; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 / #173 follow-up regression sentry: i32 shifts by
; constant. Off-by-one risk zones at byte/word boundaries
; (counts 1, 7, 8, 15, 16, 31). All three directions
; (shl/lshr/ashr). MC6809 has no native i32 shift; the legalizer
; routes constant-count shifts via either inline byte shifts or
; a const-folded libcall — this sentry guards both shapes from
; regressing.

target triple = "mc6809-unknown-unknown"

define i32 @shl_i32_1(i32 %x) {
; O0-LABEL: shl_i32_1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #1
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 1
  ret i32 %r
}

define i32 @shl_i32_7(i32 %x) {
; O0-LABEL: shl_i32_7:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #7
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_7:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #7
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 7
  ret i32 %r
}

define i32 @shl_i32_8(i32 %x) {
; O0-LABEL: shl_i32_8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #8
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #8
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 8
  ret i32 %r
}

define i32 @shl_i32_15(i32 %x) {
; O0-LABEL: shl_i32_15:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #15
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_15:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #15
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 15
  ret i32 %r
}

define i32 @shl_i32_16(i32 %x) {
; O0-LABEL: shl_i32_16:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #16
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_16:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #16
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 16
  ret i32 %r
}

define i32 @shl_i32_31(i32 %x) {
; O0-LABEL: shl_i32_31:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #31
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_31:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #31
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 31
  ret i32 %r
}

define i32 @lshr_i32_1(i32 %x) {
; O0-LABEL: lshr_i32_1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #1
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i32_1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = lshr i32 %x, 1
  ret i32 %r
}

define i32 @lshr_i32_8(i32 %x) {
; O0-LABEL: lshr_i32_8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #8
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i32_8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #8
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = lshr i32 %x, 8
  ret i32 %r
}

define i32 @lshr_i32_16(i32 %x) {
; O0-LABEL: lshr_i32_16:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #16
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i32_16:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #16
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = lshr i32 %x, 16
  ret i32 %r
}

define i32 @lshr_i32_31(i32 %x) {
; O0-LABEL: lshr_i32_31:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #31
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i32_31:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #31
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = lshr i32 %x, 31
  ret i32 %r
}

define i32 @ashr_i32_1(i32 %x) {
; O0-LABEL: ashr_i32_1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #1
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i32_1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = ashr i32 %x, 1
  ret i32 %r
}

define i32 @ashr_i32_8(i32 %x) {
; O0-LABEL: ashr_i32_8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #8
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i32_8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #8
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = ashr i32 %x, 8
  ret i32 %r
}

define i32 @ashr_i32_16(i32 %x) {
; O0-LABEL: ashr_i32_16:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #16
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i32_16:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #16
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = ashr i32 %x, 16
  ret i32 %r
}

define i32 @ashr_i32_31(i32 %x) {
; O0-LABEL: ashr_i32_31:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #31
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i32_31:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #31
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = ashr i32 %x, 31
  ret i32 %r
}
