; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 / #173 follow-up regression sentry: i32 negation,
; including INT32_MIN (= 0x80000000). INT32_MIN is its own
; negation under two's complement (0 - INT32_MIN == INT32_MIN);
; if a future change mishandles the carry-out of bit 31 in the
; i32 SUB chain, the shape of `neg_i32` changes detectably.
;
; Mirrors test/CodeGen/MC6809/i64/i64-min-negate.ll one width down.

target triple = "mc6809-unknown-unknown"

define i32 @neg_i32(i32 %x) {
; O0-LABEL: neg_i32:
; O0:       ; %bb.0:
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 8,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    tfr a,b
; O0-NEXT:    sbcb 7,s
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 6,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 5,s
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 4,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O2-LABEL: neg_i32:
; O2:       ; %bb.0:
; O2-NEXT:    leas -2,s
; O2-NEXT:    lda #0
; O2-NEXT:    tfr a,b
; O2-NEXT:    subb 7,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 6,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 5,s
; O2-NEXT:    sbca 4,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
  %r = sub i32 0, %x
  ret i32 %r
}

define i32 @mul_neg1(i32 %x) {
; O0-LABEL: mul_neg1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #-1
; O0-NEXT:    std 6,s
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: mul_neg1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -2,s
; O2-NEXT:    lda #0
; O2-NEXT:    tfr a,b
; O2-NEXT:    subb 7,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 6,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 5,s
; O2-NEXT:    sbca 4,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
  %r = mul i32 %x, -1
  ret i32 %r
}

define i32 @double_neg(i32 %x) {
; O0-LABEL: double_neg:
; O0:       ; %bb.0:
; O0-NEXT:    leas -7,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    subb 12,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 10,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 9,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    subb 4,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    tfr a,b
; O0-NEXT:    sbcb 6,s
; O0-NEXT:    lda 2,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 1,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 5,s
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 5,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 7,s
; O0-NEXT:    rts
;
; O2-LABEL: double_neg:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 4,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    rts
  %n = sub i32 0, %x
  %r = sub i32 0, %n
  ret i32 %r
}
