; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 / #173 follow-up regression sentry: i32 select and PHI.
; Both move a 4-byte aggregate between basic blocks. G_SELECT for
; i32 decomposes per-byte; G_PHI for i32 splits into 4 i8 PHIs.
; If either path miswires a byte, the wrong half of either
; argument leaks through. Mirrors i64-select-phi.ll one width
; down.

target triple = "mc6809-unknown-unknown"

define i32 @select_i32(i1 %c, i32 %a, i32 %b) {
; O0-LABEL: select_i32:
; O0:       ; %bb.0:
; O0-NEXT:    andb #1
; O0-NEXT:    lbeq .LBB0_2
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB0_3
; O0-NEXT:  .LBB0_2:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB0_3
; O0-NEXT:  .LBB0_3:
; O0-NEXT:    tstb
; O0-NEXT:    lbeq .LBB0_5
; O0-NEXT:  ; %bb.4:
; O0-NEXT:    ldd 2,s
; O0-NEXT:    lbra .LBB0_6
; O0-NEXT:  .LBB0_5:
; O0-NEXT:    ldd 6,s
; O0-NEXT:    lbra .LBB0_6
; O0-NEXT:  .LBB0_6:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    rts
;
; O2-LABEL: select_i32:
; O2:       ; %bb.0:
; O2-NEXT:    andb #1
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    tstb
; O2-NEXT:    lbne .LBB0_2
; O2-NEXT:  ; %bb.1: ; %select.false
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:  .LBB0_2: ; %select.end
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std ,x
; O2-NEXT:    rts
  %r = select i1 %c, i32 %a, i32 %b
  ret i32 %r
}

define i32 @phi_i32(i1 %c, i32 %a, i32 %b) {
; O0-LABEL: phi_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    andb #1
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 13,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 11,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tstb
; O0-NEXT:    lbeq .LBB1_2
; O0-NEXT:  ; %bb.1: ; %then
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb #1
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    tfr a,b
; O0-NEXT:    adcb #0
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 4,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    lbra .LBB1_3
; O0-NEXT:  .LBB1_2: ; %else
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb #2
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    tfr a,b
; O0-NEXT:    adcb #0
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 4,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    lbra .LBB1_3
; O0-NEXT:  .LBB1_3: ; %join
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O2-LABEL: phi_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    andb #1
; O2-NEXT:    beq .LBB1_2
; O2-NEXT:  ; %bb.1: ; %then
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb #1
; O2-NEXT:    bra .LBB1_3
; O2-NEXT:  .LBB1_2: ; %else
; O2-NEXT:    ldd 11,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 9,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb #2
; O2-NEXT:  .LBB1_3: ; %join
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    adcb #0
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 4,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb 1,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
entry:
  br i1 %c, label %then, label %else
then:
  %t = add i32 %a, 1
  br label %join
else:
  %e = add i32 %b, 2
  br label %join
join:
  %r = phi i32 [%t, %then], [%e, %else]
  ret i32 %r
}

define i32 @select_chain(i1 %c1, i1 %c2, i32 %a, i32 %b, i32 %d) {
; O0-LABEL: select_chain:
; O0:       ; %bb.0:
; O0-NEXT:    andb #1
; O0-NEXT:    lda 2,s
; O0-NEXT:    anda #1
; O0-NEXT:    lbeq .LBB2_5
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    tstb
; O0-NEXT:    lbeq .LBB2_3
; O0-NEXT:  ; %bb.2:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB2_4
; O0-NEXT:  .LBB2_3:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 11,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB2_4
; O0-NEXT:  .LBB2_4:
; O0-NEXT:    lbra .LBB2_6
; O0-NEXT:  .LBB2_5:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 15,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB2_6
; O0-NEXT:  .LBB2_6:
; O0-NEXT:    tsta
; O0-NEXT:    lbeq .LBB2_11
; O0-NEXT:  ; %bb.7:
; O0-NEXT:    tstb
; O0-NEXT:    lbeq .LBB2_9
; O0-NEXT:  ; %bb.8:
; O0-NEXT:    ldd 3,s
; O0-NEXT:    lbra .LBB2_10
; O0-NEXT:  .LBB2_9:
; O0-NEXT:    ldd 7,s
; O0-NEXT:    lbra .LBB2_10
; O0-NEXT:  .LBB2_10:
; O0-NEXT:    lbra .LBB2_12
; O0-NEXT:  .LBB2_11:
; O0-NEXT:    ldd 11,s
; O0-NEXT:    lbra .LBB2_12
; O0-NEXT:  .LBB2_12:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    rts
;
; O2-LABEL: select_chain:
; O2:       ; %bb.0:
; O2-NEXT:    andb #1
; O2-NEXT:    lda 2,s
; O2-NEXT:    anda #1
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    tstb
; O2-NEXT:    bne .LBB2_2
; O2-NEXT:  ; %bb.1: ; %select.false
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 11,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 9,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:  .LBB2_2: ; %select.end
; O2-NEXT:    tsta
; O2-NEXT:    bne .LBB2_4
; O2-NEXT:  ; %bb.3: ; %select.false2
; O2-NEXT:    ldd 13,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 11,s
; O2-NEXT:    std <__rs1
; O2-NEXT:  .LBB2_4: ; %select.end1
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std ,x
; O2-NEXT:    rts
  %s1 = select i1 %c1, i32 %a, i32 %b
  %s2 = select i1 %c2, i32 %s1, i32 %d
  ret i32 %s2
}
