; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 / #173 follow-up regression sentry: i32 division/shift
; by power-of-2. Today these go via the libcall (__divsi3 /
; __udivsi3 — hand-asm in compiler-rt/lib/builtins/mc6809/divsi.S
; — or __ashrsi3 / __lshrsi3 if the front-end already strength-
; reduced). Recording current behaviour as a baseline so a future
; strength-reduction pass shows up as a delta. NB: signed sdiv-by-2
; is NOT the same as ashr-by-1 for negative operands (round-to-zero
; vs round-to-minus-infinity), so they're checked separately.

target triple = "mc6809-unknown-unknown"

define i32 @sdiv_i32_2(i32 %x) {
; O0-LABEL: sdiv_i32_2:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #2
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __divsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: sdiv_i32_2:
; O2:       ; %bb.0:
; O2-NEXT:    leas -18,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 5,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 24,u
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #31
; O2-NEXT:    std 8,u ; 2-byte Folded Spill
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 10,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 8,u ; 2-byte Folded Reload
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 14,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 8,u ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 7,u ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 27,u
; O2-NEXT:    stb 4,u ; 1-byte Folded Spill
; O2-NEXT:    adca 26,u
; O2-NEXT:    ldb 8,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,u
; O2-NEXT:    stb 8,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,u
; O2-NEXT:    stb 7,u ; 1-byte Folded Spill
; O2-NEXT:    leas -6,s
; O2-NEXT:    ldb 4,u
; O2-NEXT:    std 2,s
; O2-NEXT:    ldb 8,u
; O2-NEXT:    lda 7,u
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 18,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 5,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 18,s
; O2-NEXT:    rts
  %r = sdiv i32 %x, 2
  ret i32 %r
}

define i32 @udiv_i32_4(i32 %x) {
; O0-LABEL: udiv_i32_4:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #4
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __udivsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: udiv_i32_4:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    leas -6,s
; O2-NEXT:    ldd #2
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = udiv i32 %x, 4
  ret i32 %r
}

define i32 @ashr_i32_1(i32 %x) {
; O0-LABEL: ashr_i32_1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #1
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i32_1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = ashr i32 %x, 1
  ret i32 %r
}

define i32 @lshr_i32_2(i32 %x) {
; O0-LABEL: lshr_i32_2:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #2
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i32_2:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    leas -6,s
; O2-NEXT:    ldd #2
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = lshr i32 %x, 2
  ret i32 %r
}

define i32 @shl_i32_3(i32 %x) {
; O0-LABEL: shl_i32_3:
; O0:       ; %bb.0:
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #3
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashlsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 6,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i32_3:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -6,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #3
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashlsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 6,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = shl i32 %x, 3
  ret i32 %r
}
