; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=MC6809-O2

; Bug #165 Phase E regression: prove the post-RA scheduler respects
; the compare→branch CC dependency edge. The scheduler reads the per-
; instruction CC clobbers from the .td (audited clean in #165 phase
; A2; load-bearing comment at MC6809InstrInfo.td:507-526 documents
; why branches MUST carry `Uses = [N, Z, V, C]`). If a future change
; weakens any of those Defs/Uses annotations, this test will fail
; because the scheduler will move a CC-clobbering load (LDD/STD/LEAS)
; into the gap between CMPD #0 and the conditional branch.
;
; Shape: small comparison + branch, with enough surrounding work to
; give the post-RA scheduler scheduling candidates. The CHECK lines
; assert that no CC-clobbering instruction appears between the CMP*
; that sets the flags and the LB* that reads them.

target triple = "mc6809"

declare void @sink_a(i16)
declare void @sink_b(i16)

define i16 @cmp_eq_branch(i16 %x, i16 %y, i16 %z) {
; MC6809-O2-LABEL: cmp_eq_branch:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    pshs u
; MC6809-O2-NEXT:    tfr s,u
; MC6809-O2-NEXT:    cmpx #0
; MC6809-O2-NEXT:    beq .LBB0_2
; MC6809-O2-NEXT:  ; %bb.1: ; %else
; MC6809-O2-NEXT:    ldd 6,u
; MC6809-O2-NEXT:    tfr d,x
; MC6809-O2-NEXT:    lbsr sink_b
; MC6809-O2-NEXT:    ldd 6,u
; MC6809-O2-NEXT:    bra .LBB0_3
; MC6809-O2-NEXT:  .LBB0_2: ; %then
; MC6809-O2-NEXT:    ldd 4,u
; MC6809-O2-NEXT:    tfr d,x
; MC6809-O2-NEXT:    lbsr sink_a
; MC6809-O2-NEXT:    ldd 4,u
; MC6809-O2-NEXT:  .LBB0_3: ; %then
; MC6809-O2-NEXT:    tfr d,x
; MC6809-O2-NEXT:    tfr u,s
; MC6809-O2-NEXT:    puls u
; MC6809-O2-NEXT:    rts
entry:
  %cmp = icmp eq i16 %x, 0
  br i1 %cmp, label %then, label %else

then:
  call void @sink_a(i16 %y)
  ret i16 %y

else:
  call void @sink_b(i16 %z)
  ret i16 %z
}
