; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3
; ModuleID = 'add.c'

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @add_s_i8(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addb 2,s
; CHECK-HD6309-NEXT:    addb 3,s
; CHECK-HD6309-NEXT:    addb 4,s
; CHECK-HD6309-NEXT:    addb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    addb 2,s
; O0-NEXT:    addb 3,s
; O0-NEXT:    addb 4,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    rts
entry:
  %add = add i8 %a, %b
  %add3 = add i8 %add, %c
  %add5 = add i8 %add3, %d
  %add7 = add i8 %add5, %e
  ret i8 %add7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @add_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    addb #5
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addb #5
; CHECK-HD6309-NEXT:    addb 2,s
; CHECK-HD6309-NEXT:    addb 3,s
; CHECK-HD6309-NEXT:    addb 4,s
; CHECK-HD6309-NEXT:    addb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    addb #5
; O0-NEXT:    addb 2,s
; O0-NEXT:    addb 3,s
; O0-NEXT:    addb 4,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    addb #5
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    addb #5
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    addb #5
; O3-NEXT:    rts
entry:
  %add4 = add i8 %a, 5
  %add5 = add i8 %add4, %b
  %add7 = add i8 %add5, %c
  %add9 = add i8 %add7, %d
  %add10 = add i8 %add9, %e
  ret i8 %add10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @add_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addb 2,s
; CHECK-HD6309-NEXT:    addb 3,s
; CHECK-HD6309-NEXT:    addb 4,s
; CHECK-HD6309-NEXT:    addb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    addb 2,s
; O0-NEXT:    addb 3,s
; O0-NEXT:    addb 4,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    rts
entry:
  %add = add i8 %a, %b
  %add3 = add i8 %add, %c
  %add5 = add i8 %add3, %d
  %add7 = add i8 %add5, %e
  ret i8 %add7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @add_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    addb #45
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addb #45
; CHECK-HD6309-NEXT:    addb 2,s
; CHECK-HD6309-NEXT:    addb 3,s
; CHECK-HD6309-NEXT:    addb 4,s
; CHECK-HD6309-NEXT:    addb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    addb #45
; O0-NEXT:    addb 2,s
; O0-NEXT:    addb 3,s
; O0-NEXT:    addb 4,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    addb #45
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    addb #45
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    addb #45
; O3-NEXT:    rts
entry:
  %add4 = add i8 %a, 45
  %add5 = add i8 %add4, %b
  %add7 = add i8 %add5, %c
  %add9 = add i8 %add7, %d
  %add10 = add i8 %add9, %e
  ret i8 %add10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @add_s_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addd 2,s
; CHECK-HD6309-NEXT:    addd 4,s
; CHECK-HD6309-NEXT:    addd 6,s
; CHECK-HD6309-NEXT:    addd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    addb 3,s
; O0-NEXT:    adca 2,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    adca 4,s
; O0-NEXT:    addb 7,s
; O0-NEXT:    adca 6,s
; O0-NEXT:    addb 9,s
; O0-NEXT:    adca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 3,s
; O1-NEXT:    adca 2,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    adca 4,s
; O1-NEXT:    addb 7,s
; O1-NEXT:    adca 6,s
; O1-NEXT:    addb 9,s
; O1-NEXT:    adca 8,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 3,s
; O2-NEXT:    adca 2,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    adca 4,s
; O2-NEXT:    addb 7,s
; O2-NEXT:    adca 6,s
; O2-NEXT:    addb 9,s
; O2-NEXT:    adca 8,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 3,s
; O3-NEXT:    adca 2,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    adca 4,s
; O3-NEXT:    addb 7,s
; O3-NEXT:    adca 6,s
; O3-NEXT:    addb 9,s
; O3-NEXT:    adca 8,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %add = add nsw i16 %a, %b
  %add1 = add nsw i16 %add, %c
  %add2 = add nsw i16 %add1, %d
  %add3 = add nsw i16 %add2, %e
  ret i16 %add3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @add_s_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leax 3149,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addd #3149
; CHECK-HD6309-NEXT:    addd 2,s
; CHECK-HD6309-NEXT:    addd 4,s
; CHECK-HD6309-NEXT:    addd 6,s
; CHECK-HD6309-NEXT:    addd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    addb #77
; O0-NEXT:    adca #12
; O0-NEXT:    addb 3,s
; O0-NEXT:    adca 2,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    adca 4,s
; O0-NEXT:    addb 7,s
; O0-NEXT:    adca 6,s
; O0-NEXT:    addb 9,s
; O0-NEXT:    adca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 3,s
; O1-NEXT:    adca 2,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    adca 4,s
; O1-NEXT:    addb 7,s
; O1-NEXT:    adca 6,s
; O1-NEXT:    addb 9,s
; O1-NEXT:    adca 8,s
; O1-NEXT:    addb #77
; O1-NEXT:    adca #12
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 3,s
; O2-NEXT:    adca 2,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    adca 4,s
; O2-NEXT:    addb 7,s
; O2-NEXT:    adca 6,s
; O2-NEXT:    addb 9,s
; O2-NEXT:    adca 8,s
; O2-NEXT:    addb #77
; O2-NEXT:    adca #12
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 3,s
; O3-NEXT:    adca 2,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    adca 4,s
; O3-NEXT:    addb 7,s
; O3-NEXT:    adca 6,s
; O3-NEXT:    addb 9,s
; O3-NEXT:    adca 8,s
; O3-NEXT:    addb #77
; O3-NEXT:    adca #12
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %add2 = add i16 %a, 3149
  %add3 = add i16 %add2, %b
  %add4 = add i16 %add3, %c
  %add5 = add i16 %add4, %d
  %add6 = add i16 %add5, %e
  ret i16 %add6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @add_u_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addd 2,s
; CHECK-HD6309-NEXT:    addd 4,s
; CHECK-HD6309-NEXT:    addd 6,s
; CHECK-HD6309-NEXT:    addd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    addb 3,s
; O0-NEXT:    adca 2,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    adca 4,s
; O0-NEXT:    addb 7,s
; O0-NEXT:    adca 6,s
; O0-NEXT:    addb 9,s
; O0-NEXT:    adca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 3,s
; O1-NEXT:    adca 2,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    adca 4,s
; O1-NEXT:    addb 7,s
; O1-NEXT:    adca 6,s
; O1-NEXT:    addb 9,s
; O1-NEXT:    adca 8,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 3,s
; O2-NEXT:    adca 2,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    adca 4,s
; O2-NEXT:    addb 7,s
; O2-NEXT:    adca 6,s
; O2-NEXT:    addb 9,s
; O2-NEXT:    adca 8,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 3,s
; O3-NEXT:    adca 2,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    adca 4,s
; O3-NEXT:    addb 7,s
; O3-NEXT:    adca 6,s
; O3-NEXT:    addb 9,s
; O3-NEXT:    adca 8,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %add = add i16 %a, %b
  %add1 = add i16 %add, %c
  %add2 = add i16 %add1, %d
  %add3 = add i16 %add2, %e
  ret i16 %add3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @add_u_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leax 8447,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addd #8447
; CHECK-HD6309-NEXT:    addd 2,s
; CHECK-HD6309-NEXT:    addd 4,s
; CHECK-HD6309-NEXT:    addd 6,s
; CHECK-HD6309-NEXT:    addd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    addb #255
; O0-NEXT:    adca #32
; O0-NEXT:    addb 3,s
; O0-NEXT:    adca 2,s
; O0-NEXT:    addb 5,s
; O0-NEXT:    adca 4,s
; O0-NEXT:    addb 7,s
; O0-NEXT:    adca 6,s
; O0-NEXT:    addb 9,s
; O0-NEXT:    adca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 3,s
; O1-NEXT:    adca 2,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    adca 4,s
; O1-NEXT:    addb 7,s
; O1-NEXT:    adca 6,s
; O1-NEXT:    addb 9,s
; O1-NEXT:    adca 8,s
; O1-NEXT:    addb #-1
; O1-NEXT:    adca #32
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 3,s
; O2-NEXT:    adca 2,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    adca 4,s
; O2-NEXT:    addb 7,s
; O2-NEXT:    adca 6,s
; O2-NEXT:    addb 9,s
; O2-NEXT:    adca 8,s
; O2-NEXT:    addb #-1
; O2-NEXT:    adca #32
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 3,s
; O3-NEXT:    adca 2,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    adca 4,s
; O3-NEXT:    addb 7,s
; O3-NEXT:    adca 6,s
; O3-NEXT:    addb 9,s
; O3-NEXT:    adca 8,s
; O3-NEXT:    addb #-1
; O3-NEXT:    adca #32
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %add2 = add i16 %a, 8447
  %add3 = add i16 %add2, %b
  %add4 = add i16 %add3, %c
  %add5 = add i16 %add4, %d
  %add6 = add i16 %add5, %e
  ret i16 %add6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @add_s_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 17,u
; CHECK-NEXT:    adca 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addw 4,s
; CHECK-HD6309-NEXT:    adcd 2,s
; CHECK-HD6309-NEXT:    addw 8,s
; CHECK-HD6309-NEXT:    adcd 6,s
; CHECK-HD6309-NEXT:    addw 12,s
; CHECK-HD6309-NEXT:    adcd 10,s
; CHECK-HD6309-NEXT:    addw 16,s
; CHECK-HD6309-NEXT:    adcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 7,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 10,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 9,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 16,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 13,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 20,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 19,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 18,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 17,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 24,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 21,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 2,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb 1,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 10,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 9,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 16,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 13,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 20,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 19,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 18,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 17,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 24,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 21,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb 1,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 7,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 10,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 9,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 16,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 13,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 20,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 19,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 18,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 17,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 24,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 21,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 2,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb 1,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %add = add nsw i32 %a, %b
  %add1 = add nsw i32 %add, %c
  %add2 = add nsw i32 %add1, %d
  %add3 = add nsw i32 %add2, %e
  ret i32 %add3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @add_s_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 17,u
; CHECK-NEXT:    adca 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd #-21923
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb #8
; CHECK-NEXT:    adca #0
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addw #43613
; CHECK-HD6309-NEXT:    adcd #8
; CHECK-HD6309-NEXT:    addw 4,s
; CHECK-HD6309-NEXT:    adcd 2,s
; CHECK-HD6309-NEXT:    addw 8,s
; CHECK-HD6309-NEXT:    adcd 6,s
; CHECK-HD6309-NEXT:    addw 12,s
; CHECK-HD6309-NEXT:    adcd 10,s
; CHECK-HD6309-NEXT:    addw 16,s
; CHECK-HD6309-NEXT:    adcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_s_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb #93
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #170
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #8
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca #0
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 7,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 10,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 9,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 16,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 13,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 20,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 19,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 18,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 17,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 24,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 21,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb #93
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-86
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #8
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca #0
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 2,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb 1,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 10,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 9,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 16,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 13,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 20,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 19,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 18,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 17,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 24,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 21,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb #93
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-86
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #8
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca #0
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb 1,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 7,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 10,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 9,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 16,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 13,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 20,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 19,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 18,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 17,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 24,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 21,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb #93
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-86
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #8
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca #0
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 2,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb 1,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %add2 = add i32 %a, 567901
  %add3 = add i32 %add2, %b
  %add4 = add i32 %add3, %c
  %add5 = add i32 %add4, %d
  %add6 = add i32 %add5, %e
  ret i32 %add6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @add_u_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 17,u
; CHECK-NEXT:    adca 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addw 4,s
; CHECK-HD6309-NEXT:    adcd 2,s
; CHECK-HD6309-NEXT:    addw 8,s
; CHECK-HD6309-NEXT:    adcd 6,s
; CHECK-HD6309-NEXT:    addw 12,s
; CHECK-HD6309-NEXT:    adcd 10,s
; CHECK-HD6309-NEXT:    addw 16,s
; CHECK-HD6309-NEXT:    adcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 7,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 10,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 9,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 16,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 13,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 20,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 19,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 18,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 17,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 24,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 21,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 2,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb 1,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 10,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 9,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 16,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 13,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 20,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 19,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 18,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 17,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 24,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 21,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb 1,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 7,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 10,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 9,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 16,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 13,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 20,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 19,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 18,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 17,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 24,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 21,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 2,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb 1,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %add = add i32 %a, %b
  %add1 = add i32 %add, %c
  %add2 = add i32 %add1, %d
  %add3 = add i32 %add2, %e
  ret i32 %add3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @add_u_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: add_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 17,u
; CHECK-NEXT:    adca 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd #-2081
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb #126
; CHECK-NEXT:    adca #0
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: add_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    addw #63455
; CHECK-HD6309-NEXT:    adcd #126
; CHECK-HD6309-NEXT:    addw 4,s
; CHECK-HD6309-NEXT:    adcd 2,s
; CHECK-HD6309-NEXT:    addw 8,s
; CHECK-HD6309-NEXT:    adcd 6,s
; CHECK-HD6309-NEXT:    addw 12,s
; CHECK-HD6309-NEXT:    adcd 10,s
; CHECK-HD6309-NEXT:    addw 16,s
; CHECK-HD6309-NEXT:    adcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: add_u_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #-2081
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #126
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 8,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 7,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 6,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 5,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    addb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    adca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 7,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 10,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 9,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 16,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 13,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 20,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 19,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 18,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 17,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb 24,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 21,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    addb #-33
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-9
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #126
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca #0
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 2,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb 1,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 7,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 10,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 9,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 16,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 13,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 20,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 19,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 18,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 17,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb 24,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 21,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    addb #-33
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-9
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #126
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca #0
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb 1,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 7,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 10,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 9,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 16,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 13,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 20,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 19,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 18,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 17,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb 24,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 21,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    addb #-33
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-9
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #126
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca #0
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 2,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb 1,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %add2 = add i32 8320991, %a
  %add3 = add i32 %add2, %b
  %add4 = add i32 %add3, %c
  %add5 = add i32 %add4, %d
  %add6 = add i32 %add5, %e
  ret i32 %add6
}

define dso_local i64 @add_s_i64(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: add_s_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 17,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 16,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 12,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    adca 11,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 10,s
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 33,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 32,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 31,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 30,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 29,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 28,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 27,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 26,s
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca 38,s
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    adca 46,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda 5,s ; 1-byte Folded Reload
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    adca 44,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 43,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 3,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 17,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 16,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 13,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 12,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    adca 11,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca 10,s
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 33,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 32,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 31,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 30,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 29,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 28,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 27,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 38,s
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    adca 46,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 45,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 44,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 43,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 3,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 17,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 16,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 13,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 12,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    adca 11,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca 10,s
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 33,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 32,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 31,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 30,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 29,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 28,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 27,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 38,s
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    adca 46,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 45,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 44,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 43,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 3,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 17,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 16,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 13,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 12,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    adca 11,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca 10,s
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 33,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 32,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 31,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 30,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 29,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 28,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 27,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 38,s
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    adca 46,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 45,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 44,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 43,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 3,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
entry:
  %add = add nsw i64 %b, %a
  %add1 = add nsw i64 %add, %c
  %add2 = add nsw i64 %add1, %d
  %add3 = add nsw i64 %add2, %e
  ret i64 %add3
}

define dso_local i64 @add_s_i64_consts(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: add_s_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb #137
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #103
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #69
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #35
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #1
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #0
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    adca #0
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 25,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 24,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 21,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 20,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 18,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 33,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 32,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 31,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 30,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 29,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 28,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 27,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 26,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 38,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    adca 36,s
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 5,s ; 1-byte Folded Reload
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 44,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 43,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 5,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: add_s_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 25,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 24,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 21,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 20,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 33,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 32,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 31,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 30,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 29,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 28,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 27,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 38,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca 36,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 45,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    adca 44,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 43,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb #-119
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #103
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #69
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #35
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca #1
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca #0
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: add_s_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 25,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 24,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 21,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 20,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 33,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 32,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 31,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 30,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 29,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 28,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 27,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 38,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca 36,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 45,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    adca 44,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 43,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb #-119
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #103
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #69
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #35
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca #1
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: add_s_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 25,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 24,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 21,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 20,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 33,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 32,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 31,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 30,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 29,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 28,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 27,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 38,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca 36,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 45,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    adca 44,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 43,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb #-119
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #103
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #69
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #35
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca #1
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca #0
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
entry:
  %add = add i64 %a, 4886718345
  %add1 = add i64 %add, %b
  %add2 = add i64 %add1, %c
  %add3 = add i64 %add2, %d
  %add4 = add i64 %add3, %e
  ret i64 %add4
}

define dso_local i64 @add_u_i64(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: add_u_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 17,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 16,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 15,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 12,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    adca 11,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 10,s
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 33,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 32,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 31,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 30,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 29,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 28,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 27,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 26,s
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca 38,s
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    adca 46,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda 5,s ; 1-byte Folded Reload
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    adca 44,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 43,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 3,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 17,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 16,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 15,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 14,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 13,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 12,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    adca 11,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca 10,s
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 33,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 32,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 31,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 30,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 29,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 28,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 27,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 38,s
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    adca 46,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 45,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 44,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 43,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 3,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 17,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 16,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 15,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 14,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 13,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 12,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    adca 11,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca 10,s
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 33,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 32,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 31,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 30,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 29,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 28,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 27,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 38,s
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    adca 46,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 45,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 44,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 43,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 3,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 17,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 16,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 15,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 14,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 13,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 12,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    adca 11,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca 10,s
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 33,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 32,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 31,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 30,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 29,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 28,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 27,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 38,s
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    adca 46,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 45,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 44,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 43,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 3,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
entry:
  %add = add i64 %b, %a
  %add1 = add i64 %add, %c
  %add2 = add i64 %add1, %d
  %add3 = add i64 %add2, %e
  ret i64 %add3
}

define dso_local i64 @add_u_i64_consts(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: add_u_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb #239
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #190
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #173
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #222
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #0
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #0
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    adca #0
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca #0
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 25,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 24,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 23,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 21,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 20,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 19,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 18,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 33,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 32,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 31,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 30,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 29,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 28,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 27,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 26,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 38,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    adca 36,s
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 5,s ; 1-byte Folded Reload
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    adca 44,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 43,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 5,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: add_u_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 25,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 24,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 23,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 21,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 20,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 33,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 32,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 31,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 30,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 29,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 28,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 27,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 38,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca 36,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 45,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    adca 44,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 43,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb #-17
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-66
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-83
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-34
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca #0
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    adca #0
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: add_u_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 25,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 24,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 21,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 20,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 33,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 32,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 31,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 30,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 29,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 28,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 27,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 38,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca 36,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 45,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    adca 44,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 43,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb #-17
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-66
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-83
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-34
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: add_u_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 25,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 24,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 23,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 21,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 20,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 33,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 32,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 31,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 30,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 29,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 28,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 27,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 38,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca 36,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 45,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    adca 44,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 43,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb #-17
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-66
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-83
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-34
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca #0
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    adca #0
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
entry:
  %add = add i64 %a, 3735928559
  %add1 = add i64 %add, %b
  %add2 = add i64 %add1, %c
  %add3 = add i64 %add2, %d
  %add4 = add i64 %add3, %e
  ret i64 %add4
}

