; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O2

; Bug #179 regression sentry: branch-over-branch fold.
; The pattern below would emit `lbXX L1; lbra L2; L1:` without
; Class 6 of MC6809FinalLowering — the conditional jumps to the
; layout successor, the unconditional jumps over it. Class 6
; should fold this to a single inverted conditional `lbYY L2;
; L1:` (fall through to L1).
;
; Two RUN lines confirm the fold fires at both -O0 (where the
; standard BranchFolderPass doesn't run, so Class 6 is the only
; safety net) and -O2 (where BranchFolder catches most cases but
; Class 6 backstops anything it missed).

target triple = "mc6809-unknown-unknown"

declare void @sink(i16)

define i16 @cond_skip_join(i16 %x, i16 %a, i16 %b) {
; O0-LABEL: cond_skip_join:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    cmpx #0
; O0-NEXT:    lbne .LBB0_2
; O0-NEXT:  ; %bb.1: ; %if.then
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr sink
; O0-NEXT:    ldd 6,u
; O0-NEXT:    lbra .LBB0_2
; O0-NEXT:  .LBB0_2: ; %if.end
; O0-NEXT:    tfr d,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O2-LABEL: cond_skip_join:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    cmpx #0
; O2-NEXT:    bne .LBB0_2
; O2-NEXT:  ; %bb.1: ; %if.then
; O2-NEXT:    ldd 4,u
; O2-NEXT:    tfr d,x
; O2-NEXT:    lbsr sink
; O2-NEXT:    ldd 6,u
; O2-NEXT:  .LBB0_2: ; %if.end
; O2-NEXT:    tfr d,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
entry:
  %t = icmp eq i16 %x, 0
  br i1 %t, label %if.then, label %if.end
if.then:
  call void @sink(i16 %a)
  br label %if.end
if.end:
  ret i16 %b
}
