# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=mc6809 -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s

# Regression sentinel for bug #182.
#
# `MC6809InstrInfo::isBranchOffsetInRange` once treated BR's
# `BrOffset` (= raw start-of-target minus start-of-branch) as
# the encoded displacement field, when in fact the encoded
# displacement is `BrOffset - <instruction size>` (because the
# 6809 branch displacement is from PC-after-instruction, not
# from PC-of-instruction). The mismatch caused short branches
# at the int8 boundary (raw disp ∈ [-128..-126] backward or
# [127..129] forward) to be left short by BR even though their
# encoded displacement would overflow int8.
#
# This test exercises the BACKWARD boundary at exactly raw
# disp = -128: BR's `isBranchOffsetInRange(Bbc, -128)` once
# returned true (-128 fits int8 signed) and BR did not widen.
# After the bug #182 fix, BR subtracts the 2-byte Bbc size and
# checks `isInt<8>(-130)`, which is false, so BR widens to
# `LBlbc` (the long form).
#
# Layout: bb.0 contains 126 single-byte filler instructions.
# bb.1 holds a `Bbc` whose target is bb.0. bb.1 sits at function
# offset 126; the Bbc starts at offset 126; raw disp = 0 - 126
# = -126 (encoded -128, in range). To push to the boundary,
# bb.1 contains 2 single-byte filler instructions before the
# Bbc, putting Bbc at offset 128 — raw disp = 0 - 128 = -128
# (encoded -130, just out of range). The fix must widen.
#
---
name: bug182_backward_boundary
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: bug182_backward_boundary
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $n, $z, $v, $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   Bbc_OnlyZ 7, %bb.2, implicit $z
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.0(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LBRAlb %bb.0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RTSr
  bb.0:
    successors: %bb.1
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx

  bb.1:
    successors: %bb.0, %bb.2
    liveins: $n, $z, $v, $c
    NOPx
    NOPx
    Bbc 6, %bb.0, implicit $n, implicit $z, implicit $v, implicit $c

  bb.2:
    RTSr
...
