# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=mc6809 -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s

# Regression sentinel for bug #187.
#
# `BranchJumpTable` is a custom-emitted pseudo: AsmPrinter expands it
# to ASLB+ROLA+LEAX+LDD+JMP (1+1+4+2+2 = 10 bytes). Pre-fix it had no
# `let Size = N;` declaration in MC6809InstrLogical.td, so
# `MCInstrDesc::getSize()` returned 0 and `MC6809InstrInfo::getInstSizeInBytes`
# fell back to MaxInstLength = 5 — under-counting by 5 bytes per BJT.
# That caused BranchRelaxation's block-size accounting to be 5 bytes
# short whenever a BJT sat between a Bbc and its target. Boundary-case
# Bbcs that BR thought were just in PCRel8 range were in reality just
# out of it; the AsmBackend guard fired at MC encoding time with
# `PCRel8 fixup value N out of [-128..127]`.
#
# Surfaced by picolibc's printf-family TUs at -O1/-O2:
#   - vfmprintf.c   @ -O1: PCRel8 -131 (off by 3)
#   - vfiprintf.c   @ -O2: PCRel8 +130 (off by 2)
#   - vfprintf_s.c  @ -O2: PCRel8 +128 (off by exactly 1, boundary)
#
# Fix: explicit `let Size = 10;` on BranchJumpTable matching its
# AsmPrinter expansion.
#
# Layout: bb.0 holds a forward Bbc to bb.3. Between them sits bb.1
# (BJT, 10 bytes with fix) and bb.2 (122 × NOPx filler). With the fix
# bb.3 lands at offset 134; raw disp from Bbc to bb.3 = +134, encoded
# +132 → out of int8 → BR MUST widen.
#
# If `let Size = 10;` is removed and BJT silently reverts to the
# MaxInstLength=5 fallback, bb.3 measures at offset 129, encoded disp
# +127 (in range), BR leaves Bbc short. The MC fixup-time guard would
# eventually fire, but this test catches the regression earlier — the
# CHECK lines below expect LBlbc, not Bbc.

--- |
  define void @bug187_bjt_must_widen() { ret void }
...

---
name: bug187_bjt_must_widen
tracksRegLiveness: true
jumpTable:
  kind: block-address
  entries:
    - id: 0
      blocks: [ '%bb.4', '%bb.5' ]
body: |
  ; CHECK-LABEL: name: bug187_bjt_must_widen
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $n, $z, $v, $c, $ad
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   Bbc_OnlyZ 7, %bb.1, implicit $z
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $ad
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LBRAlb %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT:   liveins: $ad
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BranchJumpTable killed renamable $ad, %jump-table.0, implicit-def dead $aa, implicit-def dead $ab, implicit-def dead $ad, implicit-def dead $aq, implicit-def dead $ix, implicit-def dead $nz, implicit-def dead $n, implicit-def $z, implicit-def dead $v, implicit-def dead $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RTSr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RTSr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   RTSr
  bb.0:
    successors: %bb.3, %bb.1
    liveins: $n, $z, $v, $c, $ad
    Bbc 6, %bb.3, implicit $n, implicit $z, implicit $v, implicit $c

  bb.1:
    successors: %bb.4, %bb.5
    liveins: $ad
    BranchJumpTable killed renamable $ad, %jump-table.0, implicit-def dead $aa, implicit-def dead $ab, implicit-def dead $ad, implicit-def dead $aq, implicit-def dead $ix, implicit-def dead $nz, implicit-def dead $n, implicit-def $z, implicit-def dead $v, implicit-def dead $c

  bb.2:
    successors: %bb.3
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx
    NOPx

  bb.3:
    RTSr

  bb.4:
    RTSr

  bb.5:
    RTSr
...
