; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s

; Regression sentinel for bug #184 (Case-1-restore subset).
;
; Bug discovered after bug #181's link.ld fix unblocked
; codegen-picolibc.s end-to-end execution. test_atol_w("-3")
; stored 0x0000FFFD instead of 0xFFFFFFFD. Reduced to a
; sext-i16-to-i32-then-negate-and-store shape (this test) and
; an analogous sext-i32-to-i64-then-negate shape (sibling test
; bug184_case1_restore_i64.ll).
;
; Root cause was in MC6809MaterializeSpills.cpp Case 1 conflict
; resolution: when a spill operand mapped to the same physical
; half ($ab) as another non-spill operand of the same MI, Case 1
; saved $ab to a stack slot and redirected the conflicting
; operand to the alt half ($aa) — but never restored $ab after
; the MI ran. The spill load + SUB then left the SUB result in
; $ab; any later MI that expected $ab to still hold the original
; operand value (per regalloc's plan) read garbage.
;
; The 4-byte borrow chain for i32 sext-then-negate exposes this
; cleanly: SEX8Implicit puts the sign byte in $ab; the byte-2 sub
; uses $ab as src2 and triggers Case 1 conflict because spill_b2
; (the dest) maps to AB; case-1 redirected src2 to $aa via stack
; save but never restored $ab afterwards. Byte-3 sub then read
; the byte-2 result instead of the sign byte → 0 - 0xFF - 1 =
; 0x00 for the topmost byte. Output: 0x00FFFFFD.
;
; Fix: have Case 1 populate the existing ASaveSlot/BSaveSlot
; mechanism so the post-MI restore at lines 1077-1088 fires
; automatically. Tested at -O0 and -O1 against /tmp/bug184-min.ll
; reproducer; both produce 0xFFFFFFFD.
;
; KNOWN GAP (next session): test_atol_w's i32 PHI + select shape
; in codegen-picolibc.s also produces 0x0000FFFD, but its sub
; chain uses spill registers (not physical $ab) as 3rd operand,
; so Case 1 never fires for it. That's a separate manifestation
; needing further investigation; codegen-picolibc.s remains
; XFAIL'd pending that work.

target triple = "mc6809"

define void @sext_i16_to_i32_then_store(ptr %out, i16 %x) {
; CHECK-LABEL: sext_i16_to_i32_then_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -3,s
; CHECK-NEXT:    ldd 5,s
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lblt .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ldb #1
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    negb
; CHECK-NEXT:    stb 2,s ; 1-byte Folded Spill
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    subb 6,s
; CHECK-NEXT:    stb 1,s ; 1-byte Folded Spill
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    sbcb 5,s
; CHECK-NEXT:    stb ,s ; 1-byte Folded Spill
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    sbcb 2,s
; CHECK-NEXT:    sbca 2,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 3,s
; CHECK-NEXT:    lda 2,s
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    puls d
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    leas 3,s
; CHECK-NEXT:    rts
  %ext = sext i16 %x to i32
  %neg = sub nsw i32 0, %ext
  store i32 %neg, ptr %out, align 1
  ret void
}
