; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 %s -o - | FileCheck %s

; Regression sentinel for bug #184 (Case-1-restore subset, i64
; sibling of bug184_case1_restore.ll).
;
; The same MaterializeSpills Case-1-doesn't-restore bug fires
; for i64 sext-then-negate as for i32. Phase A confirmed via
; usim execution test: at -O0, sext_i32_to_i64_then_store(3)
; produced 0x0000FFFFFFFFFFFD instead of 0xFFFFFFFFFFFFFFFD —
; same top-2-bytes-wrong pattern as i32. The fix in
; MC6809MaterializeSpills.cpp Case 1 closes both i32 and i64
; manifestations simultaneously.
;
; This sentinel locks the codegen shape so a future regression
; that reverts the Case-1-restore fix will be caught at lit
; time, not at execution time.
;
; See bug184_case1_restore.ll for the i32 cousin and the full
; root-cause analysis.

target triple = "mc6809"

define void @sext_i32_to_i64_then_store(ptr %out, i32 %x) {
; CHECK-LABEL: sext_i32_to_i64_then_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -20,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    stb 19,u
; CHECK-NEXT:    cmpa #0
; CHECK-NEXT:    lblt .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ldb #1
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    stb 17,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    negb
; CHECK-NEXT:    stb 17,u
; CHECK-NEXT:    ldb 19,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    subb 27,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    ldb 19,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sbca 26,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    sbcb 25,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    sta 7,u
; CHECK-NEXT:    ldb 19,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 18,u
; CHECK-NEXT:    lda 7,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    lda 18,u
; CHECK-NEXT:    sbca 24,u
; CHECK-NEXT:    sta 18,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    stb 11,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    sbcb 17,u
; CHECK-NEXT:    stb 11,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    sbcb 17,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    sta 5,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 16,u
; CHECK-NEXT:    lda 5,u
; CHECK-NEXT:    ldb 19,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    sbcb 17,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    ldb 19,u
; CHECK-NEXT:    sbcb 17,u
; CHECK-NEXT:    stb 19,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 14,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    ldb 15,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 13,u
; CHECK-NEXT:    lda 18,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 11,u
; CHECK-NEXT:    lda 16,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    lda 14,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 20,s
; CHECK-NEXT:    rts
  %ext = sext i32 %x to i64
  %neg = sub nsw i64 0, %ext
  store i64 %neg, ptr %out, align 1
  ret void
}
