; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s

; Regression sentinel for bug #184 (Case-1-restore subset, i64
; sibling of bug184_case1_restore.ll).
;
; The same MaterializeSpills Case-1-doesn't-restore bug fires
; for i64 sext-then-negate as for i32. Phase A confirmed via
; usim execution test: at -O0, sext_i32_to_i64_then_store(3)
; produced 0x0000FFFFFFFFFFFD instead of 0xFFFFFFFFFFFFFFFD —
; same top-2-bytes-wrong pattern as i32. The fix in
; MC6809MaterializeSpills.cpp Case 1 closes both i32 and i64
; manifestations simultaneously.
;
; This sentinel locks the codegen shape so a future regression
; that reverts the Case-1-restore fix will be caught at lit
; time, not at execution time.
;
; See bug184_case1_restore.ll for the i32 cousin and the full
; root-cause analysis.

target triple = "mc6809"

define void @sext_i32_to_i64_then_store(ptr %out, i32 %x) {
; CHECK-LABEL: sext_i32_to_i64_then_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -9,s
; CHECK-NEXT:    ldd 11,s
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    cmpa #0
; CHECK-NEXT:    lblt .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    lda #1
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    anda #1
; CHECK-NEXT:    nega
; CHECK-NEXT:    sta 4,s ; 1-byte Folded Spill
; CHECK-NEXT:    stb 8,s ; 1-byte Folded Spill
; CHECK-NEXT:    lda 8,s ; 1-byte Folded Reload
; CHECK-NEXT:    suba 14,s
; CHECK-NEXT:    sta 8,s ; 1-byte Folded Spill
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sbca 13,s
; CHECK-NEXT:    sta 2,s ; 1-byte Folded Spill
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sbca 12,s
; CHECK-NEXT:    sta 1,s ; 1-byte Folded Spill
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sbca 11,s
; CHECK-NEXT:    sta ,s ; 1-byte Folded Spill
; CHECK-NEXT:    stb 7,s ; 1-byte Folded Spill
; CHECK-NEXT:    lda 7,s ; 1-byte Folded Reload
; CHECK-NEXT:    sbca 4,s
; CHECK-NEXT:    sta 7,s ; 1-byte Folded Spill
; CHECK-NEXT:    stb 6,s ; 1-byte Folded Spill
; CHECK-NEXT:    lda 4,s ; 1-byte Folded Reload
; CHECK-NEXT:    stb 3,s ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 6,s ; 1-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    sbcb ,s+
; CHECK-NEXT:    stb 6,s ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 3,s ; 1-byte Folded Reload
; CHECK-NEXT:    stb 5,s ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 5,s ; 1-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    sbcb ,s+
; CHECK-NEXT:    stb 5,s ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 3,s ; 1-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    sbcb ,s+
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 10,s
; CHECK-NEXT:    lda 4,s
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 3,s
; CHECK-NEXT:    lda 2,s
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 9,s
; CHECK-NEXT:    lda 8,s
; CHECK-NEXT:    std <__rs2
; CHECK-NEXT:    puls d
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 5,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs1
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs2
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    puls d
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    leas 9,s
; CHECK-NEXT:    rts
  %ext = sext i32 %x to i64
  %neg = sub nsw i64 0, %ext
  store i64 %neg, ptr %out, align 1
  ret void
}
