; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 %s -o - | FileCheck %s

; Regression sentinel for bug #184 (Case-1-restore subset, i64
; sibling of bug184_case1_restore.ll).
;
; The same MaterializeSpills Case-1-doesn't-restore bug fires
; for i64 sext-then-negate as for i32. Phase A confirmed via
; usim execution test: at -O0, sext_i32_to_i64_then_store(3)
; produced 0x0000FFFFFFFFFFFD instead of 0xFFFFFFFFFFFFFFFD —
; same top-2-bytes-wrong pattern as i32. The fix in
; MC6809MaterializeSpills.cpp Case 1 closes both i32 and i64
; manifestations simultaneously.
;
; This sentinel locks the codegen shape so a future regression
; that reverts the Case-1-restore fix will be caught at lit
; time, not at execution time.
;
; See bug184_case1_restore.ll for the i32 cousin and the full
; root-cause analysis.

target triple = "mc6809"

define void @sext_i32_to_i64_then_store(ptr %out, i32 %x) {
; CHECK-LABEL: sext_i32_to_i64_then_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -37,s
; CHECK-NEXT:    pshs u,y
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr x,y
; CHECK-NEXT:    sty 23,u
; CHECK-NEXT:    ldd 45,u
; CHECK-NEXT:    std 19,u
; CHECK-NEXT:    ldd 43,u
; CHECK-NEXT:    std 33,u
; CHECK-NEXT:    ldd 19,u
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 33,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 35,u
; CHECK-NEXT:    sty 21,u
; CHECK-NEXT:    ldy 21,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __cmpsi2
; CHECK-NEXT:    ldy 21,u
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    cmpb #0
; CHECK-NEXT:    lbeq .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ldb #1
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    negb
; CHECK-NEXT:    stb 32,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 34,u
; CHECK-NEXT:    subb 46,u
; CHECK-NEXT:    stb 34,u
; CHECK-NEXT:    sta 33,u
; CHECK-NEXT:    sta 18,u
; CHECK-NEXT:    sbca 45,u
; CHECK-NEXT:    sta 33,u
; CHECK-NEXT:    lda 18,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 30,u
; CHECK-NEXT:    sbcb 44,u
; CHECK-NEXT:    stb 30,u
; CHECK-NEXT:    sta 31,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    sbca 43,u
; CHECK-NEXT:    sta 31,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 28,u
; CHECK-NEXT:    sbcb 32,u
; CHECK-NEXT:    stb 28,u
; CHECK-NEXT:    sta 29,u
; CHECK-NEXT:    sta 16,u
; CHECK-NEXT:    sbca 32,u
; CHECK-NEXT:    sta 29,u
; CHECK-NEXT:    lda 16,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 26,u
; CHECK-NEXT:    sbcb 32,u
; CHECK-NEXT:    stb 26,u
; CHECK-NEXT:    ldb 32,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    sbca ,s+
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldb 34,u
; CHECK-NEXT:    lda 33,u
; CHECK-NEXT:    std 33,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldb 30,u
; CHECK-NEXT:    lda 31,u
; CHECK-NEXT:    std 31,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldb 28,u
; CHECK-NEXT:    lda 29,u
; CHECK-NEXT:    std 29,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    ldb 26,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 33,u
; CHECK-NEXT:    ldy 23,u
; CHECK-NEXT:    std 6,y
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 31,u
; CHECK-NEXT:    ldy 23,u
; CHECK-NEXT:    std 4,y
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 29,u
; CHECK-NEXT:    ldy 23,u
; CHECK-NEXT:    std 2,y
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std [23,u]
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u,y
; CHECK-NEXT:    leas 37,s
; CHECK-NEXT:    rts
  %ext = sext i32 %x to i64
  %neg = sub nsw i64 0, %ext
  store i64 %neg, ptr %out, align 1
  ret void
}
