; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s

; Regression sentinel for bug #184 (cross-block carry chain).
;
; Bug #184: when an i32 (or wider) negation lowers to a SubSetCarry chain
; that splits across basic blocks (e.g. an i32 PHI accumulator → neg →
; select i32 → store), the borrow flag CC.C is silently clobbered by any
; CC-touching MI between bb.5's last SBC and bb.9's first SBC.
;
; The wrong code computed `0x0000FFDF` for `atol_like("-3")` (top 2 bytes
; should be 0xFF, propagated from sign extension of the borrow chain).
; USim trace pinned the clobber to the `cmpb #$2d` (the is_neg=='-' check)
; that sits between bb.5 and bb.9.
;
; Fix: at instruction selection time, when the carry-in to a
; SubSetCarryUse-family consumer is a phantom-BIT1 producer in a DIFFERENT
; basic block, freeze CC.C into a byte right after the producer (via
; `MaterializeCarryToByte_i8`) and restore CC.C right before the consumer
; (via the new `MaterializeByteToCarry_i8` pseudo, which expands to a
; single LSRB). The byte vreg crosses blocks naturally as a regular ABc
; value.
;
; This codegen sentinel locks the shape produced for atol_like at -O0 —
; specifically the materialise/restore pair around the cond trampolines.
; The companion execution test is `test/MC/MC6809/Execution/codegen-picolibc.s`
; (via test_atol_w in codegen-picolibc.ll) which actually runs on usim
; and verifies the bytes. This .ll is the durable shape sentinel.

target triple = "mc6809"

define void @atol_like(ptr %out, ptr %s) {
; CHECK-LABEL: atol_like:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -19,s
; CHECK-NEXT:    pshs u,y
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 5,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldx 25,u
; CHECK-NEXT:    ldb ,x
; CHECK-NEXT:    stb 4,u ; 1-byte Folded Spill
; CHECK-NEXT:    cmpb #45
; CHECK-NEXT:    lbeq .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    lbra .LBB0_3
; CHECK-NEXT:  .LBB0_2: ; %entry
; CHECK-NEXT:    ldb #1
; CHECK-NEXT:  .LBB0_3: ; %entry
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    lda #0
; CHECK-NEXT:    sta 17,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    lda d,x
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    stb 16,u ; 1-byte Folded Spill
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    puls a
; CHECK-NEXT:    stb 15,u ; 1-byte Folded Spill
; CHECK-NEXT:    suba #48
; CHECK-NEXT:    sta 14,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 17,u ; 1-byte Folded Reload
; CHECK-NEXT:    sbca #0
; CHECK-NEXT:    ldb 16,u ; 1-byte Folded Reload
; CHECK-NEXT:    sbcb #0
; CHECK-NEXT:    stb 16,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 15,u ; 1-byte Folded Reload
; CHECK-NEXT:    sbcb #0
; CHECK-NEXT:    sta 9,u ; 1-byte Folded Spill
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    stb 15,u ; 1-byte Folded Spill
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    lbra .LBB0_4
; CHECK-NEXT:  .LBB0_4: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    leay 19,u
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    std 7,u ; 2-byte Folded Spill
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs1
; CHECK-NEXT:    std 10,u ; 2-byte Folded Spill
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs1
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldd #10
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    stb 18,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    ldb 18,u ; 1-byte Folded Reload
; CHECK-NEXT:    addb 14,u
; CHECK-NEXT:    stb 18,u ; 1-byte Folded Spill
; CHECK-NEXT:    adca 9,u
; CHECK-NEXT:    sta 13,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 16,u ; 1-byte Folded Reload
; CHECK-NEXT:    adcb 20,u
; CHECK-NEXT:    stb 12,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 15,u ; 1-byte Folded Reload
; CHECK-NEXT:    adca 19,u
; CHECK-NEXT:    ldb 17,u ; 1-byte Folded Reload
; CHECK-NEXT:    addb #1
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 12,u
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    stb 17,u ; 1-byte Folded Spill
; CHECK-NEXT:    cmpb #2
; CHECK-NEXT:    lbne .LBB0_4
; CHECK-NEXT:  ; %bb.5: ; %exit
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    sta 17,u ; 1-byte Folded Spill
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd 7,u ; 2-byte Folded Reload
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb <__rs1lo
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    puls b
; CHECK-NEXT:    sta 16,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda <__rs1hi
; CHECK-NEXT:    sta 18,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 17,u ; 1-byte Folded Reload
; CHECK-NEXT:    subb 16,u
; CHECK-NEXT:    stb 16,u ; 1-byte Folded Spill
; CHECK-NEXT:    sbca 18,u
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    adcb #0
; CHECK-NEXT:    stb 18,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 4,u ; 1-byte Folded Reload
; CHECK-NEXT:    cmpb #45
; CHECK-NEXT:    lbne .LBB0_7
; CHECK-NEXT:  ; %bb.6: ; %exit
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    lbra .LBB0_8
; CHECK-NEXT:  .LBB0_7: ; %exit
; CHECK-NEXT:    lbra .LBB0_8
; CHECK-NEXT:  .LBB0_8: ; %exit
; CHECK-NEXT:    cmpb #45
; CHECK-NEXT:    lbne .LBB0_10
; CHECK-NEXT:  ; %bb.9: ; %exit
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    stb 17,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    stb 15,u ; 1-byte Folded Spill
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    puls a
; CHECK-NEXT:    stb 16,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldb 18,u ; 1-byte Folded Reload
; CHECK-NEXT:    lsrb
; CHECK-NEXT:    ldb 17,u ; 1-byte Folded Reload
; CHECK-NEXT:    sbcb 15,u
; CHECK-NEXT:    sbca 16,u
; CHECK-NEXT:    lbra .LBB0_11
; CHECK-NEXT:  .LBB0_10: ; %exit
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    lbra .LBB0_11
; CHECK-NEXT:  .LBB0_11: ; %exit
; CHECK-NEXT:    ldx 5,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs1
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    puls d
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u,y
; CHECK-NEXT:    leas 19,s
; CHECK-NEXT:    rts
entry:
  %first = load i8, ptr %s, align 1
  %is_neg = icmp eq i8 %first, 45
  %offset = zext i1 %is_neg to i16
  %digit_ptr = getelementptr inbounds i8, ptr %s, i16 %offset
  %d8 = load i8, ptr %digit_ptr, align 1
  %d32 = zext i8 %d8 to i32
  %sub_off = sub nuw nsw i32 %d32, 48
  br label %loop
loop:
  %acc = phi i32 [ %sub_off, %entry ], [ %nextsum, %loop ]
  %i = phi i8 [ 0, %entry ], [ %inext, %loop ]
  %mul = mul nsw i32 %acc, 10
  %nextsum = add nsw i32 %mul, %sub_off
  %inext = add i8 %i, 1
  %done = icmp eq i8 %inext, 2
  br i1 %done, label %exit, label %loop
exit:
  %neg = sub nsw i32 0, %acc
  %cond = select i1 %is_neg, i32 %neg, i32 %acc
  store i32 %cond, ptr %out, align 1
  ret void
}
