; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mcpu=hd6309 %s -o - | FileCheck %s
;
; Phase B sentinel (post-Bug #272 landing 2026-05-15) — formerly the
; Bug #221 sentinel.
;
; Bug #221 fixed an aliasing bug in expandLoadIdx where LDQ from a
; spill slot silently clobbered $aw (since AQ's low half IS AW), and
; regalloc didn't see the conflict because $spill_q* was an
; imaginary reg distinct from physical AQ.  The pre-Phase-B fix
; substituted two LDD halves for the LDQ — correct but slow.
;
; Bug #272 Phase B (2026-05-15) re-enables LDQ from slot as the
; preferred i32 load path: the AQc class was widened to include
; SPILL_Q*, so regalloc now sees the aliasing and refuses to keep
; an unrelated value in $aw across the LDQ.  The original Bug #221
; scenario is now structurally impossible.
;
; This sentinel inverts the original CHECK-NOT: it now asserts that
; LDQ from slot IS used (the cheap, native HD6309 path), and that
; the Bug #221-incident-shape miscompile cannot recur because the
; aliasing is regalloc-visible.

@gptr = external global ptr

define i32 @bug221_load_i32_from_spill(i32 %x) #0 {
; CHECK-LABEL: bug221_load_i32_from_spill:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -41,s
; CHECK-NEXT:    pshs u,y
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr x,y
; CHECK-NEXT:    sty 21,u
; CHECK-NEXT:    ldx #gptr
; CHECK-NEXT:    ldx ,x
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    stx ,s
; CHECK-NEXT:    leax 39,u
; CHECK-NEXT:    lbsr sink_i32
; CHECK-NEXT:    ldq 39,u
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    std 19,u
; CHECK-NEXT:    tfr w,d
; CHECK-NEXT:    std 35,u
; CHECK-NEXT:    ldd 19,u
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 36,u
; CHECK-NEXT:    stb 38,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    lda 35,u
; CHECK-NEXT:    sta 37,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 16,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    lda 37,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 34,u
; CHECK-NEXT:    lda 16,u
; CHECK-NEXT:    ldb 15,u
; CHECK-NEXT:    stb 36,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 32,u
; CHECK-NEXT:    ldd 47,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 49,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 29,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    stb 28,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 26,u
; CHECK-NEXT:    ldb 30,u
; CHECK-NEXT:    stb 24,u
; CHECK-NEXT:    lda 29,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 30,u
; CHECK-NEXT:    ldb 38,u
; CHECK-NEXT:    addb 28,u
; CHECK-NEXT:    stb 38,u
; CHECK-NEXT:    ldb 34,u
; CHECK-NEXT:    adcb 26,u
; CHECK-NEXT:    stb 34,u
; CHECK-NEXT:    sta 12,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 37,u
; CHECK-NEXT:    lda 12,u
; CHECK-NEXT:    ldb 36,u
; CHECK-NEXT:    adcb 24,u
; CHECK-NEXT:    stb 36,u
; CHECK-NEXT:    ldb 32,u
; CHECK-NEXT:    adcb 30,u
; CHECK-NEXT:    stb 32,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldb 38,u
; CHECK-NEXT:    lda 37,u
; CHECK-NEXT:    std 37,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    ldb 36,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 37,u
; CHECK-NEXT:    tfr d,w
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    ldy 21,u
; CHECK-NEXT:    stq ,y
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u,y
; CHECK-NEXT:    leas 41,s
; CHECK-NEXT:    rts
entry:
  %fp = load ptr, ptr @gptr, align 1
  %a = call i32 @sink_i32(ptr %fp)         ; produces an i32 callee result
  %z = zext i16 0 to i32                   ; force a separate i32 alongside
  %r = add i32 %a, %z                      ; uses the i32 path
  %s = add i32 %r, %x
  ret i32 %s
}

declare i32 @sink_i32(ptr)

attributes #0 = { nounwind }

; Phase B (Bug #272) intentionally enables LDQ from slot as the
; cheap, native HD6309 i32 load path.  The autogenerated CHECK
; block above already verifies the `ldq <slot>,u` instruction is
; present in the lowered output (e.g. `ldq 39,u`), which is the
; new desired behaviour.  Original Bug #221's CHECK-NOT (no LDQ
; from slot) was retired with Phase B's AQc widening — regalloc
; now tracks the AQ/SPILL_Q* sharing and refuses to put an
; unrelated value in $aw across the LDQ.
