; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s

; Regression sentinel for bugs #49 / #159 / #166.
;
; This is a verbatim reduction of `test_atoi_neg` from
; `test/MC/MC6809/Execution/Inputs/codegen-stdlib-ctype.ll` — a
; PHI-carried-i16 value live across an i8 byte load + i8 compare.
; Bug #49 fix part 2 added a custom PSHS-D / ... / PULS-D wrap in
; `MC6809InstrInfo::expandCompareImm` to preserve D across the
; byte load (the load clobbers D's low byte). Bug #159 narrowed
; the wrap with a live-out gate; bug #166 then removed the wrap
; after a spike confirmed the underlying PHI clobber no longer
; reproduces (regalloc / spill placer handles it now).
;
; The autogen CHECK lines below are the durable codegen-shape
; sentinel: any future change in this function's emitted asm
; — including the reintroduction of any PSHS-D / PULS-D wrap —
; will diff and fail. Regenerate with
; `update_llc_test_checks.py` only after a deliberate codegen
; change, never as a way to silence an unexpected diff.
;
; The companion execution test
; `test/MC/MC6809/Execution/codegen-stdlib-ctype.s` runs
; `test_atoi_neg("-3")` on USim and verifies the i16 result is
; -3 — that catches the SEMANTIC regression but only while that
; test exists. This lit test is the durable shape-level guard
; that stays even if the execution harness gets refactored away.

define dso_local i16 @cmp_imm_byte_load_phi_no_wrap(ptr noundef readonly captures(none) %s) local_unnamed_addr {
; CHECK-LABEL: cmp_imm_byte_load_phi_no_wrap:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    pshs u,y
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr x,y
; CHECK-NEXT:    lda ,x
; CHECK-NEXT:    sta 4,u ; 1-byte Folded Spill
; CHECK-NEXT:    cmpa #45
; CHECK-NEXT:    lbeq .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    bra .LBB0_3
; CHECK-NEXT:  .LBB0_2: ; %entry
; CHECK-NEXT:    ldb #1
; CHECK-NEXT:  .LBB0_3: ; %entry
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    clra
; CHECK-NEXT:    lda d,y
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    addb #-48
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    cmpb #10
; CHECK-NEXT:    bhs .LBB0_8
; CHECK-NEXT:  ; %bb.4: ; %while.body.preheader
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #2
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:    ldb 4,u ; 1-byte Folded Reload
; CHECK-NEXT:    cmpb #45
; CHECK-NEXT:    beq .LBB0_6
; CHECK-NEXT:  ; %bb.5: ; %select.false
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #1
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    puls d
; CHECK-NEXT:  .LBB0_6: ; %select.end
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    leay d,y
; CHECK-NEXT:    puls d
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:  .LBB0_7: ; %while.body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sta 5,u ; 1-byte Folded Spill
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd #10
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldx <__rs1
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    ldb 5,u ; 1-byte Folded Reload
; CHECK-NEXT:    addb #-48
; CHECK-NEXT:    stb 5,u ; 1-byte Folded Spill
; CHECK-NEXT:    stx <__rs0
; CHECK-NEXT:    ldb <__rs0lo
; CHECK-NEXT:    lda <__rs0hi
; CHECK-NEXT:    addb 5,u
; CHECK-NEXT:    adca #0
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    std <__rs1
; CHECK-NEXT:    puls d
; CHECK-NEXT:    lda ,y
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    addb #-48
; CHECK-NEXT:    leay 1,y
; CHECK-NEXT:    cmpb #10
; CHECK-NEXT:    lblo .LBB0_7
; CHECK-NEXT:  .LBB0_8: ; %while.end
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    ldd <__rs0
; CHECK-NEXT:    subb <__rs1lo
; CHECK-NEXT:    sbca <__rs1hi
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:    ldb 4,u ; 1-byte Folded Reload
; CHECK-NEXT:    cmpb #45
; CHECK-NEXT:    beq .LBB0_10
; CHECK-NEXT:  ; %bb.9: ; %select.false3
; CHECK-NEXT:    ldd <__rs1
; CHECK-NEXT:    std <__rs0
; CHECK-NEXT:  .LBB0_10: ; %select.end2
; CHECK-NEXT:    ldx <__rs0
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u,y
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
entry:
  %0 = load i8, ptr %s, align 1
  %cmp.not = icmp eq i8 %0, 45
  %s.addr.0.idx = zext i1 %cmp.not to i16
  %s.addr.0 = getelementptr inbounds nuw i8, ptr %s, i16 %s.addr.0.idx
  %1 = load i8, ptr %s.addr.0, align 1
  %2 = add i8 %1, -48
  %or.cond18 = icmp ult i8 %2, 10
  br i1 %or.cond18, label %while.body, label %while.end

while.body:
  %3 = phi i8 [ %4, %while.body ], [ %1, %entry ]
  %n.020 = phi i16 [ %add, %while.body ], [ 0, %entry ]
  %s.addr.119 = phi ptr [ %incdec.ptr9, %while.body ], [ %s.addr.0, %entry ]
  %mul = mul nsw i16 %n.020, 10
  %narrow = add nsw i8 %3, -48
  %sub = zext nneg i8 %narrow to i16
  %add = add nsw i16 %mul, %sub
  %incdec.ptr9 = getelementptr inbounds nuw i8, ptr %s.addr.119, i16 1
  %4 = load i8, ptr %incdec.ptr9, align 1
  %5 = add i8 %4, -48
  %or.cond = icmp ult i8 %5, 10
  br i1 %or.cond, label %while.body, label %while.end

while.end:
  %n.0.lcssa = phi i16 [ 0, %entry ], [ %add, %while.body ]
  %sub10 = sub nsw i16 0, %n.0.lcssa
  %cond = select i1 %cmp.not, i16 %sub10, i16 %n.0.lcssa
  ret i16 %cond
}
