; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3
target triple = "mc6809"

define dso_local signext i8 @div_s_i8(i8 signext %a, i8 signext %b) {
; O0-LABEL: div_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    sex
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    sex
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __divhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: div_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -1,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    stb 2,u ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,u
; O1-NEXT:    sex
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O1-NEXT:    sex
; O1-NEXT:    leas -2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,s
; O1-NEXT:    puls d
; O1-NEXT:    tfr d,x
; O1-NEXT:    lbsr __divhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr x,d
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 1,s
; O1-NEXT:    rts
;
; O2-LABEL: div_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -1,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    stb 2,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,u
; O2-NEXT:    sex
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O2-NEXT:    sex
; O2-NEXT:    leas -2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    tfr d,x
; O2-NEXT:    lbsr __divhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr x,d
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 1,s
; O2-NEXT:    rts
;
; O3-LABEL: div_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -1,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    stb 2,u ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,u
; O3-NEXT:    sex
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O3-NEXT:    sex
; O3-NEXT:    leas -2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,s
; O3-NEXT:    puls d
; O3-NEXT:    tfr d,x
; O3-NEXT:    lbsr __divhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr x,d
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 1,s
; O3-NEXT:    rts
entry:
  %conv = sext i8 %a to i16
  %conv1 = sext i8 %b to i16
  %div = sdiv i16 %conv, %conv1
  %conv2 = trunc i16 %div to i8
  ret i8 %conv2
}

define dso_local zeroext i8 @div_u_i8(i8 zeroext %a, i8 zeroext %b) {
; O0-LABEL: div_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    clra
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    clra
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __udivhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: div_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    clra
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 4,u
; O1-NEXT:    clra
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    ldx <__rs0
; O1-NEXT:    lbsr __udivhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr x,d
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: div_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    clra
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 4,u
; O2-NEXT:    clra
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    ldx <__rs0
; O2-NEXT:    lbsr __udivhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr x,d
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: div_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    clra
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 4,u
; O3-NEXT:    clra
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    ldx <__rs0
; O3-NEXT:    lbsr __udivhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr x,d
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %0 = udiv i8 %a, %b
  ret i8 %0
}

define dso_local signext i8 @mod_s_i8(i8 signext %a, i8 signext %b) {
; O0-LABEL: mod_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    sex
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    sex
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __modhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mod_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -1,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    stb 2,u ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,u
; O1-NEXT:    sex
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O1-NEXT:    sex
; O1-NEXT:    leas -2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,s
; O1-NEXT:    puls d
; O1-NEXT:    tfr d,x
; O1-NEXT:    lbsr __modhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr x,d
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 1,s
; O1-NEXT:    rts
;
; O2-LABEL: mod_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -1,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    stb 2,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,u
; O2-NEXT:    sex
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O2-NEXT:    sex
; O2-NEXT:    leas -2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    tfr d,x
; O2-NEXT:    lbsr __modhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr x,d
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 1,s
; O2-NEXT:    rts
;
; O3-LABEL: mod_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -1,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    stb 2,u ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,u
; O3-NEXT:    sex
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O3-NEXT:    sex
; O3-NEXT:    leas -2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,s
; O3-NEXT:    puls d
; O3-NEXT:    tfr d,x
; O3-NEXT:    lbsr __modhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr x,d
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 1,s
; O3-NEXT:    rts
entry:
  %conv = sext i8 %a to i16
  %conv1 = sext i8 %b to i16
  %rem = srem i16 %conv, %conv1
  %conv2 = trunc nsw i16 %rem to i8
  ret i8 %conv2
}

define dso_local zeroext i8 @mod_u_i8(i8 zeroext %a, i8 zeroext %b) {
; O0-LABEL: mod_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    clra
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    clra
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __umodhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mod_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    clra
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 4,u
; O1-NEXT:    clra
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    ldx <__rs0
; O1-NEXT:    lbsr __umodhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr x,d
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mod_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    clra
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 4,u
; O2-NEXT:    clra
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    ldx <__rs0
; O2-NEXT:    lbsr __umodhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr x,d
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mod_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    clra
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 4,u
; O3-NEXT:    clra
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    ldx <__rs0
; O3-NEXT:    lbsr __umodhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr x,d
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %0 = urem i8 %a, %b
  ret i8 %0
}

define dso_local signext i16 @div_s_i16(i16 signext %a, i16 signext %b) {
; O0-LABEL: div_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __divhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: div_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __divhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: div_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __divhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: div_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __divhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %div = sdiv i16 %a, %b
  ret i16 %div
}

define dso_local zeroext i16 @div_u_i16(i16 zeroext %a, i16 zeroext %b) {
; O0-LABEL: div_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __udivhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: div_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __udivhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: div_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __udivhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: div_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __udivhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %div = udiv i16 %a, %b
  ret i16 %div
}

define dso_local signext i16 @mod_s_i16(i16 signext %a, i16 signext %b) {
; O0-LABEL: mod_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __modhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mod_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __modhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mod_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __modhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mod_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __modhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %rem = srem i16 %a, %b
  ret i16 %rem
}

define dso_local zeroext i16 @mod_u_i16(i16 zeroext %a, i16 zeroext %b) {
; O0-LABEL: mod_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __umodhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mod_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __umodhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mod_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __umodhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mod_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __umodhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %rem = urem i16 %a, %b
  ret i16 %rem
}

define dso_local i32 @div_s_i32(i32 %a, i32 %b) {
; O0-LABEL: div_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __divsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: div_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __divsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: div_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __divsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: div_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __divsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %div = sdiv i32 %a, %b
  ret i32 %div
}

define dso_local i32 @div_u_i32(i32 %a, i32 %b) {
; O0-LABEL: div_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __udivsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: div_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __udivsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: div_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __udivsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: div_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __udivsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %div = udiv i32 %a, %b
  ret i32 %div
}

define dso_local i32 @mod_s_i32(i32 %a, i32 %b) {
; O0-LABEL: mod_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __modsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: mod_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __modsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: mod_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __modsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: mod_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __modsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %rem = srem i32 %a, %b
  ret i32 %rem
}

define dso_local i32 @mod_u_i32(i32 %a, i32 %b) {
; O0-LABEL: mod_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __umodsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: mod_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __umodsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: mod_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __umodsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: mod_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __umodsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %rem = urem i32 %a, %b
  ret i32 %rem
}

define dso_local i64 @div_s_i64(i64 %a, i64 %b) {
; O0-LABEL: div_s_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __divdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: div_s_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 30,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __divdi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: div_s_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 30,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __divdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: div_s_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 30,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __divdi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %div = sdiv i64 %a, %b
  ret i64 %div
}

define dso_local i64 @div_u_i64(i64 %a, i64 %b) {
; O0-LABEL: div_u_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __udivdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: div_u_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 30,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __udivdi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: div_u_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 30,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __udivdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: div_u_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 30,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __udivdi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %div = udiv i64 %a, %b
  ret i64 %div
}

define dso_local i64 @mod_s_i64(i64 %a, i64 %b) {
; O0-LABEL: mod_s_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __moddi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mod_s_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 30,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __moddi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mod_s_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 30,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __moddi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mod_s_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 30,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __moddi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %rem = srem i64 %a, %b
  ret i64 %rem
}

define dso_local i64 @mod_u_i64(i64 %a, i64 %b) {
; O0-LABEL: mod_u_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __umoddi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mod_u_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 30,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __umoddi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mod_u_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 30,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __umoddi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mod_u_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 30,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __umoddi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %rem = urem i64 %a, %b
  ret i64 %rem
}

