; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3

target triple = "mc6809-unknown-unknown"

@g = external global i64

; Basic i64 add with carry propagation through 4 words.
define i64 @add64(i64 %a, i64 %b) {
; CHECK-LABEL: add64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb 29,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; O0-LABEL: add64:
; O0:       ; %bb.0:
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 25,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 24,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 6,s ; 1-byte Folded Reload
; O0-NEXT:    adca 23,s
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 22,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 21,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 20,s
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    adca 19,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca 18,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 4,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: add64:
; O1:       ; %bb.0:
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    addb 25,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 24,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 23,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 22,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 21,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 20,s
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 4,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: add64:
; O2:       ; %bb.0:
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    addb 25,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 24,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 23,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 21,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 20,s
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: add64:
; O3:       ; %bb.0:
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    addb 25,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 24,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 23,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 22,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 21,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 20,s
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 4,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
  %r = add i64 %a, %b
  ret i64 %r
}

; i64 sub with borrow propagation.
define i64 @sub64(i64 %a, i64 %b) {
; CHECK-LABEL: sub64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    subb 29,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    sbca 28,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    sbcb 27,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sbca 26,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    sbcb 25,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sbca 24,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    sbcb 23,u
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    sbca 22,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; O0-LABEL: sub64:
; O0:       ; %bb.0:
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    subb 25,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 24,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 23,s
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 21,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 20,s
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 19,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 18,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 4,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: sub64:
; O1:       ; %bb.0:
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    subb 25,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 24,s
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 23,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 22,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 21,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 20,s
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 19,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 18,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    lda 4,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: sub64:
; O2:       ; %bb.0:
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    subb 25,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 24,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 23,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 22,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 21,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 20,s
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 19,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 18,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    lda 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: sub64:
; O3:       ; %bb.0:
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    subb 25,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 24,s
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 23,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 22,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 21,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 20,s
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 19,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 18,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    lda 4,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
  %r = sub i64 %a, %b
  ret i64 %r
}

; i64 bitwise AND — decomposes to 4×i16 ANDs.
define i64 @and64(i64 %a, i64 %b) {
; CHECK-LABEL: and64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -22,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 34,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    andb 33,u
; CHECK-NEXT:    anda 32,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    andb 31,u
; CHECK-NEXT:    anda 30,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    andb 29,u
; CHECK-NEXT:    anda 28,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    andb 27,u
; CHECK-NEXT:    anda 26,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 22,s
; CHECK-NEXT:    rts
; O0-LABEL: and64:
; O0:       ; %bb.0:
; O0-NEXT:    ldd 16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    andb 9,s
; O0-NEXT:    anda 8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    andb 9,s
; O0-NEXT:    anda 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    andb 7,s
; O0-NEXT:    anda 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    andb 5,s
; O0-NEXT:    anda 4,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: and64:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 16,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    andb 9,s
; O1-NEXT:    anda 8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    andb 9,s
; O1-NEXT:    anda 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    andb 7,s
; O1-NEXT:    anda 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    andb 5,s
; O1-NEXT:    anda 4,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: and64:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    andb 9,s
; O2-NEXT:    anda 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    andb 9,s
; O2-NEXT:    anda 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    andb 7,s
; O2-NEXT:    anda 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    andb 5,s
; O2-NEXT:    anda 4,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: and64:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 16,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    andb 9,s
; O3-NEXT:    anda 8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    andb 9,s
; O3-NEXT:    anda 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    andb 7,s
; O3-NEXT:    anda 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    andb 5,s
; O3-NEXT:    anda 4,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  %r = and i64 %a, %b
  ret i64 %r
}

; i64 bitwise OR.
define i64 @or64(i64 %a, i64 %b) {
; CHECK-LABEL: or64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -22,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 34,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    orb 33,u
; CHECK-NEXT:    ora 32,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    orb 31,u
; CHECK-NEXT:    ora 30,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    orb 29,u
; CHECK-NEXT:    ora 28,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    orb 27,u
; CHECK-NEXT:    ora 26,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 22,s
; CHECK-NEXT:    rts
; O0-LABEL: or64:
; O0:       ; %bb.0:
; O0-NEXT:    ldd 16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    orb 9,s
; O0-NEXT:    ora 8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    orb 9,s
; O0-NEXT:    ora 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    orb 7,s
; O0-NEXT:    ora 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    orb 5,s
; O0-NEXT:    ora 4,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: or64:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 16,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    orb 9,s
; O1-NEXT:    ora 8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    orb 9,s
; O1-NEXT:    ora 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    orb 7,s
; O1-NEXT:    ora 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    orb 5,s
; O1-NEXT:    ora 4,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: or64:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    orb 9,s
; O2-NEXT:    ora 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    orb 9,s
; O2-NEXT:    ora 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    orb 7,s
; O2-NEXT:    ora 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    orb 5,s
; O2-NEXT:    ora 4,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: or64:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 16,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    orb 9,s
; O3-NEXT:    ora 8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    orb 9,s
; O3-NEXT:    ora 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    orb 7,s
; O3-NEXT:    ora 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    orb 5,s
; O3-NEXT:    ora 4,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  %r = or i64 %a, %b
  ret i64 %r
}

; i64 bitwise XOR.
define i64 @xor64(i64 %a, i64 %b) {
; CHECK-LABEL: xor64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -22,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 34,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    eorb 33,u
; CHECK-NEXT:    eora 32,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    eorb 31,u
; CHECK-NEXT:    eora 30,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    eorb 29,u
; CHECK-NEXT:    eora 28,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    eorb 27,u
; CHECK-NEXT:    eora 26,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 22,s
; CHECK-NEXT:    rts
; O0-LABEL: xor64:
; O0:       ; %bb.0:
; O0-NEXT:    ldd 16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    eorb 9,s
; O0-NEXT:    eora 8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    eorb 9,s
; O0-NEXT:    eora 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    eorb 7,s
; O0-NEXT:    eora 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    eorb 5,s
; O0-NEXT:    eora 4,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: xor64:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 16,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    eorb 9,s
; O1-NEXT:    eora 8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    eorb 9,s
; O1-NEXT:    eora 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    eorb 7,s
; O1-NEXT:    eora 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    eorb 5,s
; O1-NEXT:    eora 4,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: xor64:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    eorb 9,s
; O2-NEXT:    eora 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    eorb 9,s
; O2-NEXT:    eora 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    eorb 7,s
; O2-NEXT:    eora 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    eorb 5,s
; O2-NEXT:    eora 4,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: xor64:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 16,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    eorb 9,s
; O3-NEXT:    eora 8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    eorb 9,s
; O3-NEXT:    eora 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    eorb 7,s
; O3-NEXT:    eora 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    eorb 5,s
; O3-NEXT:    eora 4,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  %r = xor i64 %a, %b
  ret i64 %r
}

; Zero-extend i32 to i64: low 4 bytes = input, high 4 bytes = 0.
define i64 @zext_i32_to_i64(i32 %v) {
; CHECK-LABEL: zext_i32_to_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; O0-LABEL: zext_i32_to_i64:
; O0:       ; %bb.0:
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: zext_i32_to_i64:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 4,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd #0
; O1-NEXT:    std 2,x
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: zext_i32_to_i64:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 4,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd #0
; O2-NEXT:    std 2,x
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: zext_i32_to_i64:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 4,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd #0
; O3-NEXT:    std 2,x
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  %r = zext i32 %v to i64
  ret i64 %r
}

; Truncate i64 to i32: extract low 4 bytes.
define i32 @trunc_i64_to_i32(i64 %v) {
; CHECK-LABEL: trunc_i64_to_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; O0-LABEL: trunc_i64_to_i32:
; O0:       ; %bb.0:
; O0-NEXT:    ldd 8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: trunc_i64_to_i32:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: trunc_i64_to_i32:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: trunc_i64_to_i32:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  %r = trunc i64 %v to i32
  ret i32 %r
}

; Return a 64-bit constant. Verifies sret return mechanism.
define i64 @return_const() {
; CHECK-LABEL: return_const:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd #42
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; O0-LABEL: return_const:
; O0:       ; %bb.0:
; O0-NEXT:    ldd #42
; O0-NEXT:    std 6,x
; O0-NEXT:    ldd #0
; O0-NEXT:    std 4,x
; O0-NEXT:    std 2,x
; O0-NEXT:    std ,x
; O0-NEXT:    rts
;
; O1-LABEL: return_const:
; O1:       ; %bb.0:
; O1-NEXT:    ldd #42
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd #0
; O1-NEXT:    std 4,x
; O1-NEXT:    std 2,x
; O1-NEXT:    std ,x
; O1-NEXT:    rts
;
; O2-LABEL: return_const:
; O2:       ; %bb.0:
; O2-NEXT:    ldd #42
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd #0
; O2-NEXT:    std 4,x
; O2-NEXT:    std 2,x
; O2-NEXT:    std ,x
; O2-NEXT:    rts
;
; O3-LABEL: return_const:
; O3:       ; %bb.0:
; O3-NEXT:    ldd #42
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd #0
; O3-NEXT:    std 4,x
; O3-NEXT:    std 2,x
; O3-NEXT:    std ,x
; O3-NEXT:    rts
  ret i64 42
}

; Calling convention: i64 args all on stack (no piece in IX).
; The store to @g forces the value to be materialized.
define void @takes_i64(i64 %x) {
; CHECK-LABEL: takes_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    ldx #g
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; O0-LABEL: takes_i64:
; O0:       ; %bb.0:
; O0-NEXT:    ldd 8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldx #g
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std g
; O0-NEXT:    puls d
; O0-NEXT:    rts
;
; O1-LABEL: takes_i64:
; O1:       ; %bb.0:
; O1-NEXT:    ldd 8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldx #g
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std g
; O1-NEXT:    rts
;
; O2-LABEL: takes_i64:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldx #g
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std g
; O2-NEXT:    rts
;
; O3-LABEL: takes_i64:
; O3:       ; %bb.0:
; O3-NEXT:    ldd 8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldx #g
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std g
; O3-NEXT:    rts
  store volatile i64 %x, ptr @g
  ret void
}

; Calling convention: i16 in IX, i64 all on stack.
define void @i16_then_i64(i16 %a, i64 %b) {
; CHECK-LABEL: i16_then_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 2,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    addb 21,u
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    adcb 19,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    adca 18,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    adcb 17,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    adca 16,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    adcb 15,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    adca 14,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldx #g
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 6,x
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,x
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; O0-LABEL: i16_then_i64:
; O0:       ; %bb.0:
; O0-NEXT:    leas -8,s
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    addb 17,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 16,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 6,s ; 1-byte Folded Reload
; O0-NEXT:    adca 15,s
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 14,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 12,s
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    adca 11,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    adca 10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 4,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    ldx #g
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std g
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: i16_then_i64:
; O1:       ; %bb.0:
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 12,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 17,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    adca 16,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca #0
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca #0
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #0
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    lda 2,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 9,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 8,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 7,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    ldx #g
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std g
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: i16_then_i64:
; O2:       ; %bb.0:
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 17,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    adca 16,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca #0
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #0
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 9,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 8,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 7,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    ldx #g
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std g
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: i16_then_i64:
; O3:       ; %bb.0:
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 12,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 17,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    adca 16,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca #0
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca #0
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #0
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    lda 2,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 9,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 8,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 7,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    ldx #g
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std g
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
  %ext = zext i16 %a to i64
  %sum = add i64 %ext, %b
  store volatile i64 %sum, ptr @g
  ret void
}
