; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3
; ModuleID = 'if.c'

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local signext i8 @if_s8(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_s8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 4,s
; CHECK-NEXT:    tsta
; CHECK-NEXT:    lbgt .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %if.end
; CHECK-NEXT:    ldb #0
; CHECK-NEXT:    subb 4,s
; CHECK-NEXT:  .LBB0_2: ; %return
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; O0-LABEL: if_s8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    tsta
; O0-NEXT:    lbgt .LBB0_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    ldb #0
; O0-NEXT:    subb 2,s
; O0-NEXT:    lbra .LBB0_2
; O0-NEXT:  .LBB0_2: ; %return
; O0-NEXT:    rts
;
; O1-LABEL: if_s8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    tsta
; O1-NEXT:    ble .LBB0_2
; O1-NEXT:  ; %bb.1: ; %return
; O1-NEXT:    rts
; O1-NEXT:  .LBB0_2: ; %if.end
; O1-NEXT:    ldb #0
; O1-NEXT:    subb 2,s
; O1-NEXT:    rts
;
; O2-LABEL: if_s8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    tsta
; O2-NEXT:    ble .LBB0_2
; O2-NEXT:  ; %bb.1: ; %return
; O2-NEXT:    rts
; O2-NEXT:  .LBB0_2: ; %if.end
; O2-NEXT:    ldb #0
; O2-NEXT:    subb 2,s
; O2-NEXT:    rts
;
; O3-LABEL: if_s8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    tsta
; O3-NEXT:    ble .LBB0_2
; O3-NEXT:  ; %bb.1: ; %return
; O3-NEXT:    rts
; O3-NEXT:  .LBB0_2: ; %if.end
; O3-NEXT:    ldb #0
; O3-NEXT:    subb 2,s
; O3-NEXT:    rts
entry:
  %cmp = icmp sgt i8 %a, 0
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %sub = sub i8 0, %b
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i8 [ %sub, %if.end ], [ %b, %entry ]
  ret i8 %retval.0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local zeroext i8 @if_u8(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_u8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 4,s
; CHECK-NEXT:    tsta
; CHECK-NEXT:    lbne .LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %if.end
; CHECK-NEXT:    ldb #-1
; CHECK-NEXT:    eorb 4,s
; CHECK-NEXT:  .LBB1_2: ; %return
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; O0-LABEL: if_u8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    tsta
; O0-NEXT:    lbne .LBB1_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    ldb #-1
; O0-NEXT:    eorb 2,s
; O0-NEXT:    lbra .LBB1_2
; O0-NEXT:  .LBB1_2: ; %return
; O0-NEXT:    rts
;
; O1-LABEL: if_u8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    tsta
; O1-NEXT:    beq .LBB1_2
; O1-NEXT:  ; %bb.1: ; %return
; O1-NEXT:    rts
; O1-NEXT:  .LBB1_2: ; %if.end
; O1-NEXT:    ldb #-1
; O1-NEXT:    eorb 2,s
; O1-NEXT:    rts
;
; O2-LABEL: if_u8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    tsta
; O2-NEXT:    beq .LBB1_2
; O2-NEXT:  ; %bb.1: ; %return
; O2-NEXT:    rts
; O2-NEXT:  .LBB1_2: ; %if.end
; O2-NEXT:    ldb #-1
; O2-NEXT:    eorb 2,s
; O2-NEXT:    rts
;
; O3-LABEL: if_u8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    tsta
; O3-NEXT:    beq .LBB1_2
; O3-NEXT:  ; %bb.1: ; %return
; O3-NEXT:    rts
; O3-NEXT:  .LBB1_2: ; %if.end
; O3-NEXT:    ldb #-1
; O3-NEXT:    eorb 2,s
; O3-NEXT:    rts
entry:
  %cmp.not = icmp eq i8 %a, 0
  br i1 %cmp.not, label %if.end, label %return

if.end:                                           ; preds = %entry
  %not = xor i8 %b, -1
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i8 [ %not, %if.end ], [ %b, %entry ]
  ret i8 %retval.0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @if_s16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_s16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    stx 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbgt .LBB2_1
; CHECK-NEXT:    lbra .LBB2_2
; CHECK-NEXT:  .LBB2_1: ; %entry
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    lbra .LBB2_3
; CHECK-NEXT:  .LBB2_2: ; %if.end
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd 12,u
; CHECK-NEXT:  .LBB2_3: ; %return
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; O0-LABEL: if_s16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    ldd 2,s
; O0-NEXT:    cmpx #0
; O0-NEXT:    lbgt .LBB2_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    subb 3,s
; O0-NEXT:    sbca 2,s
; O0-NEXT:    lbra .LBB2_2
; O0-NEXT:  .LBB2_2: ; %return
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: if_s16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    ldd 2,s
; O1-NEXT:    cmpx #0
; O1-NEXT:    ble .LBB2_2
; O1-NEXT:  ; %bb.1: ; %return
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
; O1-NEXT:  .LBB2_2: ; %if.end
; O1-NEXT:    ldd #0
; O1-NEXT:    subd 2,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: if_s16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    ldd 2,s
; O2-NEXT:    cmpx #0
; O2-NEXT:    ble .LBB2_2
; O2-NEXT:  ; %bb.1: ; %return
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
; O2-NEXT:  .LBB2_2: ; %if.end
; O2-NEXT:    ldd #0
; O2-NEXT:    subd 2,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: if_s16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    ldd 2,s
; O3-NEXT:    cmpx #0
; O3-NEXT:    ble .LBB2_2
; O3-NEXT:  ; %bb.1: ; %return
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
; O3-NEXT:  .LBB2_2: ; %if.end
; O3-NEXT:    ldd #0
; O3-NEXT:    subd 2,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %cmp = icmp sgt i16 %a, 0
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %sub = sub nsw i16 0, %b
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i16 [ %sub, %if.end ], [ %b, %entry ]
  ret i16 %retval.0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @if_u16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_u16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    stx 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbne .LBB3_1
; CHECK-NEXT:    lbra .LBB3_2
; CHECK-NEXT:  .LBB3_1: ; %entry
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    lbra .LBB3_3
; CHECK-NEXT:  .LBB3_2: ; %if.end
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    ldd #-1
; CHECK-NEXT:    eorb 13,u
; CHECK-NEXT:    eora 12,u
; CHECK-NEXT:  .LBB3_3: ; %return
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; O0-LABEL: if_u16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    ldd 2,s
; O0-NEXT:    cmpx #0
; O0-NEXT:    lbne .LBB3_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    ldd #-1
; O0-NEXT:    eorb 3,s
; O0-NEXT:    eora 2,s
; O0-NEXT:    lbra .LBB3_2
; O0-NEXT:  .LBB3_2: ; %return
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: if_u16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    ldd 2,s
; O1-NEXT:    cmpx #0
; O1-NEXT:    beq .LBB3_2
; O1-NEXT:  ; %bb.1: ; %return
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
; O1-NEXT:  .LBB3_2: ; %if.end
; O1-NEXT:    ldd #-1
; O1-NEXT:    eorb 3,s
; O1-NEXT:    eora 2,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: if_u16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    ldd 2,s
; O2-NEXT:    cmpx #0
; O2-NEXT:    beq .LBB3_2
; O2-NEXT:  ; %bb.1: ; %return
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
; O2-NEXT:  .LBB3_2: ; %if.end
; O2-NEXT:    ldd #-1
; O2-NEXT:    eorb 3,s
; O2-NEXT:    eora 2,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: if_u16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    ldd 2,s
; O3-NEXT:    cmpx #0
; O3-NEXT:    beq .LBB3_2
; O3-NEXT:  ; %bb.1: ; %return
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
; O3-NEXT:  .LBB3_2: ; %if.end
; O3-NEXT:    ldd #-1
; O3-NEXT:    eorb 3,s
; O3-NEXT:    eora 2,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %cmp.not = icmp eq i16 %a, 0
  br i1 %cmp.not, label %if.end, label %return

if.end:                                           ; preds = %entry
  %not = xor i16 %b, -1
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i16 [ %not, %if.end ], [ %b, %entry ]
  ret i16 %retval.0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @if_s32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_s32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbeq .LBB4_1
; CHECK-NEXT:    lbra .LBB4_2
; CHECK-NEXT:  .LBB4_1: ; %entry
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbhi .LBB4_4
; CHECK-NEXT:    lbra .LBB4_3
; CHECK-NEXT:  .LBB4_2: ; %entry
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbgt .LBB4_4
; CHECK-NEXT:  .LBB4_3: ; %if.end
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    subb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    sbcb 3,u
; CHECK-NEXT:    sbca 2,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:  .LBB4_4: ; %return
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; O0-LABEL: if_s32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -9,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 7,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 17,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 15,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 6,s
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 9,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __cmpsi2
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 19,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 21,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 8,s
; O0-NEXT:    cmpb #2
; O0-NEXT:    lbeq .LBB4_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,u ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 5,u ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,u ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,u ; 1-byte Folded Reload
; O0-NEXT:    subb 22,u
; O0-NEXT:    stb 6,u ; 1-byte Folded Spill
; O0-NEXT:    tfr a,b
; O0-NEXT:    sbcb 21,u
; O0-NEXT:    lda 5,u ; 1-byte Folded Reload
; O0-NEXT:    sbca 20,u
; O0-NEXT:    sta 5,u ; 1-byte Folded Spill
; O0-NEXT:    lda 4,u ; 1-byte Folded Reload
; O0-NEXT:    sbca 19,u
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 5,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    lbra .LBB4_2
; O0-NEXT:  .LBB4_2: ; %return
; O0-NEXT:    ldx 7,u ; 2-byte Folded Reload
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 9,s
; O0-NEXT:    rts
;
; O1-LABEL: if_s32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -8,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 6,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 16,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #0
; O1-NEXT:    std 6,s
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 8,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __cmpsi2
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 2,y
; O1-NEXT:    leas 8,s
; O1-NEXT:    cmpb #2
; O1-NEXT:    lbeq .LBB4_2
; O1-NEXT:  ; %bb.1: ; %if.end
; O1-NEXT:    lda #0
; O1-NEXT:    tfr a,b
; O1-NEXT:    subb 21,u
; O1-NEXT:    stb 5,u ; 1-byte Folded Spill
; O1-NEXT:    tfr a,b
; O1-NEXT:    sbcb 20,u
; O1-NEXT:    stb 4,u ; 1-byte Folded Spill
; O1-NEXT:    tfr a,b
; O1-NEXT:    sbcb 19,u
; O1-NEXT:    sbca 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 5,u
; O1-NEXT:    lda 4,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:  .LBB4_2: ; %return
; O1-NEXT:    ldx 6,u ; 2-byte Folded Reload
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 8,s
; O1-NEXT:    rts
;
; O2-LABEL: if_s32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 6,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 16,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 6,s
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 8,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __cmpsi2
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 8,s
; O2-NEXT:    cmpb #2
; O2-NEXT:    lbeq .LBB4_2
; O2-NEXT:  ; %bb.1: ; %if.end
; O2-NEXT:    lda #0
; O2-NEXT:    tfr a,b
; O2-NEXT:    subb 21,u
; O2-NEXT:    stb 5,u ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 20,u
; O2-NEXT:    stb 4,u ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 19,u
; O2-NEXT:    sbca 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,u
; O2-NEXT:    lda 4,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:  .LBB4_2: ; %return
; O2-NEXT:    ldx 6,u ; 2-byte Folded Reload
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
;
; O3-LABEL: if_s32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -8,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 6,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 16,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #0
; O3-NEXT:    std 6,s
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 8,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __cmpsi2
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 2,y
; O3-NEXT:    leas 8,s
; O3-NEXT:    cmpb #2
; O3-NEXT:    lbeq .LBB4_2
; O3-NEXT:  ; %bb.1: ; %if.end
; O3-NEXT:    lda #0
; O3-NEXT:    tfr a,b
; O3-NEXT:    subb 21,u
; O3-NEXT:    stb 5,u ; 1-byte Folded Spill
; O3-NEXT:    tfr a,b
; O3-NEXT:    sbcb 20,u
; O3-NEXT:    stb 4,u ; 1-byte Folded Spill
; O3-NEXT:    tfr a,b
; O3-NEXT:    sbcb 19,u
; O3-NEXT:    sbca 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 5,u
; O3-NEXT:    lda 4,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:  .LBB4_2: ; %return
; O3-NEXT:    ldx 6,u ; 2-byte Folded Reload
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 8,s
; O3-NEXT:    rts
entry:
  %cmp = icmp sgt i32 %a, 0
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %sub = sub nsw i32 0, %b
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i32 [ %sub, %if.end ], [ %b, %entry ]
  ret i32 %retval.0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @if_u32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: if_u32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    orb 23,u
; CHECK-NEXT:    ora 22,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbne .LBB5_1
; CHECK-NEXT:    lbra .LBB5_2
; CHECK-NEXT:  .LBB5_1: ; %entry
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    lbra .LBB5_3
; CHECK-NEXT:  .LBB5_2: ; %if.end
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    ldd #-1
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    eorb 27,u
; CHECK-NEXT:    eora 26,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    eorb 25,u
; CHECK-NEXT:    eora 24,u
; CHECK-NEXT:  .LBB5_3: ; %return
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; O0-LABEL: if_u32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 18,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 6,s
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ucmpsi2
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 8,s
; O0-NEXT:    cmpb #1
; O0-NEXT:    lbne .LBB5_2
; O0-NEXT:  ; %bb.1: ; %if.end
; O0-NEXT:    leas -8,s
; O0-NEXT:    leay 10,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #-1
; O0-NEXT:    std 6,s
; O0-NEXT:    std 4,s
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __xorsi3
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    lbra .LBB5_2
; O0-NEXT:  .LBB5_2: ; %return
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: if_u32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #0
; O1-NEXT:    std 6,s
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __ucmpsi2
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 2,y
; O1-NEXT:    leas 8,s
; O1-NEXT:    cmpb #1
; O1-NEXT:    bne .LBB5_2
; O1-NEXT:  ; %bb.1: ; %if.end
; O1-NEXT:    leas -8,s
; O1-NEXT:    leay 10,u
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #-1
; O1-NEXT:    std 6,s
; O1-NEXT:    std 4,s
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __xorsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 10,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    leas 8,s
; O1-NEXT:  .LBB5_2: ; %return
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: if_u32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 6,s
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ucmpsi2
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 8,s
; O2-NEXT:    cmpb #1
; O2-NEXT:    bne .LBB5_2
; O2-NEXT:  ; %bb.1: ; %if.end
; O2-NEXT:    leas -8,s
; O2-NEXT:    leay 10,u
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #-1
; O2-NEXT:    std 6,s
; O2-NEXT:    std 4,s
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __xorsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    leas 8,s
; O2-NEXT:  .LBB5_2: ; %return
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: if_u32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #0
; O3-NEXT:    std 6,s
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __ucmpsi2
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 2,y
; O3-NEXT:    leas 8,s
; O3-NEXT:    cmpb #1
; O3-NEXT:    bne .LBB5_2
; O3-NEXT:  ; %bb.1: ; %if.end
; O3-NEXT:    leas -8,s
; O3-NEXT:    leay 10,u
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #-1
; O3-NEXT:    std 6,s
; O3-NEXT:    std 4,s
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __xorsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 10,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    leas 8,s
; O3-NEXT:  .LBB5_2: ; %return
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %cmp.not = icmp eq i32 %a, 0
  br i1 %cmp.not, label %if.end, label %return

if.end:                                           ; preds = %entry
  %not = xor i32 %b, -1
  br label %return

return:                                           ; preds = %entry, %if.end
  %retval.0 = phi i32 [ %not, %if.end ], [ %b, %entry ]
  ret i32 %retval.0
}

