; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mc6809 -mcpu=mc6809 -O2 -global-isel < %s | FileCheck %s --check-prefix=MC6809
; RUN: llc -mtriple=mc6809 -mcpu=hd6309 -O2 -global-isel < %s | FileCheck %s --check-prefix=HD6309
;
; P3b Phase B: `if (**pp == x)` folds the double deref into a fused `cmp [n,r]; b<cc>`.
; HD6309 i16 compares can land in W -> also exercises the CMPW indirect sibling.

target datalayout = "E-p:16:8-p1:8:8-S8-m:e-i1:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:0-n8:16"
target triple = "mc6809-unknown-unknown"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none)
define dso_local range(i16 7, 10) i16 @e_ind(ptr noundef readonly captures(none) %pp, i8 noundef zeroext %x) local_unnamed_addr #0 {
; MC6809-LABEL: e_ind:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    pshs d
; MC6809-NEXT:    ldd #7
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:    puls d
; MC6809-NEXT:    cmpb [,x]
; MC6809-NEXT:    lbeq .LBB0_2
; MC6809-NEXT:  ; %bb.1: ; %select.false
; MC6809-NEXT:    ldd #9
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:  .LBB0_2: ; %select.end
; MC6809-NEXT:    ldx <__rs0
; MC6809-NEXT:    rts
;
; HD6309-LABEL: e_ind:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldw #7
; HD6309-NEXT:    cmpb [,x]
; HD6309-NEXT:    lbeq .LBB0_2
; HD6309-NEXT:  ; %bb.1: ; %select.false
; HD6309-NEXT:    ldw #9
; HD6309-NEXT:  .LBB0_2: ; %select.end
; HD6309-NEXT:    tfr w,x
; HD6309-NEXT:    rts
entry:
  %0 = load ptr, ptr %pp, align 1, !tbaa !8
  %1 = load i8, ptr %0, align 1, !tbaa !11
  %cmp = icmp eq i8 %1, %x
  %. = select i1 %cmp, i16 7, i16 9
  ret i16 %.
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none)
define dso_local range(i16 7, 10) i16 @l_ind(ptr noundef readonly captures(none) %pp, i8 noundef zeroext %x) local_unnamed_addr #0 {
; MC6809-LABEL: l_ind:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    pshs d
; MC6809-NEXT:    ldd #7
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:    puls d
; MC6809-NEXT:    cmpb [,x]
; MC6809-NEXT:    lbhi .LBB1_2
; MC6809-NEXT:  ; %bb.1: ; %select.false
; MC6809-NEXT:    ldd #9
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:  .LBB1_2: ; %select.end
; MC6809-NEXT:    ldx <__rs0
; MC6809-NEXT:    rts
;
; HD6309-LABEL: l_ind:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldw #7
; HD6309-NEXT:    cmpb [,x]
; HD6309-NEXT:    lbhi .LBB1_2
; HD6309-NEXT:  ; %bb.1: ; %select.false
; HD6309-NEXT:    ldw #9
; HD6309-NEXT:  .LBB1_2: ; %select.end
; HD6309-NEXT:    tfr w,x
; HD6309-NEXT:    rts
entry:
  %0 = load ptr, ptr %pp, align 1, !tbaa !8
  %1 = load i8, ptr %0, align 1, !tbaa !11
  %cmp = icmp ult i8 %1, %x
  %. = select i1 %cmp, i16 7, i16 9
  ret i16 %.
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none)
define dso_local range(i16 7, 10) i16 @sw_ind(ptr noundef readonly captures(none) %pp, i8 noundef zeroext %x) local_unnamed_addr #0 {
; MC6809-LABEL: sw_ind:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    pshs d
; MC6809-NEXT:    ldd #7
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:    puls d
; MC6809-NEXT:    cmpb [,x]
; MC6809-NEXT:    lbeq .LBB2_2
; MC6809-NEXT:  ; %bb.1: ; %select.false
; MC6809-NEXT:    ldd #9
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:  .LBB2_2: ; %select.end
; MC6809-NEXT:    ldx <__rs0
; MC6809-NEXT:    rts
;
; HD6309-LABEL: sw_ind:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldw #7
; HD6309-NEXT:    cmpb [,x]
; HD6309-NEXT:    lbeq .LBB2_2
; HD6309-NEXT:  ; %bb.1: ; %select.false
; HD6309-NEXT:    ldw #9
; HD6309-NEXT:  .LBB2_2: ; %select.end
; HD6309-NEXT:    tfr w,x
; HD6309-NEXT:    rts
entry:
  %0 = load ptr, ptr %pp, align 1, !tbaa !8
  %1 = load i8, ptr %0, align 1, !tbaa !11
  %cmp = icmp eq i8 %x, %1
  %. = select i1 %cmp, i16 7, i16 9
  ret i16 %.
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none)
define dso_local range(i16 7, 10) i16 @e16(ptr noundef readonly captures(none) %pp, i16 noundef zeroext %x) local_unnamed_addr #0 {
; MC6809-LABEL: e16:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    ldd 2,s
; MC6809-NEXT:    std <__rs0
; MC6809-NEXT:    ldd #7
; MC6809-NEXT:    pshs d
; MC6809-NEXT:    ldd <__rs0
; MC6809-NEXT:    cmpd [,x]
; MC6809-NEXT:    puls d
; MC6809-NEXT:    lbeq .LBB3_2
; MC6809-NEXT:  ; %bb.1: ; %select.false
; MC6809-NEXT:    ldd #9
; MC6809-NEXT:  .LBB3_2: ; %select.end
; MC6809-NEXT:    tfr d,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: e16:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldw 2,s
; HD6309-NEXT:    ldd #7
; HD6309-NEXT:    cmpw [,x]
; HD6309-NEXT:    lbeq .LBB3_2
; HD6309-NEXT:  ; %bb.1: ; %select.false
; HD6309-NEXT:    ldd #9
; HD6309-NEXT:  .LBB3_2: ; %select.end
; HD6309-NEXT:    tfr d,x
; HD6309-NEXT:    rts
entry:
  %0 = load ptr, ptr %pp, align 1, !tbaa !12
  %1 = load i16, ptr %0, align 1, !tbaa !14
  %cmp = icmp eq i16 %1, %x
  %. = select i1 %cmp, i16 7, i16 9
  ret i16 %.
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}
!llvm.errno.tbaa = !{!4}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 7, !"PIE Level", i32 2}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 23.0.0git (git@github.com:markrvmurray/llvm-mc6809.git 7f0a1f156fe97c95a46f45bd54348be2ef33a475)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !9, i64 0}
!9 = !{!"p1 omnipotent char", !10, i64 0}
!10 = !{!"any pointer", !6, i64 0}
!11 = !{!6, !6, i64 0}
!12 = !{!13, !13, i64 0}
!13 = !{!"p1 short", !10, i64 0}
!14 = !{!15, !15, i64 0}
!15 = !{!"short", !6, i64 0}
