; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O2

; Bug #176 regression sentry: LEA-pointer-spill fold (Class 7 of
; MC6809FinalLowering). The pattern below would emit
;
;     leay  off,u
;     sty   slot,u
;     ldy   slot,u
;     std   ,y
;
; without Class 7. With Class 7, the immediately-adjacent
; ldy+std,y pair collapses to a direct std off,u (the LDY is
; deleted because it's the PendingLDY at the rewrite site, and
; the STD's base/offset get rewritten to use U directly with the
; combined offset). The leay+sty pair stays for now (a dedicated
; DSE pass would clean those up; tracked separately).
;
; Two RUN lines: -O0 (where standard regalloc would normally
; spill the pointer and the standard mid-end can't help) and -O2
; (where we expect rematerialisation or other regalloc smarts to
; mostly avoid the pattern, but Class 7 still backstops anything
; that slips through).

target triple = "mc6809-unknown-unknown"

declare void @sink(ptr)

; Function whose stack frame's pointer arithmetic produces the
; canonical LEAY+STY+LDY+STD,Y chain at -O0. The address of a
; local is taken (alloca + escape via @sink) to force frame use,
; then a series of stores through that pointer creates the spill.
define void @fold_through_y(i16 %v, i16 %w) {
; O0-LABEL: fold_through_y:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    tfr x,d
; O0-NEXT:    leay 4,u
; O0-NEXT:    std 4,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,y
; O0-NEXT:    puls d
; O0-NEXT:    std 4,y
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr sink
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O2-LABEL: fold_through_y:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -8,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 14,u
; O2-NEXT:    leay 4,u
; O2-NEXT:    stx 4,u
; O2-NEXT:    std 2,y
; O2-NEXT:    stx 4,y
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr sink
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 8,s
; O2-NEXT:    rts
entry:
  %a = alloca [4 x i16], align 1
  %p0 = getelementptr [4 x i16], ptr %a, i32 0, i32 0
  store i16 %v, ptr %p0, align 1
  %p1 = getelementptr [4 x i16], ptr %a, i32 0, i32 1
  store i16 %w, ptr %p1, align 1
  %p2 = getelementptr [4 x i16], ptr %a, i32 0, i32 2
  store i16 %v, ptr %p2, align 1
  call void @sink(ptr %a)
  ret void
}
