; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809               %s -o - | FileCheck %s --check-prefixes=MC6809-O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809               %s -o - | FileCheck %s --check-prefixes=MC6809-O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809               %s -o - | FileCheck %s --check-prefixes=MC6809-O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809               %s -o - | FileCheck %s --check-prefixes=MC6809-O3
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 --mcpu=hd6309 %s -o - | FileCheck %s --check-prefixes=HD6309
; ModuleID = 'loop.c'
source_filename = "loop.c"
target datalayout = "e-p:16:8-S8-m:e-i1:8:8-i8:8:8-i16:8:8-i32:8:8-i64:8:8-f16:8:8-f32:8:8-f64:8:8-f128:8:8-a:0:8-n8:16"
target triple = "mc6809-unknown-unknown"

; Function Attrs: argmemonly nofree norecurse nosync nounwind readonly
define dso_local i16 @loop(ptr nocapture noundef readonly %pa, i8 noundef signext %n) local_unnamed_addr #0 {
; CHECK-LABEL: loop:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -14,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    tstb
; CHECK-NEXT:    lble .LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %for.body.preheader
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    clra
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:  .LBB0_2: ; %for.body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldd ,x
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldb 13,u
; CHECK-NEXT:    addb 11,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    lda 12,u
; CHECK-NEXT:    adca 10,u
; CHECK-NEXT:    sta 12,u
; CHECK-NEXT:    leax 2,x
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb #-1
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    adca #-1
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    cmpd #0
; CHECK-NEXT:    lbne .LBB0_2
; CHECK-NEXT:  .LBB0_3: ; %for.end
; CHECK-NEXT:    ldx 12,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 14,s
; CHECK-NEXT:    rts
;
; MC6809-O0-LABEL: loop:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    leas -3,s
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    ldd #0
; MC6809-O0-NEXT:    std <__rs0
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    tstb
; MC6809-O0-NEXT:    lble .LBB0_3
; MC6809-O0-NEXT:  ; %bb.1: ; %for.body.preheader
; MC6809-O0-NEXT:    clra
; MC6809-O0-NEXT:    std <__rs1
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    ldd #0
; MC6809-O0-NEXT:    std <__rs0
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    lbra .LBB0_2
; MC6809-O0-NEXT:  .LBB0_2: ; %for.body
; MC6809-O0-NEXT:    ; =>This Inner Loop Header: Depth=1
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    ldd ,x
; MC6809-O0-NEXT:    std <__rs2
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    ldb <__rs2lo
; MC6809-O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; MC6809-O0-NEXT:    lda <__rs2hi
; MC6809-O0-NEXT:    ldb <__rs0lo
; MC6809-O0-NEXT:    stb ,s ; 1-byte Folded Spill
; MC6809-O0-NEXT:    pshs a
; MC6809-O0-NEXT:    lda <__rs0hi
; MC6809-O0-NEXT:    tfr a,b
; MC6809-O0-NEXT:    puls a
; MC6809-O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; MC6809-O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; MC6809-O0-NEXT:    addb ,s
; MC6809-O0-NEXT:    adca 2,s
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    std <__rs0
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    leax 2,x
; MC6809-O0-NEXT:    ldb <__rs1lo
; MC6809-O0-NEXT:    lda <__rs1hi
; MC6809-O0-NEXT:    addb #255
; MC6809-O0-NEXT:    adca #255
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    std <__rs1
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    pshs d
; MC6809-O0-NEXT:    ldd <__rs1
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    puls d
; MC6809-O0-NEXT:    lbne .LBB0_2
; MC6809-O0-NEXT:  .LBB0_3: ; %for.end
; MC6809-O0-NEXT:    ldx <__rs0
; MC6809-O0-NEXT:    leas 3,s
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: loop:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    pshs d
; MC6809-O1-NEXT:    ldd #0
; MC6809-O1-NEXT:    std <__rs0
; MC6809-O1-NEXT:    puls d
; MC6809-O1-NEXT:    tstb
; MC6809-O1-NEXT:    ble .LBB0_3
; MC6809-O1-NEXT:  ; %bb.1: ; %for.body.preheader
; MC6809-O1-NEXT:    clra
; MC6809-O1-NEXT:    pshs d
; MC6809-O1-NEXT:    ldd #0
; MC6809-O1-NEXT:    std <__rs0
; MC6809-O1-NEXT:    puls d
; MC6809-O1-NEXT:  .LBB0_2: ; %for.body
; MC6809-O1-NEXT:    ; =>This Inner Loop Header: Depth=1
; MC6809-O1-NEXT:    pshs d
; MC6809-O1-NEXT:    ldd <__rs0
; MC6809-O1-NEXT:    addd ,x
; MC6809-O1-NEXT:    std <__rs0
; MC6809-O1-NEXT:    puls d
; MC6809-O1-NEXT:    leax 2,x
; MC6809-O1-NEXT:    addd #-1
; MC6809-O1-NEXT:    bne .LBB0_2
; MC6809-O1-NEXT:  .LBB0_3: ; %for.end
; MC6809-O1-NEXT:    ldx <__rs0
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: loop:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    pshs d
; MC6809-O2-NEXT:    ldd #0
; MC6809-O2-NEXT:    std <__rs0
; MC6809-O2-NEXT:    puls d
; MC6809-O2-NEXT:    tstb
; MC6809-O2-NEXT:    ble .LBB0_3
; MC6809-O2-NEXT:  ; %bb.1: ; %for.body.preheader
; MC6809-O2-NEXT:    clra
; MC6809-O2-NEXT:    pshs d
; MC6809-O2-NEXT:    ldd #0
; MC6809-O2-NEXT:    std <__rs0
; MC6809-O2-NEXT:    puls d
; MC6809-O2-NEXT:  .LBB0_2: ; %for.body
; MC6809-O2-NEXT:    ; =>This Inner Loop Header: Depth=1
; MC6809-O2-NEXT:    pshs d
; MC6809-O2-NEXT:    ldd <__rs0
; MC6809-O2-NEXT:    addd ,x
; MC6809-O2-NEXT:    std <__rs0
; MC6809-O2-NEXT:    puls d
; MC6809-O2-NEXT:    leax 2,x
; MC6809-O2-NEXT:    addd #-1
; MC6809-O2-NEXT:    bne .LBB0_2
; MC6809-O2-NEXT:  .LBB0_3: ; %for.end
; MC6809-O2-NEXT:    ldx <__rs0
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: loop:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    pshs d
; MC6809-O3-NEXT:    ldd #0
; MC6809-O3-NEXT:    std <__rs0
; MC6809-O3-NEXT:    puls d
; MC6809-O3-NEXT:    tstb
; MC6809-O3-NEXT:    ble .LBB0_3
; MC6809-O3-NEXT:  ; %bb.1: ; %for.body.preheader
; MC6809-O3-NEXT:    clra
; MC6809-O3-NEXT:    pshs d
; MC6809-O3-NEXT:    ldd #0
; MC6809-O3-NEXT:    std <__rs0
; MC6809-O3-NEXT:    puls d
; MC6809-O3-NEXT:  .LBB0_2: ; %for.body
; MC6809-O3-NEXT:    ; =>This Inner Loop Header: Depth=1
; MC6809-O3-NEXT:    pshs d
; MC6809-O3-NEXT:    ldd <__rs0
; MC6809-O3-NEXT:    addd ,x
; MC6809-O3-NEXT:    std <__rs0
; MC6809-O3-NEXT:    puls d
; MC6809-O3-NEXT:    leax 2,x
; MC6809-O3-NEXT:    addd #-1
; MC6809-O3-NEXT:    bne .LBB0_2
; MC6809-O3-NEXT:  .LBB0_3: ; %for.end
; MC6809-O3-NEXT:    ldx <__rs0
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: loop:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldw #0
; HD6309-NEXT:    tstb
; HD6309-NEXT:    ble .LBB0_3
; HD6309-NEXT:  ; %bb.1: ; %for.body.preheader
; HD6309-NEXT:    clra
; HD6309-NEXT:    ldw #0
; HD6309-NEXT:  .LBB0_2: ; %for.body
; HD6309-NEXT:    ; =>This Inner Loop Header: Depth=1
; HD6309-NEXT:    addw ,x
; HD6309-NEXT:    leax 2,x
; HD6309-NEXT:    addd #-1
; HD6309-NEXT:    bne .LBB0_2
; HD6309-NEXT:  .LBB0_3: ; %for.end
; HD6309-NEXT:    tfr w,x
; HD6309-NEXT:    rts
entry:
  %cmp6 = icmp sgt i8 %n, 0
  br i1 %cmp6, label %for.body.preheader, label %for.end

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext i8 %n to i16
  br label %for.body

for.body:                                         ; preds = %for.body.preheader, %for.body
  %lsr.iv14 = phi i16 [ %wide.trip.count, %for.body.preheader ], [ %lsr.iv.next, %for.body ]
  %lsr.iv = phi ptr [ %pa, %for.body.preheader ], [ %uglygep13, %for.body ]
  %s.07 = phi i16 [ 0, %for.body.preheader ], [ %add, %for.body ]
  %0 = load i16, ptr %lsr.iv, align 1, !tbaa !3
  %add = add nsw i16 %0, %s.07
  %uglygep13 = getelementptr i8, ptr %lsr.iv, i16 2
  %lsr.iv.next = add nsw i16 %lsr.iv14, -1
  %exitcond.not = icmp eq i16 %lsr.iv.next, 0
  br i1 %exitcond.not, label %for.end, label %for.body, !llvm.loop !7

for.end:                                          ; preds = %for.body, %entry
  %s.0.lcssa = phi i16 [ 0, %entry ], [ %add, %for.body ]
  ret i16 %s.0.lcssa
}

attributes #0 = { argmemonly nofree norecurse nosync nounwind readonly "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"frame-pointer", i32 2}
!2 = !{!"clang version 15.0.0 (https://github.com/markrvmurray/llvm-mc6809.git 3fe96cc89c1380c464065b93a4a93c7ed9052f94)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
!7 = distinct !{!7, !8}
!8 = !{!"llvm.loop.mustprogress"}
