; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809               %s -o - | FileCheck %s

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local signext i8 @mul_s_i8(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldb 11,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i8 %b, %a
  ret i8 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i8_i16(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldb 15,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    sex
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    sex
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 11,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    sta 10,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 11,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 11,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 11,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    sex
; CHECK-HD6309-NEXT:    tfr d,w
; CHECK-HD6309-NEXT:    ldb 4,u
; CHECK-HD6309-NEXT:    sex
; CHECK-HD6309-NEXT:    pshsw
; CHECK-HD6309-NEXT:    muld ,s++
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %conv = sext i8 %a to i16
  %conv1 = sext i8 %b to i16
  %mul = mul nsw i16 %conv1, %conv
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local signext i8 @mul_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda #12
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -2,s
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    sta -1,u ; 1-byte Folded Spill
; CHECK-HD6309-NEXT:    lda #12
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    lda -1,u ; 1-byte Folded Reload
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    leas 2,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i8 %a, 12
  %mul2 = mul i8 %mul, %b
  ret i8 %mul2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local zeroext i8 @mul_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldb 11,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i8 %b, %a
  ret i8 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i8_i16(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldb 11,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    clra
; CHECK-HD6309-NEXT:    clra
; CHECK-HD6309-NEXT:    pshsw
; CHECK-HD6309-NEXT:    muld ,s++
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %conv = zext i8 %a to i16
  %conv1 = zext i8 %b to i16
  %mul = mul nuw i16 %conv1, %conv
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local zeroext i8 @mul_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda #13
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -2,s
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    sta -1,u ; 1-byte Folded Spill
; CHECK-HD6309-NEXT:    lda #13
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    lda -1,u ; 1-byte Folded Reload
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    leas 2,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i8 %a, 13
  %mul2 = mul i8 %mul, %b
  ret i8 %mul2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 9,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    stb 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul nsw i16 %b, %a
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i16_consts(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -12,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda #-14
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    aslb
; CHECK-NEXT:    std 10,u ; 2-byte Folded Spill
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    stb 2,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 12,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld #754
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul nsw i16 %a, 754
  %mul1 = mul nsw i16 %mul, %b
  ret i16 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 9,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    stb 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i16 %b, %a
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i16_consts(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -12,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    tfr a,b
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda #87
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    aslb
; CHECK-NEXT:    std 10,u ; 2-byte Folded Spill
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    stb 2,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 12,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld #1111
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i16 %a, 1111
  %mul1 = mul i16 %mul, %b
  ret i16 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_s_i32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -19,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 23,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 27,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 25,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 7,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 4,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 15,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 17,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 10,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 18,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 12,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 13,u ; 2-byte Folded Spill
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 12,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 15,u ; 2-byte Folded Reload
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 13,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 17,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 17,u
; CHECK-NEXT:    std 23,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 19,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul nsw i32 %b, %a
  ret i32 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_s_i32_consts(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -15,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 19,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 5,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    lda #35
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    lda #11
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 13,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    addb 19,u
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldb 13,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    addb 19,u
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 23,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    ldd 21,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 13,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 11,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldd 11,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    ldb 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 14,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldd 21,u
; CHECK-NEXT:    sta 13,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 13,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 13,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 13,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    stb 13,u
; CHECK-NEXT:    std 19,u
; CHECK-NEXT:    ldd 13,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 15,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq #68387
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul nsw i32 %a, 68387
  %mul1 = mul nsw i32 %mul, %b
  ret i32 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_u_i32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -19,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 23,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 27,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 25,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 7,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 4,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 15,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 17,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 10,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 18,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 8,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 12,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 13,u ; 2-byte Folded Spill
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 10,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 12,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    sta 17,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 17,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 15,u ; 2-byte Folded Reload
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 17,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 13,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 18,u
; CHECK-NEXT:    ldd 17,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 18,u
; CHECK-NEXT:    stb 17,u
; CHECK-NEXT:    std 23,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 19,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i32 %b, %a
  ret i32 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_u_i32_consts(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -17,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 21,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 16,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda #46
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 15,u ; 2-byte Folded Spill
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    lda #-28
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sta 7,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 11,u ; 2-byte Folded Spill
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    lda #6
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 13,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldb 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 3,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    lda 4,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 11,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 2,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 13,u ; 2-byte Folded Reload
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 25,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    ldd 15,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    ldd 0,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    ldd 23,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 15,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    sta 8,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    std 13,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    std 0,u
; CHECK-NEXT:    stb 11,u ; 1-byte Folded Spill
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    sta 2,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    lda 6,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldd 13,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    ldb 11,u ; 1-byte Folded Reload
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs s,s
; CHECK-NEXT:    addb 1,s
; CHECK-NEXT:    adda ,s
; CHECK-NEXT:    leas s,2
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    andb #1
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 16,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    sta 6,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    ldd 23,u
; CHECK-NEXT:    sta 15,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 15,u
; CHECK-NEXT:    ldb 3,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 15,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    lda 8,u
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldb 16,u
; CHECK-NEXT:    pshs b
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    addb ,s+
; CHECK-NEXT:    stb 7,u
; CHECK-NEXT:    ldd 15,u ; 2-byte Folded Reload
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    ldb 7,u
; CHECK-NEXT:    stb 15,u
; CHECK-NEXT:    std 21,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 17,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq #451630
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
entry:
  %mul = mul i32 %a, 451630
  %mul1 = mul i32 %mul, %b
  ret i32 %mul1
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"frame-pointer", i32 2}
!2 = !{!"clang version 16.0.0 (https://github.com/llvm-mos/llvm-mos.git 3a36081cf8e78f58d86001abde8d1da1de50027b)"}

