; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local signext i8 @mul_s_i8(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldb 10,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    rts
entry:
  %mul = mul i8 %b, %a
  ret i8 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i8_i16(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    sex
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    sex
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldx 8,u
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    sex
; CHECK-HD6309-NEXT:    tfr d,w
; CHECK-HD6309-NEXT:    ldb 4,u
; CHECK-HD6309-NEXT:    sex
; CHECK-HD6309-NEXT:    pshsw
; CHECK-HD6309-NEXT:    muld ,s++
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i8_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    sex
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    sex
; O0-NEXT:    leas -2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    tfr d,x
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i8_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -1,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    stb 2,u ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,u
; O1-NEXT:    sex
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O1-NEXT:    sex
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    ldx <__rs0
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 1,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i8_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -1,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    stb 2,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,u
; O2-NEXT:    sex
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O2-NEXT:    sex
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    ldx <__rs0
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 1,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i8_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -1,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    stb 2,u ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,u
; O3-NEXT:    sex
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O3-NEXT:    sex
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    ldx <__rs0
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 1,s
; O3-NEXT:    rts
entry:
  %conv = sext i8 %a to i16
  %conv1 = sext i8 %b to i16
  %mul = mul nsw i16 %conv1, %conv
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local signext i8 @mul_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    lda #12
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    lda 10,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -2,s
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    sta -1,u ; 1-byte Folded Spill
; CHECK-HD6309-NEXT:    lda #12
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    lda -1,u ; 1-byte Folded Reload
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    leas 2,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    lda #12
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    lda #12
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    lda #12
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    lda #12
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    rts
entry:
  %mul = mul i8 %a, 12
  %mul2 = mul i8 %mul, %b
  ret i8 %mul2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local zeroext i8 @mul_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    tfr b,a
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldb 10,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    rts
entry:
  %mul = mul i8 %b, %a
  ret i8 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i8_i16(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldb 14,u
; CHECK-NEXT:    stb 9,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 9,u
; CHECK-NEXT:    clra
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    clra
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldx 8,u
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    clra
; CHECK-HD6309-NEXT:    clra
; CHECK-HD6309-NEXT:    pshsw
; CHECK-HD6309-NEXT:    muld ,s++
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i8_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    clra
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,u
; O0-NEXT:    clra
; O0-NEXT:    leas -2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    tfr d,x
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i8_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -1,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    stb 2,u ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,u
; O1-NEXT:    clra
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O1-NEXT:    clra
; O1-NEXT:    leas -2,s
; O1-NEXT:    std ,s
; O1-NEXT:    ldx <__rs0
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 1,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i8_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -1,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    stb 2,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,u
; O2-NEXT:    clra
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O2-NEXT:    clra
; O2-NEXT:    leas -2,s
; O2-NEXT:    std ,s
; O2-NEXT:    ldx <__rs0
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 1,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i8_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -1,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    stb 2,u ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,u
; O3-NEXT:    clra
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb 2,u ; 1-byte Folded Reload
; O3-NEXT:    clra
; O3-NEXT:    leas -2,s
; O3-NEXT:    std ,s
; O3-NEXT:    ldx <__rs0
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 1,s
; O3-NEXT:    rts
entry:
  %conv = zext i8 %a to i16
  %conv1 = zext i8 %b to i16
  %mul = mul nuw i16 %conv1, %conv
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local zeroext i8 @mul_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stb 5,u
; CHECK-NEXT:    lda #13
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    lda 10,u
; CHECK-NEXT:    sta 4,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    mul
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldb 5,u
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -2,s
; CHECK-HD6309-NEXT:    lda 4,u
; CHECK-HD6309-NEXT:    sta -1,u ; 1-byte Folded Spill
; CHECK-HD6309-NEXT:    lda #13
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    lda -1,u ; 1-byte Folded Reload
; CHECK-HD6309-NEXT:    mul
; CHECK-HD6309-NEXT:    leas 2,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    lda #13
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    mul
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    lda #13
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    mul
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    lda #13
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    mul
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    lda #13
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    mul
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    rts
entry:
  %mul = mul i8 %a, 13
  %mul2 = mul i8 %mul, %b
  ret i8 %mul2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    stx 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    stx ,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    stx ,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    stx ,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %mul = mul nsw i16 %b, %a
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_s_i16_consts(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd #754
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld #754
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    ldd #754
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    leas -2,s
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd #754
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd 4,u
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd #754
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd 4,u
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd #754
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd 4,u
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %mul = mul nsw i16 %a, 754
  %mul1 = mul nsw i16 %mul, %b
  ret i16 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i16(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    stx 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    std ,s
; O0-NEXT:    ldx <__rs0
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    stx ,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    stx ,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    stx ,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %mul = mul i16 %b, %a
  ret i16 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i16 @mul_u_i16_consts(i16 noundef %a, i16 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -6,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd #1111
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    lbsr __mulhi3
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 6,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    muld #1111
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    muld 4,u
; CHECK-HD6309-NEXT:    tfr w,d
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    leas -2,s
; O0-NEXT:    ldd #1111
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    leas -2,s
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std ,s
; O0-NEXT:    lbsr __mulhi3
; O0-NEXT:    leas 2,s
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd #1111
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd 4,u
; O1-NEXT:    std ,s
; O1-NEXT:    lbsr __mulhi3
; O1-NEXT:    leas 2,s
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd #1111
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd 4,u
; O2-NEXT:    std ,s
; O2-NEXT:    lbsr __mulhi3
; O2-NEXT:    leas 2,s
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd #1111
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd 4,u
; O3-NEXT:    std ,s
; O3-NEXT:    lbsr __mulhi3
; O3-NEXT:    leas 2,s
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    rts
entry:
  %mul = mul i16 %a, 1111
  %mul1 = mul i16 %mul, %b
  ret i16 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_s_i32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -28,s
; CHECK-NEXT:    pshs y
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 24,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 34,u
; CHECK-NEXT:    std 22,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 26,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 22,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    ldx 24,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    puls y
; CHECK-NEXT:    leas 28,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %mul = mul nsw i32 %b, %a
  ret i32 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_s_i32_consts(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -30,s
; CHECK-NEXT:    pshs y
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 22,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 42,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd #2851
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd #1
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 24,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 28,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 28,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    ldx 22,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    puls y
; CHECK-NEXT:    leas 30,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq #68387
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_s_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 18,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #2851
; O0-NEXT:    std 6,s
; O0-NEXT:    ldd #1
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std 6,s
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 10,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #2851
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd #1
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 10,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 10,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #2851
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 10,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #2851
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd #1
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 10,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 10,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %mul = mul nsw i32 %a, 68387
  %mul1 = mul nsw i32 %mul, %b
  ret i32 %mul1
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_u_i32(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -28,s
; CHECK-NEXT:    pshs y
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 24,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 36,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 34,u
; CHECK-NEXT:    std 22,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 38,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 26,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 22,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    ldx 24,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    puls y
; CHECK-NEXT:    leas 28,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -6,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 6,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -6,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 12,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 6,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -6,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -6,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 12,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 6,s
; O3-NEXT:    rts
entry:
  %mul = mul i32 %b, %a
  ret i32 %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local i32 @mul_u_i32_consts(i32 noundef %a, i32 noundef %b) local_unnamed_addr #0 {
; CHECK-LABEL: mul_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -34,s
; CHECK-NEXT:    pshs y
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    stx 26,u ; 2-byte Folded Spill
; CHECK-NEXT:    ldd 42,u
; CHECK-NEXT:    std 18,u
; CHECK-NEXT:    ldd 40,u
; CHECK-NEXT:    std 24,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 16,u
; CHECK-NEXT:    ldd 46,u
; CHECK-NEXT:    std 22,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 44,u
; CHECK-NEXT:    std 20,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd #6
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd #-7122
; CHECK-NEXT:    std 24,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 28,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 28,u
; CHECK-NEXT:    std 24,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    std 2,s
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std ,s
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 6,s
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 4,s
; CHECK-NEXT:    leay 32,u
; CHECK-NEXT:    tfr y,x
; CHECK-NEXT:    lbsr __mulsi3
; CHECK-NEXT:    ldd 2,y
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 32,u
; CHECK-NEXT:    std 24,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    ldx 26,u ; 2-byte Folded Reload
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    puls y
; CHECK-NEXT:    leas 34,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: mul_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    pshs u
; CHECK-HD6309-NEXT:    tfr s,u
; CHECK-HD6309-NEXT:    leas -12,s
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -4,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq #451630
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq -8,u ; 4-byte Folded Spill
; CHECK-HD6309-NEXT:    ldq -4,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    ldq -8,u ; 4-byte Folded Reload
; CHECK-HD6309-NEXT:    jsr __mulsi3,pc
; CHECK-HD6309-NEXT:    ldq 4,u
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    leas 12,s
; CHECK-HD6309-NEXT:    puls u
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: mul_u_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 18,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #6
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldd #-7122
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    leas -8,s
; O0-NEXT:    std 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std 6,s
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 4,s
; O0-NEXT:    leay 10,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __mulsi3
; O0-NEXT:    ldd 2,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas 8,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 2,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 18,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #6
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd #-7122
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    leas -8,s
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 4,s
; O1-NEXT:    leay 10,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __mulsi3
; O1-NEXT:    ldd 2,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 10,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    leas 8,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 18,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #6
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd #-7122
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    leas -8,s
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 4,s
; O2-NEXT:    leay 10,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __mulsi3
; O2-NEXT:    ldd 2,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    leas 8,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 18,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #6
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd #-7122
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    leas -8,s
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,s
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 4,s
; O3-NEXT:    leay 10,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __mulsi3
; O3-NEXT:    ldd 2,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 10,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    leas 8,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %mul = mul i32 %a, 451630
  %mul1 = mul i32 %mul, %b
  ret i32 %mul1
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"frame-pointer", i32 2}
!2 = !{!"clang version 16.0.0 (https://github.com/llvm-mos/llvm-mos.git 3a36081cf8e78f58d86001abde8d1da1de50027b)"}


define dso_local i64 @mul_s_i64(i64 %a, i64 %b) {
; O0-LABEL: mul_s_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    ldd 30,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 30,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    ldd 30,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %mul = mul nsw i64 %b, %a
  ret i64 %mul
}

define dso_local i64 @mul_s_i64_consts(i64 %a, i64 %b) {
; O0-LABEL: mul_s_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -18,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 30,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #7
; O0-NEXT:    std 14,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 14,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 12,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 10,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 38,u
; O0-NEXT:    std 14,s
; O0-NEXT:    ldd 36,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 34,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 32,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 14,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 18,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_s_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -18,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 30,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #7
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd #0
; O1-NEXT:    std 12,s
; O1-NEXT:    std 10,s
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd 38,u
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 36,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 34,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 32,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 14,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 18,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_s_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -18,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 30,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #7
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 12,s
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 38,u
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 36,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 34,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 32,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 14,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 18,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_s_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -18,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 30,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #7
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd #0
; O3-NEXT:    std 12,s
; O3-NEXT:    std 10,s
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd 38,u
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 36,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 34,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 32,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 14,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 18,s
; O3-NEXT:    rts
entry:
  %mul = mul i64 %a, 7
  %mul1 = mul i64 %mul, %b
  ret i64 %mul1
}

define dso_local i64 @mul_u_i64(i64 %a, i64 %b) {
; O0-LABEL: mul_u_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldd 30,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std <__rs3
; O1-NEXT:    ldd 30,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 30,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std <__rs3
; O3-NEXT:    ldd 30,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %mul = mul i64 %b, %a
  ret i64 %mul
}

define dso_local i64 @mul_u_i64_consts(i64 %a, i64 %b) {
; O0-LABEL: mul_u_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -18,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 30,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #13
; O0-NEXT:    std 14,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 14,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 12,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 10,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd 38,u
; O0-NEXT:    std 14,s
; O0-NEXT:    ldd 36,u
; O0-NEXT:    std 12,s
; O0-NEXT:    ldd 34,u
; O0-NEXT:    std 10,s
; O0-NEXT:    ldd 32,u
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 14,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 18,s
; O0-NEXT:    rts
;
; O1-LABEL: mul_u_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -18,s
; O1-NEXT:    pshs u,y
; O1-NEXT:    tfr s,u
; O1-NEXT:    stx 4,u ; 2-byte Folded Spill
; O1-NEXT:    ldd 30,u
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,u
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd #13
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd #0
; O1-NEXT:    std 12,s
; O1-NEXT:    std 10,s
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 6,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    leas -16,s
; O1-NEXT:    std 6,s
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,s
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,s
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 0,s
; O1-NEXT:    ldd 38,u
; O1-NEXT:    std 14,s
; O1-NEXT:    ldd 36,u
; O1-NEXT:    std 12,s
; O1-NEXT:    ldd 34,u
; O1-NEXT:    std 10,s
; O1-NEXT:    ldd 32,u
; O1-NEXT:    std 8,s
; O1-NEXT:    leay 14,u
; O1-NEXT:    tfr y,x
; O1-NEXT:    lbsr __muldi3
; O1-NEXT:    ldd 6,y
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 4,y
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 2,y
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    leas 16,s
; O1-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u,y
; O1-NEXT:    leas 18,s
; O1-NEXT:    rts
;
; O2-LABEL: mul_u_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -18,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 30,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #13
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 12,s
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 38,u
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd 36,u
; O2-NEXT:    std 12,s
; O2-NEXT:    ldd 34,u
; O2-NEXT:    std 10,s
; O2-NEXT:    ldd 32,u
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 14,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __muldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 16,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 18,s
; O2-NEXT:    rts
;
; O3-LABEL: mul_u_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -18,s
; O3-NEXT:    pshs u,y
; O3-NEXT:    tfr s,u
; O3-NEXT:    stx 4,u ; 2-byte Folded Spill
; O3-NEXT:    ldd 30,u
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,u
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd #13
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd #0
; O3-NEXT:    std 12,s
; O3-NEXT:    std 10,s
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 6,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    leas -16,s
; O3-NEXT:    std 6,s
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,s
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,s
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,s
; O3-NEXT:    ldd 38,u
; O3-NEXT:    std 14,s
; O3-NEXT:    ldd 36,u
; O3-NEXT:    std 12,s
; O3-NEXT:    ldd 34,u
; O3-NEXT:    std 10,s
; O3-NEXT:    ldd 32,u
; O3-NEXT:    std 8,s
; O3-NEXT:    leay 14,u
; O3-NEXT:    tfr y,x
; O3-NEXT:    lbsr __muldi3
; O3-NEXT:    ldd 6,y
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 4,y
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 2,y
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    leas 16,s
; O3-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u,y
; O3-NEXT:    leas 18,s
; O3-NEXT:    rts
entry:
  %mul = mul i64 %a, 13
  %mul1 = mul i64 %mul, %b
  ret i64 %mul1
}

