# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=mc6809 -run-pass=mc6809-spill-opt -o - %s | FileCheck %s

# Regression sentinel for bug #189 (Stage 6 of MC6809PostRASpillOpt).
#
# Folds the pattern
#     LDY  n,u            ; MI1 — load pointer
#     ... (gap of 0..MaxGap=5 MIs that don't touch Y) ...
#     op   ,Y             ; MI2 — dereference via Y, offset 0
#     ... after MI2, Y must be dead ...
# into
#     ... gap MIs unchanged ...
#     op   [n,u]          ; indirect-indexed; MI1 erased
#
# Saves 2-3 bytes (the LDY) and ~3-6 cycles per fold.
#
# Coverage:
#   * `fold_o0_byte`             — LDY 0,u / ORB ,Y / Y dead → ORBi_o0I.
#   * `fold_o8_byte`             — LDY 5,u / ORB ,Y / Y dead → ORBi_o8I.
#   * `fold_o16_word`            — LDY 200,u / CMPD ,Y / Y dead → CMPDi_o16I.
#   * `fold_with_gap3`           — LDY 5,u / 3 frame ops / ORB ,Y → ORBi_o8I.
#   * `negative_y_reused`        — LDY 5,u / ORB ,Y / TFRpp Y to X — must
#                                  NOT fold (Y is read past MI2).
#   * `negative_slot_rewritten`  — LDY 5,u / STA 5,u / ORB ,Y — must NOT
#                                  fold: folded, the deref would read the
#                                  pointer the store just put there.
#   * `negative_y_clobbered_in_gap` — LDY 5,u / LDY 6,u / ORB ,Y — the first
#                                  LDY is dead (Y redefined before use) so
#                                  Bug #362 removes it, then the second
#                                  LDY+ORB pair folds → one indirect ORB.
#   * `negative_y_clobbered_live_first` — as above but the first LDY's value
#                                  is used (STY), so #362 keeps it and only
#                                  the second LDY+ORB folds (Stage 6 picks the
#                                  adjacent LDY, never across the live clobber).

--- |
  define void @fold_o0_byte() { ret void }
  define void @fold_o8_byte() { ret void }
  define void @fold_o16_word() { ret void }
  define void @fold_with_gap3() { ret void }
  define void @negative_y_reused() { ret void }
  define void @negative_y_clobbered_in_gap() { ret void }
  define void @negative_y_clobbered_live_first() { ret void }
  define void @fold_load_through_self_y() { ret void }
  define void @fold_load_through_self_y_o8() { ret void }
  define void @fold_load_through_self_y_o16() { ret void }
  define void @fold_load_through_self_x() { ret void }
  define void @fold_cross_register_y_dead() { ret void }
  define void @negative_cross_register_y_live() { ret void }
  define void @negative_slot_rewritten() { ret void }
...

---
name: fold_o0_byte
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; CHECK-LABEL: name: fold_o0_byte
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ORBi_o0I $su, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o0 $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...

---
name: fold_o8_byte
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $ab
    ; CHECK-LABEL: name: fold_o8_byte
    ; CHECK: liveins: $su, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ORBi_o8I 5, $su, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...

---
name: fold_o16_word
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $ad
    ; CHECK-LABEL: name: fold_o16_word
    ; CHECK: liveins: $su, $ad
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: CMPDi_o16I 200, $su, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $c, implicit $ad
    ; CHECK-NEXT: RTSr
    LDYi_o16 200, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    CMPDi_o0 $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $c, implicit $ad
    RTSr
...

---
name: fold_with_gap3
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $aa, $ab
    ; CHECK-LABEL: name: fold_with_gap3
    ; CHECK: liveins: $su, $aa, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDAi_o5 1, $su, implicit-def $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq
    ; CHECK-NEXT: STAi_o5 2, $su, implicit $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STBi_o5 3, $su, implicit $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: ORBi_o8I 5, $su, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDAi_o5 1, $su, implicit-def $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq
    STAi_o5 2, $su, implicit $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STBi_o5 3, $su, implicit $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...

---
name: negative_y_reused
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $ab
    ; Y is used after MI2 (TFR Y,X) — fold MUST abort.
    ; CHECK-LABEL: name: negative_y_reused
    ; CHECK: liveins: $su, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: $ix = TFRp $iy, implicit-def $nz
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    $ix = TFRp $iy, implicit-def $nz
    RTSr
...

---
name: negative_y_clobbered_in_gap
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $ab
    ; The second LDY redefines Y in the gap, so the first LDY's value is
    ; never used: Bug #362 dead-load DCE removes it, and the SECOND LDY+ORB
    ; then fold (Y dead after the ORB) — the whole thing collapses to one
    ; indirect ORB. (See negative_y_clobbered_live_first for the case where
    ; the first LDY is live and only the second folds.)
    ; CHECK-LABEL: name: negative_y_clobbered_in_gap
    ; CHECK: liveins: $su, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: ORBi_o8I 6, $su, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDYi_o5 6, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...

---
name: negative_y_clobbered_live_first
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $ab
    ; The first LDY's value IS used (stored via STY), so Bug #362 dead-load
    ; DCE keeps it; the second LDY redefines Y and the second LDY+ORB still
    ; fold (Stage 6). Verifies Stage 6 folds the LDY adjacent to the ORB,
    ; never across the earlier (live) clobber — the Bug #189 discrimination
    ; that #362 must not erode.
    ; CHECK-LABEL: name: negative_y_clobbered_live_first
    ; CHECK: liveins: $su, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STYi_o8 100, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: ORBi_o8I 6, $su, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STYi_o8 100, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDYi_o5 6, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...

# ----------------------------------------------------------------------
# Bug #190 cases — load-through-self and cross-register variants.
# ----------------------------------------------------------------------

---
name: fold_load_through_self_y
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; LDY 5,u / LDY ,Y / STY 5,u  →  LDY [5,u] / STY 5,u.
    ; #190 path: mutate MI1 to LDYi_o8I; erase MI2 (LDYi_o0). MI3
    ; (STY) is unchanged. Y is re-defined by MI2, so the standard
    ; #189 dead-after liveness check is skipped.
    ; CHECK-LABEL: name: fold_load_through_self_y
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o8I 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STYi_o5 5, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDYi_o0 $iy, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STYi_o5 5, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    RTSr
...

---
name: fold_load_through_self_y_o8
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; Bug #361: load-through-self where MI1's OWN offset is 8-bit
    ; (LDY 62,u — an LDYi_o8, not o0/o5). Before #361,
    ; getIndirectIndexedOpcode rejected the o8 SOURCE opcode (the macro
    ; only matched _o0/_o5), so the o8/o16 double-deref silently failed
    ; to fold. Now folds to LDY [62,u].
    ; CHECK-LABEL: name: fold_load_through_self_y_o8
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o8I 62, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STYi_o8 62, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: RTSr
    LDYi_o8 62, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDYi_o0 $iy, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STYi_o8 62, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    RTSr
...

---
name: fold_load_through_self_y_o16
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; Bug #361: same, with a 16-bit MI1 offset (LDY 300,u → LDY [300,u]).
    ; CHECK-LABEL: name: fold_load_through_self_y_o16
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o16I 300, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STYi_o16 300, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: RTSr
    LDYi_o16 300, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDYi_o0 $iy, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STYi_o16 300, $su, implicit $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    RTSr
...

---
name: fold_load_through_self_x
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; Same shape but with X instead of Y.
    ; CHECK-LABEL: name: fold_load_through_self_x
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDXi_o8I 7, $su, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STXi_o5 7, $su, implicit $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: RTSr
    LDXi_o5 7, $su, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDXi_o0 $ix, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STXi_o5 7, $su, implicit $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    RTSr
...

---
name: fold_cross_register_y_dead
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; LDY 9,u / LDX ,Y where Y is dead after LDX.
    ; This is the cross-register case — handled by the standard
    ; #189 path with the dead-after liveness check (Y is dead, so
    ; it folds). MI2 is mutated; MI1 is erased.
    ; CHECK-LABEL: name: fold_cross_register_y_dead
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDXi_o8I 9, $su, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: RTSr
    LDYi_o5 9, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDXi_o0 $iy, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    RTSr
...

---
name: negative_cross_register_y_live
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su
    ; LDY 9,u / LDX ,Y / TFR Y,U — Y is read past MI2 by TFR, so
    ; the standard #189 dead-after liveness check fires and the
    ; fold MUST abort. All 3 MIs remain.
    ; CHECK-LABEL: name: negative_cross_register_y_live
    ; CHECK: liveins: $su
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o5 9, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: LDXi_o0 $iy, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: $su = TFRp $iy, implicit-def $nz
    ; CHECK-NEXT: RTSr
    LDYi_o5 9, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    LDXi_o0 $iy, implicit-def $ix, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    $su = TFRp $iy, implicit-def $nz
    RTSr
...

---
name: negative_slot_rewritten
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $su, $aa, $ab
    ; The slot the pointer came from is written before the deref, so the
    ; fold would read the new pointer where this code reads the old one.
    ; CHECK-LABEL: name: negative_slot_rewritten
    ; CHECK: liveins: $su, $aa, $ab
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: STAi_o5 5, $su, implicit $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ; CHECK-NEXT: ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    ; CHECK-NEXT: RTSr
    LDYi_o5 5, $su, implicit-def $iy, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    STAi_o5 5, $su, implicit $aa, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v
    ORBi_o0 $iy, implicit-def $ab, implicit-def $nz, implicit-def $n, implicit-def $z, implicit-def $v, implicit-def $ad, implicit-def $aq, implicit $ab
    RTSr
...
