# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=mc6809 -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s

# Regression sentinel for bug #183.
#
# `PseudoInstExpansion`-based pseudos (BranchSubroutine,
# LongBranchSubroutine, JumpSubroutine, JumpAbsolute, JumpIndir,
# IndirectJumpSubroutine, ReturnImplicit, ReturnIRQImplicit,
# TailJump) used to default `let Size = 0` in TableGen, so
# `MC6809InstrInfo::getInstSizeInBytes` returned 0 for them.
# That silently undercounted block sizes during BranchRelaxation
# and caused PCRel8 fixup overflows that the AsmBackend guard
# only caught at MC fixup time (the originally-observed
# manifestation of bug #174). Bug #174's fix landed a 9-case
# switch in .cpp as a stopgap; bug #183 moved sizes into per-def
# `let Size = N;` declarations in MC6809InstrLogical.td and added
# a MOS-style MaxInstLength fallback in getInstSizeInBytes for
# any future undeclared pseudo.
#
# Both functions below pack bb.0 with `LongBranchSubroutine`
# (Size=3, expands to LBSRlb) so its byte total straddles the
# int8 backward-branch boundary in a way that depends on
# LongBranchSubroutine being credited the right number of bytes:
#
#   * `bug183_must_widen` — bb.0 is 42 × LongBranchSubroutine
#     (= 126 bytes). bb.1's `Bbc` to bb.0 has raw disp -128 →
#     encoded -130 → out of int8, BR MUST widen to LBlbc + LBRAlb.
#     If LongBranchSubroutine reverts to Size=0 AND the
#     MaxInstLength fallback also disappears, bb.0 measures 0
#     bytes, encoded disp drops to -4 (in range), and BR leaves
#     the Bbc short — silent miscompile that the AsmBackend guard
#     would catch at fixup time. CHECK fails before that bug
#     reaches users.
#
#   * `bug183_must_stay_short` — bb.0 is 41 × LongBranchSubroutine
#     (= 123 bytes). Bbc to bb.0 has raw disp -125 → encoded -127
#     → just inside int8, BR MUST leave the Bbc short. If
#     LongBranchSubroutine's `let Size = 3;` is removed and the
#     MaxInstLength fallback (currently 5 bytes) takes over,
#     bb.0 measures 205 bytes, encoded disp -209, and BR widens
#     unnecessarily — codegen pessimisation. CHECK catches that
#     too.
#
# Together the two functions catch every regression mode of
# bug #183: silent undercount (worst case), and conservative
# overcount (commit-1 specifically being lost while the fallback
# remains in place).

--- |
  declare void @bug183_callee()
  define void @bug183_must_widen() { ret void }
  define void @bug183_must_stay_short() { ret void }
...

---
name: bug183_must_widen
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: bug183_must_widen
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $n, $z, $v, $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   Bbc_OnlyZ 7, %bb.2, implicit $z
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.0(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LBRAlb %bb.0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RTSr
  bb.0:
    successors: %bb.1
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee

  bb.1:
    successors: %bb.0, %bb.2
    liveins: $n, $z, $v, $c
    NOPx
    NOPx
    Bbc 6, %bb.0, implicit $n, implicit $z, implicit $v, implicit $c

  bb.2:
    RTSr
...

---
name: bug183_must_stay_short
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: bug183_must_stay_short
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT:   LongBranchSubroutine @bug183_callee
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.0(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $n, $z, $v, $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   NOPx
  ; CHECK-NEXT:   Bbc 6, %bb.0, implicit $n, implicit $z, implicit $v, implicit $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RTSr
  bb.0:
    successors: %bb.1
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee
    LongBranchSubroutine @bug183_callee

  bb.1:
    successors: %bb.0, %bb.2
    liveins: $n, $z, $v, $c
    NOPx
    NOPx
    Bbc 6, %bb.0, implicit $n, implicit $z, implicit $v, implicit $c

  bb.2:
    RTSr
...
