; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mc6809 -mcpu=mc6809 -O2 -global-isel < %s | FileCheck %s --check-prefix=MC6809
; RUN: llc -mtriple=mc6809 -mcpu=hd6309 -O2 -global-isel < %s | FileCheck %s --check-prefix=HD6309
;
; P1 store half: a signed-char-indexed byte store `a[i] = v` folds the sext-i8
; index into the store's own register-offset addressing mode (STA B,X / STB A,X,
; hardware sign-extending the 8-bit offset) instead of SEX-to-D + LEAX + a
; zero-offset store. Value and offset land in opposite accumulators (they
; interfere), so there is no value/offset alias. sld is the matching load.

target datalayout = "E-p:16:8-p1:8:8-S8-m:e-i1:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:0-n8:16"
target triple = "mc6809-unknown-unknown"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write)
define dso_local void @sst(ptr noundef writeonly captures(none) %a, i8 noundef signext %i, i8 noundef signext %v) local_unnamed_addr #0 {
; MC6809-LABEL: sst:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    lda 2,s
; MC6809-NEXT:    sta b,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: sst:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    lda 2,s
; HD6309-NEXT:    sta b,x
; HD6309-NEXT:    rts
entry:
  %idxprom = sext i8 %i to i16
  %arrayidx = getelementptr inbounds i8, ptr %a, i16 %idxprom
  store i8 %v, ptr %arrayidx, align 1, !tbaa !8
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local signext i8 @sld(ptr noundef readonly captures(none) %a, i8 noundef signext %i) local_unnamed_addr #1 {
; MC6809-LABEL: sld:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    ldb b,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: sld:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldb b,x
; HD6309-NEXT:    rts
entry:
  %idxprom = sext i8 %i to i16
  %arrayidx = getelementptr inbounds i8, ptr %a, i16 %idxprom
  %0 = load i8, ptr %arrayidx, align 1, !tbaa !8
  ret i8 %0
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}
!llvm.errno.tbaa = !{!4}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 7, !"PIE Level", i32 2}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 23.0.0git (git@github.com:markrvmurray/llvm-mc6809.git 8c1a7817d0c1354f7566711ad2471ce836ba5641)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!6, !6, i64 0}
