; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mc6809 -mcpu=mc6809 -O2 -global-isel < %s | FileCheck %s --check-prefix=MC6809
; RUN: llc -mtriple=mc6809 -mcpu=hd6309 -O2 -global-isel < %s | FileCheck %s --check-prefix=HD6309
;
; Bug #383: a compare in a VALUE context (`int r = *p == x`) folds its memory
; operand into the compare's addressing mode (cmp ,p / cmp k,p / cmp [n,r]) +
; ConditionalImm, instead of loading it into an accumulator first. The setcc
; value is selected by the C++ G_ICMP arm (the SetIfCondPat Pats do not import
; into GISel), which now mirrors the G_BRCOND memory-fold.

target datalayout = "E-p:16:8-p1:8:8-S8-m:e-i1:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:0-n8:16"
target triple = "mc6809-unknown-unknown"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local range(i16 0, 2) i16 @eqv(ptr noundef readonly captures(none) %p, i8 noundef signext %x) local_unnamed_addr #0 {
; MC6809-LABEL: eqv:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    cmpb ,x
; MC6809-NEXT:    lbeq .LBB0_2
; MC6809-NEXT:  ; %bb.1: ; %entry
; MC6809-NEXT:    ldb #0
; MC6809-NEXT:    bra .LBB0_3
; MC6809-NEXT:  .LBB0_2: ; %entry
; MC6809-NEXT:    ldb #1
; MC6809-NEXT:  .LBB0_3: ; %entry
; MC6809-NEXT:    andb #1
; MC6809-NEXT:    clra
; MC6809-NEXT:    tfr d,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: eqv:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    cmpb ,x
; HD6309-NEXT:    lbeq .LBB0_2
; HD6309-NEXT:  ; %bb.1: ; %entry
; HD6309-NEXT:    ldb #0
; HD6309-NEXT:    bra .LBB0_3
; HD6309-NEXT:  .LBB0_2: ; %entry
; HD6309-NEXT:    ldb #1
; HD6309-NEXT:  .LBB0_3: ; %entry
; HD6309-NEXT:    andb #1
; HD6309-NEXT:    clra
; HD6309-NEXT:    tfr d,x
; HD6309-NEXT:    rts
entry:
  %0 = load i8, ptr %p, align 1, !tbaa !8
  %cmp = icmp eq i8 %0, %x
  %conv2 = zext i1 %cmp to i16
  ret i16 %conv2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local range(i16 0, 2) i16 @idxv(ptr noundef readonly captures(none) %p, i8 noundef signext %x) local_unnamed_addr #0 {
; MC6809-LABEL: idxv:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    cmpb 3,x
; MC6809-NEXT:    lbeq .LBB1_2
; MC6809-NEXT:  ; %bb.1: ; %entry
; MC6809-NEXT:    ldb #0
; MC6809-NEXT:    bra .LBB1_3
; MC6809-NEXT:  .LBB1_2: ; %entry
; MC6809-NEXT:    ldb #1
; MC6809-NEXT:  .LBB1_3: ; %entry
; MC6809-NEXT:    andb #1
; MC6809-NEXT:    clra
; MC6809-NEXT:    tfr d,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: idxv:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    cmpb 3,x
; HD6309-NEXT:    lbeq .LBB1_2
; HD6309-NEXT:  ; %bb.1: ; %entry
; HD6309-NEXT:    ldb #0
; HD6309-NEXT:    bra .LBB1_3
; HD6309-NEXT:  .LBB1_2: ; %entry
; HD6309-NEXT:    ldb #1
; HD6309-NEXT:  .LBB1_3: ; %entry
; HD6309-NEXT:    andb #1
; HD6309-NEXT:    clra
; HD6309-NEXT:    tfr d,x
; HD6309-NEXT:    rts
entry:
  %arrayidx = getelementptr inbounds nuw i8, ptr %p, i16 3
  %0 = load i8, ptr %arrayidx, align 1, !tbaa !8
  %cmp = icmp eq i8 %0, %x
  %conv2 = zext i1 %cmp to i16
  ret i16 %conv2
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none)
define dso_local range(i16 0, 2) i16 @indv(ptr noundef readonly captures(none) %pp, i8 noundef signext %x) local_unnamed_addr #1 {
; MC6809-LABEL: indv:
; MC6809:       ; %bb.0: ; %entry
; MC6809-NEXT:    cmpb [,x]
; MC6809-NEXT:    lbeq .LBB2_2
; MC6809-NEXT:  ; %bb.1: ; %entry
; MC6809-NEXT:    ldb #0
; MC6809-NEXT:    bra .LBB2_3
; MC6809-NEXT:  .LBB2_2: ; %entry
; MC6809-NEXT:    ldb #1
; MC6809-NEXT:  .LBB2_3: ; %entry
; MC6809-NEXT:    andb #1
; MC6809-NEXT:    clra
; MC6809-NEXT:    tfr d,x
; MC6809-NEXT:    rts
;
; HD6309-LABEL: indv:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    cmpb [,x]
; HD6309-NEXT:    lbeq .LBB2_2
; HD6309-NEXT:  ; %bb.1: ; %entry
; HD6309-NEXT:    ldb #0
; HD6309-NEXT:    bra .LBB2_3
; HD6309-NEXT:  .LBB2_2: ; %entry
; HD6309-NEXT:    ldb #1
; HD6309-NEXT:  .LBB2_3: ; %entry
; HD6309-NEXT:    andb #1
; HD6309-NEXT:    clra
; HD6309-NEXT:    tfr d,x
; HD6309-NEXT:    rts
entry:
  %0 = load ptr, ptr %pp, align 1, !tbaa !9
  %1 = load i8, ptr %0, align 1, !tbaa !8
  %cmp = icmp eq i8 %1, %x
  %conv2 = zext i1 %cmp to i16
  ret i16 %conv2
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { mustprogress nofree norecurse nosync nounwind willreturn memory(read, inaccessiblemem: none, target_mem: none) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}
!llvm.errno.tbaa = !{!4}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 7, !"PIE Level", i32 2}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 23.0.0git (git@github.com:markrvmurray/llvm-mc6809.git 4672d2edb53f6d38c7d1195f869b22d1b1cccbaf)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!6, !6, i64 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"p1 omnipotent char", !11, i64 0}
!11 = !{!"any pointer", !6, i64 0}
