; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809               %s -o - | FileCheck %s
; ModuleID = 'sub.c'

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    lda 9,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    adda 11,s
; CHECK-NEXT:    adda 13,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    addb 7,s
; CHECK-NEXT:    addb 9,s
; CHECK-NEXT:    subb #5
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #5
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub4 = sub i8 5, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    lda 9,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    adda 11,s
; CHECK-NEXT:    adda 13,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    addb 7,s
; CHECK-NEXT:    addb 9,s
; CHECK-NEXT:    subb #45
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #45
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub4 = sub i8 45, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    ldd 8,s
; CHECK-NEXT:    addd 6,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    addd 12,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub nsw i16 %a, %b
  %sub1 = sub nsw i16 %sub, %c
  %sub2 = sub nsw i16 %sub1, %d
  %sub3 = sub nsw i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldd 2,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 4,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 8,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #3149
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #3149
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub2 = sub i16 3149, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    ldd 8,s
; CHECK-NEXT:    addd 6,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    addd 12,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub i16 %a, %b
  %sub1 = sub i16 %sub, %c
  %sub2 = sub i16 %sub1, %d
  %sub3 = sub i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldd 2,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 4,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 8,s
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #8447
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #8447
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub2 = sub i16 8447, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    subd 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    sbcb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub nsw i32 %a, %b
  %sub1 = sub nsw i32 %sub, %c
  %sub2 = sub nsw i32 %sub1, %d
  %sub3 = sub nsw i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    addd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    adcb 15,u
; CHECK-NEXT:    adca 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 20,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 19,u
; CHECK-NEXT:    adca 18,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    subd #-21923
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    sbcb #8
; CHECK-NEXT:    sbca #0
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #43613
; CHECK-HD6309-NEXT:    sbcd #8
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub2 = sub i32 567901, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 22,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 21,u
; CHECK-NEXT:    adca 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 26,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 25,u
; CHECK-NEXT:    adca 24,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 30,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    adcb 29,u
; CHECK-NEXT:    adca 28,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    subd 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    sbcb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub = sub i32 %a, %b
  %sub1 = sub i32 %sub, %c
  %sub2 = sub i32 %sub1, %d
  %sub3 = sub i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -8,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    addd 16,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    adcb 15,u
; CHECK-NEXT:    adca 14,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 20,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 19,u
; CHECK-NEXT:    adca 18,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    subd #-2081
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    sbcb #126
; CHECK-NEXT:    sbca #0
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 8,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #63455
; CHECK-HD6309-NEXT:    sbcd #126
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
entry:
  %sub2 = sub i32 8320991, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}
