; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O3
; ModuleID = 'sub.c'

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    lda 5,s
; CHECK-NEXT:    adda 4,s
; CHECK-NEXT:    adda 6,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    subb 2,s
; O0-NEXT:    subb 3,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    lda 3,s
; O1-NEXT:    adda 2,s
; O1-NEXT:    adda 4,s
; O1-NEXT:    adda 5,s
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    lda 3,s
; O2-NEXT:    adda 2,s
; O2-NEXT:    adda 4,s
; O2-NEXT:    adda 5,s
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    lda 3,s
; O3-NEXT:    adda 2,s
; O3-NEXT:    adda 4,s
; O3-NEXT:    adda 5,s
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    subb #5
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #5
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    subb #5
; O0-NEXT:    negb
; O0-NEXT:    subb 2,s
; O0-NEXT:    subb 3,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    subb #5
; O1-NEXT:    negb
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    subb #5
; O2-NEXT:    negb
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    subb #5
; O3-NEXT:    negb
; O3-NEXT:    rts
entry:
  %sub4 = sub i8 5, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    lda 5,s
; CHECK-NEXT:    adda 4,s
; CHECK-NEXT:    adda 6,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    subb 2,s
; O0-NEXT:    subb 3,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    lda 3,s
; O1-NEXT:    adda 2,s
; O1-NEXT:    adda 4,s
; O1-NEXT:    adda 5,s
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    lda 3,s
; O2-NEXT:    adda 2,s
; O2-NEXT:    adda 4,s
; O2-NEXT:    adda 5,s
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    lda 3,s
; O3-NEXT:    adda 2,s
; O3-NEXT:    adda 4,s
; O3-NEXT:    adda 5,s
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    subb #45
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #45
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    subb #45
; O0-NEXT:    negb
; O0-NEXT:    subb 2,s
; O0-NEXT:    subb 3,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    subb #45
; O1-NEXT:    negb
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    subb #45
; O2-NEXT:    negb
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    subb #45
; O3-NEXT:    negb
; O3-NEXT:    rts
entry:
  %sub4 = sub i8 45, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    addd 4,s
; CHECK-NEXT:    addd 8,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    subb 3,s
; O0-NEXT:    sbca 2,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    sbca 4,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    sbca 6,s
; O0-NEXT:    subb 9,s
; O0-NEXT:    sbca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    adda 8,s
; O1-NEXT:    adcb 7,s
; O1-NEXT:    adda 10,s
; O1-NEXT:    adcb 9,s
; O1-NEXT:    adda 12,s
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 1,s
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    adda 8,s
; O2-NEXT:    adcb 7,s
; O2-NEXT:    adda 10,s
; O2-NEXT:    adcb 9,s
; O2-NEXT:    adda 12,s
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 1,s
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    adda 8,s
; O3-NEXT:    adcb 7,s
; O3-NEXT:    adda 10,s
; O3-NEXT:    adcb 9,s
; O3-NEXT:    adda 12,s
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 1,s
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %sub = sub nsw i16 %a, %b
  %sub1 = sub nsw i16 %sub, %c
  %sub2 = sub nsw i16 %sub1, %d
  %sub3 = sub nsw i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #3149
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #3149
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #3149
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    subb ,s
; O0-NEXT:    sbca 2,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    sbca 5,s
; O0-NEXT:    subb 8,s
; O0-NEXT:    sbca 7,s
; O0-NEXT:    subb 10,s
; O0-NEXT:    sbca 9,s
; O0-NEXT:    subb 12,s
; O0-NEXT:    sbca 11,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -2,s
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    adda 5,s
; O1-NEXT:    adcb 4,s
; O1-NEXT:    adda 7,s
; O1-NEXT:    adcb 6,s
; O1-NEXT:    adda 9,s
; O1-NEXT:    adcb 8,s
; O1-NEXT:    adda 11,s
; O1-NEXT:    adcb 10,s
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb #77
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda #12
; O1-NEXT:    sbca ,s
; O1-NEXT:    ldb 1,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    leas 2,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -2,s
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    adda 5,s
; O2-NEXT:    adcb 4,s
; O2-NEXT:    adda 7,s
; O2-NEXT:    adcb 6,s
; O2-NEXT:    adda 9,s
; O2-NEXT:    adcb 8,s
; O2-NEXT:    adda 11,s
; O2-NEXT:    adcb 10,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb #77
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda #12
; O2-NEXT:    sbca ,s
; O2-NEXT:    ldb 1,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -2,s
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    adda 5,s
; O3-NEXT:    adcb 4,s
; O3-NEXT:    adda 7,s
; O3-NEXT:    adcb 6,s
; O3-NEXT:    adda 9,s
; O3-NEXT:    adcb 8,s
; O3-NEXT:    adda 11,s
; O3-NEXT:    adcb 10,s
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb #77
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda #12
; O3-NEXT:    sbca ,s
; O3-NEXT:    ldb 1,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    leas 2,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i16 3149, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    addd 4,s
; CHECK-NEXT:    addd 8,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    subb 3,s
; O0-NEXT:    sbca 2,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    sbca 4,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    sbca 6,s
; O0-NEXT:    subb 9,s
; O0-NEXT:    sbca 8,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -3,s
; O1-NEXT:    ldd 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    adda 8,s
; O1-NEXT:    adcb 7,s
; O1-NEXT:    adda 10,s
; O1-NEXT:    adcb 9,s
; O1-NEXT:    adda 12,s
; O1-NEXT:    adcb 11,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 1,s
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 2,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    leas 3,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -3,s
; O2-NEXT:    ldd 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    adda 8,s
; O2-NEXT:    adcb 7,s
; O2-NEXT:    adda 10,s
; O2-NEXT:    adcb 9,s
; O2-NEXT:    adda 12,s
; O2-NEXT:    adcb 11,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 1,s
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 2,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    leas 3,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -3,s
; O3-NEXT:    ldd 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    adda 8,s
; O3-NEXT:    adcb 7,s
; O3-NEXT:    adda 10,s
; O3-NEXT:    adcb 9,s
; O3-NEXT:    adda 12,s
; O3-NEXT:    adcb 11,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 1,s
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 2,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    leas 3,s
; O3-NEXT:    rts
entry:
  %sub = sub i16 %a, %b
  %sub1 = sub i16 %sub, %c
  %sub2 = sub i16 %sub1, %d
  %sub3 = sub i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #8447
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #8447
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #8447
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    stx <__rs0
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    subb ,s
; O0-NEXT:    sbca 2,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    sbca 5,s
; O0-NEXT:    subb 8,s
; O0-NEXT:    sbca 7,s
; O0-NEXT:    subb 10,s
; O0-NEXT:    sbca 9,s
; O0-NEXT:    subb 12,s
; O0-NEXT:    sbca 11,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -1,s
; O1-NEXT:    stx <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    addb 4,s
; O1-NEXT:    adca 3,s
; O1-NEXT:    addb 6,s
; O1-NEXT:    adca 5,s
; O1-NEXT:    addb 8,s
; O1-NEXT:    adca 7,s
; O1-NEXT:    addb 10,s
; O1-NEXT:    adca 9,s
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    subb #-1
; O1-NEXT:    negb
; O1-NEXT:    lda #32
; O1-NEXT:    suba ,s
; O1-NEXT:    tfr d,x
; O1-NEXT:    leas 1,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -1,s
; O2-NEXT:    stx <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    addb 4,s
; O2-NEXT:    adca 3,s
; O2-NEXT:    addb 6,s
; O2-NEXT:    adca 5,s
; O2-NEXT:    addb 8,s
; O2-NEXT:    adca 7,s
; O2-NEXT:    addb 10,s
; O2-NEXT:    adca 9,s
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    subb #-1
; O2-NEXT:    negb
; O2-NEXT:    lda #32
; O2-NEXT:    suba ,s
; O2-NEXT:    tfr d,x
; O2-NEXT:    leas 1,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -1,s
; O3-NEXT:    stx <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    addb 4,s
; O3-NEXT:    adca 3,s
; O3-NEXT:    addb 6,s
; O3-NEXT:    adca 5,s
; O3-NEXT:    addb 8,s
; O3-NEXT:    adca 7,s
; O3-NEXT:    addb 10,s
; O3-NEXT:    adca 9,s
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    subb #-1
; O3-NEXT:    negb
; O3-NEXT:    lda #32
; O3-NEXT:    suba ,s
; O3-NEXT:    tfr d,x
; O3-NEXT:    leas 1,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i16 8447, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 32,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 31,u
; CHECK-NEXT:    adca 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    subb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 5,u
; CHECK-NEXT:    sbca 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -7,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 13,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 11,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 17,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 15,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 20,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 17,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 24,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 23,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 22,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 21,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 28,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 27,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 25,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    pshs b
; O1-NEXT:    suba ,s+
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 4,s
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 5,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 6,s
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 4,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    leas 7,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -7,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 13,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 11,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 17,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 15,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 20,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 17,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 24,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 23,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 22,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 21,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 28,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 27,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 25,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    pshs b
; O2-NEXT:    suba ,s+
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 4,s
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 5,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 6,s
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    leas 7,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -7,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 13,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 11,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 17,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 15,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 20,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 17,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 24,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 23,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 22,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 21,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 28,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 27,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 25,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    pshs b
; O3-NEXT:    suba ,s+
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 4,s
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 5,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 6,s
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 4,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    leas 7,s
; O3-NEXT:    rts
entry:
  %sub = sub nsw i32 %a, %b
  %sub1 = sub nsw i32 %sub, %c
  %sub2 = sub nsw i32 %sub1, %d
  %sub3 = sub nsw i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -11,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 21,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 20,u
; CHECK-NEXT:    adca 19,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 25,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 24,u
; CHECK-NEXT:    adca 23,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 29,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 28,u
; CHECK-NEXT:    adca 27,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 33,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 32,u
; CHECK-NEXT:    adca 31,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #-21923
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    subb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; CHECK-NEXT:    sta 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldd #8
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 11,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #43613
; CHECK-HD6309-NEXT:    sbcd #8
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #-21923
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #8
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 8,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 7,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 6,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 5,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -4,s
; O1-NEXT:    ldd 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 13,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 12,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 11,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 10,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 17,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 16,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 15,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 14,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 21,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 20,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 25,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 24,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 23,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 22,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda #93
; O1-NEXT:    pshs b
; O1-NEXT:    suba ,s+
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb #-86
; O1-NEXT:    sbcb 1,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb #8
; O1-NEXT:    sbcb 2,s
; O1-NEXT:    lda #0
; O1-NEXT:    sbca 3,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 2,s
; O1-NEXT:    lda 3,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 4,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -4,s
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 13,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 12,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 11,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 10,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 17,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 16,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 15,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 14,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 21,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 20,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 25,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 24,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 23,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 22,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda #93
; O2-NEXT:    pshs b
; O2-NEXT:    suba ,s+
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb #-86
; O2-NEXT:    sbcb 1,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb #8
; O2-NEXT:    sbcb 2,s
; O2-NEXT:    lda #0
; O2-NEXT:    sbca 3,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 2,s
; O2-NEXT:    lda 3,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 4,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -4,s
; O3-NEXT:    ldd 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 13,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 12,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 11,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 10,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 17,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 16,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 15,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 14,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 21,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 20,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 25,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 24,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 23,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 22,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda #93
; O3-NEXT:    pshs b
; O3-NEXT:    suba ,s+
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb #-86
; O3-NEXT:    sbcb 1,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb #8
; O3-NEXT:    sbcb 2,s
; O3-NEXT:    lda #0
; O3-NEXT:    sbca 3,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 2,s
; O3-NEXT:    lda 3,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 4,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i32 567901, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 32,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 31,u
; CHECK-NEXT:    adca 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    subb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 5,u
; CHECK-NEXT:    sbca 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 9,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -7,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 13,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 11,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 17,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 15,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 20,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 17,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 24,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 23,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 22,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 21,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    addb 28,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    adca 27,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 5,s ; 1-byte Folded Reload
; O1-NEXT:    adca 26,s
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 6,s ; 1-byte Folded Reload
; O1-NEXT:    adca 25,s
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    pshs b
; O1-NEXT:    suba ,s+
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 4,s
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 5,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 6,s
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 4,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 5,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std ,x
; O1-NEXT:    leas 7,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -7,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 13,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 11,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 17,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 15,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 20,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 17,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 24,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 23,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 22,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 21,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    addb 28,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    adca 27,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 5,s ; 1-byte Folded Reload
; O2-NEXT:    adca 26,s
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 6,s ; 1-byte Folded Reload
; O2-NEXT:    adca 25,s
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    pshs b
; O2-NEXT:    suba ,s+
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 4,s
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 5,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 6,s
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std ,x
; O2-NEXT:    leas 7,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -7,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 13,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 11,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 17,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 15,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 20,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 17,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 24,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 23,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 22,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 21,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    addb 28,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    adca 27,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 5,s ; 1-byte Folded Reload
; O3-NEXT:    adca 26,s
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 6,s ; 1-byte Folded Reload
; O3-NEXT:    adca 25,s
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    pshs b
; O3-NEXT:    suba ,s+
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 4,s
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 5,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 6,s
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 4,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 5,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std ,x
; O3-NEXT:    leas 7,s
; O3-NEXT:    rts
entry:
  %sub = sub i32 %a, %b
  %sub1 = sub i32 %sub, %c
  %sub2 = sub i32 %sub1, %d
  %sub3 = sub i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -11,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 21,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 20,u
; CHECK-NEXT:    adca 19,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 25,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 24,u
; CHECK-NEXT:    adca 23,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 29,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 28,u
; CHECK-NEXT:    adca 27,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 33,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 32,u
; CHECK-NEXT:    adca 31,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #-2081
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    subb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; CHECK-NEXT:    sta 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldd #126
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 11,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #63455
; CHECK-HD6309-NEXT:    sbcd #126
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #-2081
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #126
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 8,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 7,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 6,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 5,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 9,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 16,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 13,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 20,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 19,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 18,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 17,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    subb 24,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 23,s
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 21,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    lda 2,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb 1,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 3,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -4,s
; O1-NEXT:    ldd 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 6,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 13,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 12,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 11,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 10,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 17,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 16,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 15,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 14,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 21,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 20,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 19,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 18,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    addb 25,s
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    adca 24,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 23,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda 3,s ; 1-byte Folded Reload
; O1-NEXT:    adca 22,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda #-33
; O1-NEXT:    pshs b
; O1-NEXT:    suba ,s+
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb #-9
; O1-NEXT:    sbcb 1,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb #126
; O1-NEXT:    sbcb 2,s
; O1-NEXT:    lda #0
; O1-NEXT:    sbca 3,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 2,s
; O1-NEXT:    lda 3,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 4,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -4,s
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 13,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 12,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 11,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 10,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 17,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 16,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 15,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 14,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 21,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 20,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 19,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 18,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    addb 25,s
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    adca 24,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 23,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda 3,s ; 1-byte Folded Reload
; O2-NEXT:    adca 22,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda #-33
; O2-NEXT:    pshs b
; O2-NEXT:    suba ,s+
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb #-9
; O2-NEXT:    sbcb 1,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb #126
; O2-NEXT:    sbcb 2,s
; O2-NEXT:    lda #0
; O2-NEXT:    sbca 3,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 2,s
; O2-NEXT:    lda 3,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 4,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -4,s
; O3-NEXT:    ldd 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 6,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 13,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 12,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 11,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 10,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 17,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 16,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 15,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 14,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 21,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 20,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 19,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 18,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    addb 25,s
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    adca 24,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 23,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda 3,s ; 1-byte Folded Reload
; O3-NEXT:    adca 22,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda #-33
; O3-NEXT:    pshs b
; O3-NEXT:    suba ,s+
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb #-9
; O3-NEXT:    sbcb 1,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb #126
; O3-NEXT:    sbcb 2,s
; O3-NEXT:    lda #0
; O3-NEXT:    sbca 3,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 2,s
; O3-NEXT:    lda 3,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 4,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i32 8320991, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}

define dso_local i64 @sub_s_i64(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: sub_s_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 34,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 32,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    adca 39,s
; O0-NEXT:    sta 10,s ; 1-byte Folded Spill
; O0-NEXT:    lda 15,s ; 1-byte Folded Reload
; O0-NEXT:    adca 38,s
; O0-NEXT:    sta 15,s ; 1-byte Folded Spill
; O0-NEXT:    lda 9,s ; 1-byte Folded Reload
; O0-NEXT:    adca 37,s
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 44,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    lda 8,s ; 1-byte Folded Reload
; O0-NEXT:    adca 43,s
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 57,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 56,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 55,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 54,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 53,s
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 52,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    adca 51,s
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 50,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    subb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda 7,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 14,s
; O0-NEXT:    sta 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 9,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 11,s
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 8,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    lda 9,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 5,s
; O0-NEXT:    lda 8,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr a,b
; O0-NEXT:    lda 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    ldd 32,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 30,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 28,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    adca 39,s
; O1-NEXT:    sta 10,s ; 1-byte Folded Spill
; O1-NEXT:    lda 15,s ; 1-byte Folded Reload
; O1-NEXT:    adca 38,s
; O1-NEXT:    sta 15,s ; 1-byte Folded Spill
; O1-NEXT:    lda 9,s ; 1-byte Folded Reload
; O1-NEXT:    adca 37,s
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    adca 45,s
; O1-NEXT:    sta 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 44,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    lda 8,s ; 1-byte Folded Reload
; O1-NEXT:    adca 43,s
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 57,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 56,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 55,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 54,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 53,s
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 52,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    adca 51,s
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 50,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    subb 13,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 7,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 14,s
; O1-NEXT:    sta 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 10,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 15,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 9,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 11,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 8,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    lda 9,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 5,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr a,b
; O1-NEXT:    lda 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    ldd 32,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 30,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 28,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    adca 39,s
; O2-NEXT:    sta 10,s ; 1-byte Folded Spill
; O2-NEXT:    lda 15,s ; 1-byte Folded Reload
; O2-NEXT:    adca 38,s
; O2-NEXT:    sta 15,s ; 1-byte Folded Spill
; O2-NEXT:    lda 9,s ; 1-byte Folded Reload
; O2-NEXT:    adca 37,s
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    adca 45,s
; O2-NEXT:    sta 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 44,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    lda 8,s ; 1-byte Folded Reload
; O2-NEXT:    adca 43,s
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 57,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 56,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 55,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 54,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 53,s
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 52,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    adca 51,s
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 50,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    subb 13,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 7,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 14,s
; O2-NEXT:    sta 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 10,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 15,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 9,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 11,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 8,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 9,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr a,b
; O2-NEXT:    lda 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    ldd 32,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 30,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 28,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    adca 39,s
; O3-NEXT:    sta 10,s ; 1-byte Folded Spill
; O3-NEXT:    lda 15,s ; 1-byte Folded Reload
; O3-NEXT:    adca 38,s
; O3-NEXT:    sta 15,s ; 1-byte Folded Spill
; O3-NEXT:    lda 9,s ; 1-byte Folded Reload
; O3-NEXT:    adca 37,s
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    adca 45,s
; O3-NEXT:    sta 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 44,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    lda 8,s ; 1-byte Folded Reload
; O3-NEXT:    adca 43,s
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 57,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 56,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 55,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 54,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 53,s
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 52,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    adca 51,s
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 50,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    subb 13,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 7,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 14,s
; O3-NEXT:    sta 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 10,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 15,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 9,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 11,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 8,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    lda 9,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 5,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr a,b
; O3-NEXT:    lda 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %0 = add i64 %b, %c
  %1 = add i64 %0, %d
  %2 = add i64 %1, %e
  %sub3 = sub i64 %a, %2
  ret i64 %sub3
}

define dso_local i64 @sub_s_i64_consts(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: sub_s_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    sta 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 9,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    addb #119
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #152
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #186
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #220
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #254
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 32,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 32,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 30,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 30,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 28,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 28,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 38,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 34,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 45,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 44,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    lda 2,s ; 1-byte Folded Reload
; O0-NEXT:    adca 43,s
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 57,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 56,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 55,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 54,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 53,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 52,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    adca 51,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 50,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    suba 10,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 13,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    lda 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 2,s
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 8,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 3,s
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    lda 9,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    lda 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 11,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 6,s
; O0-NEXT:    lda 10,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 7,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 9,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    addb #119
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-104
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-70
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-36
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-2
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 32,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 32,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 30,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 30,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 28,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 28,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 38,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 34,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 45,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 44,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 43,s
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 57,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 56,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 55,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 54,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 53,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 52,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    adca 51,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 50,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    suba 10,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 11,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 12,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 13,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 14,s
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 15,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 2,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 8,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 3,s
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    lda 9,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 11,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 7,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 9,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    addb #119
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-104
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-70
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-36
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-2
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 32,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 32,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 30,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 30,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 28,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 28,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 38,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 34,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 45,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 44,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 43,s
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 57,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 56,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 55,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 54,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 53,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 52,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    adca 51,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 50,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    suba 10,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 11,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 13,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 14,s
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 15,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 2,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 8,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 3,s
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 9,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 11,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 7,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 9,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    addb #119
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-104
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-70
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-36
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-2
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 32,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 32,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 30,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 30,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 28,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 28,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 38,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 34,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 45,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 44,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 43,s
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 57,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 56,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 55,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 54,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 53,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 52,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    adca 51,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 50,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    suba 10,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 11,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 12,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 13,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 14,s
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 15,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 2,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 8,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 3,s
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    lda 9,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 11,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %.neg = add i64 %a, -4886718345
  %0 = add i64 %b, %c
  %1 = add i64 %0, %d
  %2 = add i64 %1, %e
  %sub4 = sub i64 %.neg, %2
  ret i64 %sub4
}

define dso_local i64 @sub_u_i64(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: sub_u_i64:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 34,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 32,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 30,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    adca 39,s
; O0-NEXT:    sta 10,s ; 1-byte Folded Spill
; O0-NEXT:    lda 15,s ; 1-byte Folded Reload
; O0-NEXT:    adca 38,s
; O0-NEXT:    sta 15,s ; 1-byte Folded Spill
; O0-NEXT:    lda 9,s ; 1-byte Folded Reload
; O0-NEXT:    adca 37,s
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 34,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    adca 45,s
; O0-NEXT:    sta 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 44,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    lda 8,s ; 1-byte Folded Reload
; O0-NEXT:    adca 43,s
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    addb 57,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 56,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 55,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 54,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 53,s
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 52,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    adca 51,s
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 50,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    subb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda 7,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 14,s
; O0-NEXT:    sta 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 9,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    lda 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 11,s
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda ,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 8,s
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    lda 9,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 5,s
; O0-NEXT:    lda 8,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    tfr a,b
; O0-NEXT:    lda 2,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i64:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    ldd 32,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldd 30,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    ldd 28,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    pshs a
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    puls a
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    adca 39,s
; O1-NEXT:    sta 10,s ; 1-byte Folded Spill
; O1-NEXT:    lda 15,s ; 1-byte Folded Reload
; O1-NEXT:    adca 38,s
; O1-NEXT:    sta 15,s ; 1-byte Folded Spill
; O1-NEXT:    lda 9,s ; 1-byte Folded Reload
; O1-NEXT:    adca 37,s
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 34,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    adca 45,s
; O1-NEXT:    sta 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 44,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    lda 8,s ; 1-byte Folded Reload
; O1-NEXT:    adca 43,s
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    addb 57,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 56,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 55,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 54,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 53,s
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 52,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    adca 51,s
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 50,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 18,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    subb 13,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda 7,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 14,s
; O1-NEXT:    sta 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 10,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 15,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 9,s
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 11,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda ,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 8,s
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 12,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    lda 9,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 5,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    lda 6,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    tfr a,b
; O1-NEXT:    lda 2,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 6,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 4,x
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std 2,x
; O1-NEXT:    puls d
; O1-NEXT:    std ,x
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i64:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    ldd 32,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 30,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 28,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    pshs a
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    puls a
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    adca 39,s
; O2-NEXT:    sta 10,s ; 1-byte Folded Spill
; O2-NEXT:    lda 15,s ; 1-byte Folded Reload
; O2-NEXT:    adca 38,s
; O2-NEXT:    sta 15,s ; 1-byte Folded Spill
; O2-NEXT:    lda 9,s ; 1-byte Folded Reload
; O2-NEXT:    adca 37,s
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 34,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    adca 45,s
; O2-NEXT:    sta 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 44,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    lda 8,s ; 1-byte Folded Reload
; O2-NEXT:    adca 43,s
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    addb 57,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 56,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 55,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 54,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 53,s
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 52,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    adca 51,s
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 50,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 18,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    subb 13,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda 7,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 14,s
; O2-NEXT:    sta 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 10,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 15,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 9,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 11,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda ,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 8,s
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 9,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    tfr a,b
; O2-NEXT:    lda 2,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i64:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    ldd 32,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldd 30,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    ldd 28,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    pshs a
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    puls a
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    adca 39,s
; O3-NEXT:    sta 10,s ; 1-byte Folded Spill
; O3-NEXT:    lda 15,s ; 1-byte Folded Reload
; O3-NEXT:    adca 38,s
; O3-NEXT:    sta 15,s ; 1-byte Folded Spill
; O3-NEXT:    lda 9,s ; 1-byte Folded Reload
; O3-NEXT:    adca 37,s
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 34,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    adca 45,s
; O3-NEXT:    sta 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 44,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    lda 8,s ; 1-byte Folded Reload
; O3-NEXT:    adca 43,s
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    addb 57,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 56,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 55,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 54,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 53,s
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 52,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    adca 51,s
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 50,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 18,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    subb 13,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda 7,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 14,s
; O3-NEXT:    sta 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 10,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 15,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 9,s
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 11,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda ,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 8,s
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 12,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    lda 9,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 5,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    lda 6,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    tfr a,b
; O3-NEXT:    lda 2,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 6,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 4,x
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std 2,x
; O3-NEXT:    puls d
; O3-NEXT:    std ,x
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %0 = add i64 %b, %c
  %1 = add i64 %0, %d
  %2 = add i64 %1, %e
  %sub3 = sub i64 %a, %2
  ret i64 %sub3
}

define dso_local i64 @sub_u_i64_consts(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; O0-LABEL: sub_u_i64_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 26,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 24,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    sta 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs2lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 9,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs2hi
; O0-NEXT:    sta ,s ; 1-byte Folded Spill
; O0-NEXT:    pshs b
; O0-NEXT:    ldb <__rs3lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    puls b
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs3hi
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    addb #17
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #65
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #82
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #33
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O0-NEXT:    adcb #255
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 32,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 32,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 30,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 30,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 28,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldd 28,s
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 28,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 41,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 40,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 39,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 38,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 37,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 36,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 35,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    adca 34,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 49,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 48,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 47,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 46,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 45,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 44,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    lda 2,s ; 1-byte Folded Reload
; O0-NEXT:    adca 43,s
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 42,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    addb 57,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 56,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 55,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 54,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 53,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 52,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    adca 51,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    adcb 50,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    suba 10,s
; O0-NEXT:    sta 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 11,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 13,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    lda 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 2,s
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 8,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 3,s
; O0-NEXT:    sta 8,s ; 1-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    lda 9,s
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 7,s
; O0-NEXT:    lda 8,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 11,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 6,s
; O0-NEXT:    lda 10,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i64_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 26,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 24,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 22,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 20,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    sta 7,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs1lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 5,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs1hi
; O1-NEXT:    sta 6,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs2lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 9,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs2hi
; O1-NEXT:    sta ,s ; 1-byte Folded Spill
; O1-NEXT:    pshs b
; O1-NEXT:    ldb <__rs3lo
; O1-NEXT:    tfr b,a
; O1-NEXT:    puls b
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs3hi
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    addb #17
; O1-NEXT:    stb 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #65
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #82
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #33
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb ,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb 4,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O1-NEXT:    adcb #-1
; O1-NEXT:    stb 8,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 32,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 32,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 30,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 30,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 28,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldd 28,s
; O1-NEXT:    tfr a,b
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldd 28,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    ldb <__rs0lo
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    lda <__rs0hi
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 41,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 40,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 39,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 38,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 37,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 36,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 35,s
; O1-NEXT:    stb 2,s ; 1-byte Folded Spill
; O1-NEXT:    adca 34,s
; O1-NEXT:    sta 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 49,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 48,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 47,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 46,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 45,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 44,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    lda 2,s ; 1-byte Folded Reload
; O1-NEXT:    adca 43,s
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 42,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O1-NEXT:    addb 57,s
; O1-NEXT:    stb 10,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 56,s
; O1-NEXT:    stb 11,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 55,s
; O1-NEXT:    stb 12,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 54,s
; O1-NEXT:    stb 13,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 53,s
; O1-NEXT:    stb 14,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 52,s
; O1-NEXT:    stb 15,s ; 1-byte Folded Spill
; O1-NEXT:    adca 51,s
; O1-NEXT:    sta 2,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O1-NEXT:    adcb 50,s
; O1-NEXT:    stb 3,s ; 1-byte Folded Spill
; O1-NEXT:    lda 1,s ; 1-byte Folded Reload
; O1-NEXT:    suba 10,s
; O1-NEXT:    sta 1,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 11,s
; O1-NEXT:    stb 7,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 12,s
; O1-NEXT:    stb 5,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 13,s
; O1-NEXT:    stb 6,s ; 1-byte Folded Spill
; O1-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 14,s
; O1-NEXT:    stb 9,s ; 1-byte Folded Spill
; O1-NEXT:    ldb ,s ; 1-byte Folded Reload
; O1-NEXT:    sbcb 15,s
; O1-NEXT:    lda 4,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 2,s
; O1-NEXT:    sta 4,s ; 1-byte Folded Spill
; O1-NEXT:    lda 8,s ; 1-byte Folded Reload
; O1-NEXT:    sbca 3,s
; O1-NEXT:    sta 8,s ; 1-byte Folded Spill
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 3,s
; O1-NEXT:    lda 9,s
; O1-NEXT:    std <__rs3
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    ldb 7,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs0
; O1-NEXT:    puls d
; O1-NEXT:    pshs d
; O1-NEXT:    tfr b,a
; O1-NEXT:    ldb 11,s
; O1-NEXT:    std <__rs1
; O1-NEXT:    puls d
; O1-NEXT:    ldb 4,s
; O1-NEXT:    lda 8,s
; O1-NEXT:    std <__rs2
; O1-NEXT:    ldd <__rs3
; O1-NEXT:    std 6,x
; O1-NEXT:    ldd <__rs0
; O1-NEXT:    std 4,x
; O1-NEXT:    ldd <__rs1
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd <__rs2
; O1-NEXT:    std ,x
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i64_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 26,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 24,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 22,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 7,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 5,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta 6,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 9,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    sta ,s ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    addb #17
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #65
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #82
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #33
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O2-NEXT:    adcb #-1
; O2-NEXT:    stb 8,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 32,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 32,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 30,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 30,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 28,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldd 28,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 28,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 41,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 40,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 39,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 38,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 37,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 36,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 35,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    adca 34,s
; O2-NEXT:    sta 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 49,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 48,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 47,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 45,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 44,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    lda 2,s ; 1-byte Folded Reload
; O2-NEXT:    adca 43,s
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O2-NEXT:    addb 57,s
; O2-NEXT:    stb 10,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 56,s
; O2-NEXT:    stb 11,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 55,s
; O2-NEXT:    stb 12,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 54,s
; O2-NEXT:    stb 13,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 53,s
; O2-NEXT:    stb 14,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 52,s
; O2-NEXT:    stb 15,s ; 1-byte Folded Spill
; O2-NEXT:    adca 51,s
; O2-NEXT:    sta 2,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O2-NEXT:    adcb 50,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    lda 1,s ; 1-byte Folded Reload
; O2-NEXT:    suba 10,s
; O2-NEXT:    sta 1,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 11,s
; O2-NEXT:    stb 7,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 13,s
; O2-NEXT:    stb 6,s ; 1-byte Folded Spill
; O2-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 14,s
; O2-NEXT:    stb 9,s ; 1-byte Folded Spill
; O2-NEXT:    ldb ,s ; 1-byte Folded Reload
; O2-NEXT:    sbcb 15,s
; O2-NEXT:    lda 4,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 2,s
; O2-NEXT:    sta 4,s ; 1-byte Folded Spill
; O2-NEXT:    lda 8,s ; 1-byte Folded Reload
; O2-NEXT:    sbca 3,s
; O2-NEXT:    sta 8,s ; 1-byte Folded Spill
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 9,s
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 11,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    ldb 4,s
; O2-NEXT:    lda 8,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i64_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 26,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 24,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 22,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 20,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    sta 7,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs1lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 5,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs1hi
; O3-NEXT:    sta 6,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs2lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 9,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs2hi
; O3-NEXT:    sta ,s ; 1-byte Folded Spill
; O3-NEXT:    pshs b
; O3-NEXT:    ldb <__rs3lo
; O3-NEXT:    tfr b,a
; O3-NEXT:    puls b
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs3hi
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    addb #17
; O3-NEXT:    stb 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #65
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #82
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #33
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb ,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb 4,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O3-NEXT:    adcb #-1
; O3-NEXT:    stb 8,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 32,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 32,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 30,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 30,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 28,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldd 28,s
; O3-NEXT:    tfr a,b
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldd 28,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    ldb <__rs0lo
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    lda <__rs0hi
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 41,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 40,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 39,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 38,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 37,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 36,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 35,s
; O3-NEXT:    stb 2,s ; 1-byte Folded Spill
; O3-NEXT:    adca 34,s
; O3-NEXT:    sta 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 49,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 48,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 47,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 46,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 45,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 44,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    lda 2,s ; 1-byte Folded Reload
; O3-NEXT:    adca 43,s
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 42,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O3-NEXT:    addb 57,s
; O3-NEXT:    stb 10,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 56,s
; O3-NEXT:    stb 11,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 55,s
; O3-NEXT:    stb 12,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 54,s
; O3-NEXT:    stb 13,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 53,s
; O3-NEXT:    stb 14,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 52,s
; O3-NEXT:    stb 15,s ; 1-byte Folded Spill
; O3-NEXT:    adca 51,s
; O3-NEXT:    sta 2,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O3-NEXT:    adcb 50,s
; O3-NEXT:    stb 3,s ; 1-byte Folded Spill
; O3-NEXT:    lda 1,s ; 1-byte Folded Reload
; O3-NEXT:    suba 10,s
; O3-NEXT:    sta 1,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 11,s
; O3-NEXT:    stb 7,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 12,s
; O3-NEXT:    stb 5,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 13,s
; O3-NEXT:    stb 6,s ; 1-byte Folded Spill
; O3-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 14,s
; O3-NEXT:    stb 9,s ; 1-byte Folded Spill
; O3-NEXT:    ldb ,s ; 1-byte Folded Reload
; O3-NEXT:    sbcb 15,s
; O3-NEXT:    lda 4,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 2,s
; O3-NEXT:    sta 4,s ; 1-byte Folded Spill
; O3-NEXT:    lda 8,s ; 1-byte Folded Reload
; O3-NEXT:    sbca 3,s
; O3-NEXT:    sta 8,s ; 1-byte Folded Spill
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 3,s
; O3-NEXT:    lda 9,s
; O3-NEXT:    std <__rs3
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    ldb 7,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs0
; O3-NEXT:    puls d
; O3-NEXT:    pshs d
; O3-NEXT:    tfr b,a
; O3-NEXT:    ldb 11,s
; O3-NEXT:    std <__rs1
; O3-NEXT:    puls d
; O3-NEXT:    ldb 4,s
; O3-NEXT:    lda 8,s
; O3-NEXT:    std <__rs2
; O3-NEXT:    ldd <__rs3
; O3-NEXT:    std 6,x
; O3-NEXT:    ldd <__rs0
; O3-NEXT:    std 4,x
; O3-NEXT:    ldd <__rs1
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd <__rs2
; O3-NEXT:    std ,x
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %.neg = add i64 %a, -3735928559
  %0 = add i64 %b, %c
  %1 = add i64 %0, %d
  %2 = add i64 %1, %e
  %sub4 = sub i64 %.neg, %2
  ret i64 %sub4
}

