; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O3
; ModuleID = 'sub.c'

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    lda 5,s
; CHECK-NEXT:    adda 4,s
; CHECK-NEXT:    adda 6,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -2,s
; O1-NEXT:    lda 5,s
; O1-NEXT:    adda 4,s
; O1-NEXT:    adda 6,s
; O1-NEXT:    adda 7,s
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    leas 2,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -2,s
; O2-NEXT:    lda 5,s
; O2-NEXT:    adda 4,s
; O2-NEXT:    adda 6,s
; O2-NEXT:    adda 7,s
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -2,s
; O3-NEXT:    lda 5,s
; O3-NEXT:    adda 4,s
; O3-NEXT:    adda 6,s
; O3-NEXT:    adda 7,s
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    leas 2,s
; O3-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local signext i8 @sub_s_i8_consts(i8 noundef signext %a, i8 noundef signext %b, i8 noundef signext %c, i8 noundef signext %d, i8 noundef signext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    subb #5
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #5
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    subb #5
; O0-NEXT:    negb
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    subb #5
; O1-NEXT:    negb
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    subb #5
; O2-NEXT:    negb
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    subb #5
; O3-NEXT:    negb
; O3-NEXT:    rts
entry:
  %sub4 = sub i8 5, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    lda 5,s
; CHECK-NEXT:    adda 4,s
; CHECK-NEXT:    adda 6,s
; CHECK-NEXT:    adda 7,s
; CHECK-NEXT:    pshs a
; CHECK-NEXT:    subb ,s+
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -2,s
; O1-NEXT:    lda 5,s
; O1-NEXT:    adda 4,s
; O1-NEXT:    adda 6,s
; O1-NEXT:    adda 7,s
; O1-NEXT:    pshs a
; O1-NEXT:    subb ,s+
; O1-NEXT:    leas 2,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -2,s
; O2-NEXT:    lda 5,s
; O2-NEXT:    adda 4,s
; O2-NEXT:    adda 6,s
; O2-NEXT:    adda 7,s
; O2-NEXT:    pshs a
; O2-NEXT:    subb ,s+
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -2,s
; O3-NEXT:    lda 5,s
; O3-NEXT:    adda 4,s
; O3-NEXT:    adda 6,s
; O3-NEXT:    adda 7,s
; O3-NEXT:    pshs a
; O3-NEXT:    subb ,s+
; O3-NEXT:    leas 2,s
; O3-NEXT:    rts
entry:
  %sub = sub i8 %a, %b
  %sub3 = sub i8 %sub, %c
  %sub5 = sub i8 %sub3, %d
  %sub7 = sub i8 %sub5, %e
  ret i8 %sub7
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local zeroext i8 @sub_u_i8_consts(i8 noundef zeroext %a, i8 noundef zeroext %b, i8 noundef zeroext %c, i8 noundef zeroext %d, i8 noundef zeroext %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i8_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    addb 2,s
; CHECK-NEXT:    addb 3,s
; CHECK-NEXT:    addb 4,s
; CHECK-NEXT:    addb 5,s
; CHECK-NEXT:    subb #45
; CHECK-NEXT:    negb
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i8_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subb #45
; CHECK-HD6309-NEXT:    negb
; CHECK-HD6309-NEXT:    subb 2,s
; CHECK-HD6309-NEXT:    subb 3,s
; CHECK-HD6309-NEXT:    subb 4,s
; CHECK-HD6309-NEXT:    subb 5,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i8_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    subb #45
; O0-NEXT:    negb
; O0-NEXT:    subb 4,s
; O0-NEXT:    subb 5,s
; O0-NEXT:    subb 6,s
; O0-NEXT:    subb 7,s
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i8_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    addb 3,s
; O1-NEXT:    addb 4,s
; O1-NEXT:    addb 5,s
; O1-NEXT:    subb #45
; O1-NEXT:    negb
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i8_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    addb 3,s
; O2-NEXT:    addb 4,s
; O2-NEXT:    addb 5,s
; O2-NEXT:    subb #45
; O2-NEXT:    negb
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i8_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    addb 3,s
; O3-NEXT:    addb 4,s
; O3-NEXT:    addb 5,s
; O3-NEXT:    subb #45
; O3-NEXT:    negb
; O3-NEXT:    rts
entry:
  %sub4 = sub i8 45, %a
  %sub5 = sub i8 %sub4, %b
  %sub7 = sub i8 %sub5, %c
  %sub9 = sub i8 %sub7, %d
  %sub10 = sub i8 %sub9, %e
  ret i8 %sub10
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    addd 4,s
; CHECK-NEXT:    addd 8,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 8,u
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std 14,u
; O0-NEXT:    ldd 8,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 12,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 12,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 10,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd 6,s
; O1-NEXT:    addd 4,s
; O1-NEXT:    addd 8,s
; O1-NEXT:    addd 10,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd #0
; O1-NEXT:    subd ,s++
; O1-NEXT:    leax d,x
; O1-NEXT:    leas 2,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd 6,s
; O2-NEXT:    addd 4,s
; O2-NEXT:    addd 8,s
; O2-NEXT:    addd 10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd #0
; O2-NEXT:    subd ,s++
; O2-NEXT:    leax d,x
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd 6,s
; O3-NEXT:    addd 4,s
; O3-NEXT:    addd 8,s
; O3-NEXT:    addd 10,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd #0
; O3-NEXT:    subd ,s++
; O3-NEXT:    leax d,x
; O3-NEXT:    leas 2,s
; O3-NEXT:    rts
entry:
  %sub = sub nsw i16 %a, %b
  %sub1 = sub nsw i16 %sub, %c
  %sub2 = sub nsw i16 %sub1, %d
  %sub3 = sub nsw i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_s_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #3149
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #3149
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    subd #3149
; O0-NEXT:    coma
; O0-NEXT:    comb
; O0-NEXT:    addd #1
; O0-NEXT:    subd 4,s
; O0-NEXT:    subd 6,s
; O0-NEXT:    subd 8,s
; O0-NEXT:    subd 10,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std 14,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 12,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 14,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 12,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 10,u
; O1-NEXT:    leax d,x
; O1-NEXT:    tfr x,d
; O1-NEXT:    subd #3149
; O1-NEXT:    coma
; O1-NEXT:    comb
; O1-NEXT:    addd #1
; O1-NEXT:    tfr d,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std 14,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 12,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 14,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 12,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 10,u
; O2-NEXT:    leax d,x
; O2-NEXT:    tfr x,d
; O2-NEXT:    subd #3149
; O2-NEXT:    coma
; O2-NEXT:    comb
; O2-NEXT:    addd #1
; O2-NEXT:    tfr d,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std 14,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 12,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 14,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 12,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 10,u
; O3-NEXT:    leax d,x
; O3-NEXT:    tfr x,d
; O3-NEXT:    subd #3149
; O3-NEXT:    coma
; O3-NEXT:    comb
; O3-NEXT:    addd #1
; O3-NEXT:    tfr d,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i16 3149, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd 6,s
; CHECK-NEXT:    addd 4,s
; CHECK-NEXT:    addd 8,s
; CHECK-NEXT:    addd 10,s
; CHECK-NEXT:    pshs d
; CHECK-NEXT:    ldd #0
; CHECK-NEXT:    subd ,s++
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i16:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std 8,u
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std 14,u
; O0-NEXT:    ldd 8,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 24,u
; O0-NEXT:    std 12,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 26,u
; O0-NEXT:    std 10,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 14,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 12,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    ldd 10,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    subd ,s++
; O0-NEXT:    leax d,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i16:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -2,s
; O1-NEXT:    ldd 6,s
; O1-NEXT:    addd 4,s
; O1-NEXT:    addd 8,s
; O1-NEXT:    addd 10,s
; O1-NEXT:    pshs d
; O1-NEXT:    ldd #0
; O1-NEXT:    subd ,s++
; O1-NEXT:    leax d,x
; O1-NEXT:    leas 2,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i16:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -2,s
; O2-NEXT:    ldd 6,s
; O2-NEXT:    addd 4,s
; O2-NEXT:    addd 8,s
; O2-NEXT:    addd 10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd #0
; O2-NEXT:    subd ,s++
; O2-NEXT:    leax d,x
; O2-NEXT:    leas 2,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i16:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -2,s
; O3-NEXT:    ldd 6,s
; O3-NEXT:    addd 4,s
; O3-NEXT:    addd 8,s
; O3-NEXT:    addd 10,s
; O3-NEXT:    pshs d
; O3-NEXT:    ldd #0
; O3-NEXT:    subd ,s++
; O3-NEXT:    leax d,x
; O3-NEXT:    leas 2,s
; O3-NEXT:    rts
entry:
  %sub = sub i16 %a, %b
  %sub1 = sub i16 %sub, %c
  %sub2 = sub i16 %sub1, %d
  %sub3 = sub i16 %sub2, %e
  ret i16 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i16 @sub_u_i16_consts(i16 noundef %a, i16 noundef %b, i16 noundef %c, i16 noundef %d, i16 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i16_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -16,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 22,u
; CHECK-NEXT:    std 14,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 24,u
; CHECK-NEXT:    std 12,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 26,u
; CHECK-NEXT:    std 10,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 12,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    ldd 10,u
; CHECK-NEXT:    leax d,x
; CHECK-NEXT:    tfr x,d
; CHECK-NEXT:    subd #8447
; CHECK-NEXT:    coma
; CHECK-NEXT:    comb
; CHECK-NEXT:    addd #1
; CHECK-NEXT:    tfr d,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 16,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i16_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subd #8447
; CHECK-HD6309-NEXT:    negd
; CHECK-HD6309-NEXT:    subd 2,s
; CHECK-HD6309-NEXT:    subd 4,s
; CHECK-HD6309-NEXT:    subd 6,s
; CHECK-HD6309-NEXT:    subd 8,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i16_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    subd #8447
; O0-NEXT:    coma
; O0-NEXT:    comb
; O0-NEXT:    addd #1
; O0-NEXT:    subd 4,s
; O0-NEXT:    subd 6,s
; O0-NEXT:    subd 8,s
; O0-NEXT:    subd 10,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i16_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -16,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 22,u
; O1-NEXT:    std 14,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 24,u
; O1-NEXT:    std 12,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 26,u
; O1-NEXT:    std 10,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 14,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 12,u
; O1-NEXT:    leax d,x
; O1-NEXT:    ldd 10,u
; O1-NEXT:    leax d,x
; O1-NEXT:    tfr x,d
; O1-NEXT:    subd #8447
; O1-NEXT:    coma
; O1-NEXT:    comb
; O1-NEXT:    addd #1
; O1-NEXT:    tfr d,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 16,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i16_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std 14,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 24,u
; O2-NEXT:    std 12,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 26,u
; O2-NEXT:    std 10,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 14,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 12,u
; O2-NEXT:    leax d,x
; O2-NEXT:    ldd 10,u
; O2-NEXT:    leax d,x
; O2-NEXT:    tfr x,d
; O2-NEXT:    subd #8447
; O2-NEXT:    coma
; O2-NEXT:    comb
; O2-NEXT:    addd #1
; O2-NEXT:    tfr d,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 16,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i16_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -16,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 22,u
; O3-NEXT:    std 14,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 24,u
; O3-NEXT:    std 12,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 26,u
; O3-NEXT:    std 10,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 14,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 12,u
; O3-NEXT:    leax d,x
; O3-NEXT:    ldd 10,u
; O3-NEXT:    leax d,x
; O3-NEXT:    tfr x,d
; O3-NEXT:    subd #8447
; O3-NEXT:    coma
; O3-NEXT:    comb
; O3-NEXT:    addd #1
; O3-NEXT:    tfr d,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 16,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i16 8447, %a
  %sub3 = sub i16 %sub2, %b
  %sub4 = sub i16 %sub3, %c
  %sub5 = sub i16 %sub4, %d
  %sub6 = sub i16 %sub5, %e
  ret i16 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 32,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 31,u
; CHECK-NEXT:    adca 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    subb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 5,u
; CHECK-NEXT:    sbca 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 18,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 17,u
; O0-NEXT:    sbca 16,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 22,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 21,u
; O0-NEXT:    sbca 20,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 26,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 25,u
; O0-NEXT:    sbca 24,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 30,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 29,u
; O0-NEXT:    sbca 28,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std 2,x
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std ,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std 2,u
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 24,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 23,u
; O1-NEXT:    adca 22,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 28,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 27,u
; O1-NEXT:    adca 26,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 32,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 31,u
; O1-NEXT:    adca 30,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 2,u
; O1-NEXT:    subb 7,u
; O1-NEXT:    sbca 6,u
; O1-NEXT:    std 2,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    sbcb 5,u
; O1-NEXT:    sbca 4,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 2,u
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std 2,u
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 24,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 23,u
; O2-NEXT:    adca 22,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 28,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 27,u
; O2-NEXT:    adca 26,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 32,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 31,u
; O2-NEXT:    adca 30,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 2,u
; O2-NEXT:    subb 7,u
; O2-NEXT:    sbca 6,u
; O2-NEXT:    std 2,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    sbcb 5,u
; O2-NEXT:    sbca 4,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 2,u
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std 2,u
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 24,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 23,u
; O3-NEXT:    adca 22,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 28,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 27,u
; O3-NEXT:    adca 26,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 32,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 31,u
; O3-NEXT:    adca 30,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 2,u
; O3-NEXT:    subb 7,u
; O3-NEXT:    sbca 6,u
; O3-NEXT:    std 2,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    sbcb 5,u
; O3-NEXT:    sbca 4,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 2,u
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %sub = sub nsw i32 %a, %b
  %sub1 = sub nsw i32 %sub, %c
  %sub2 = sub nsw i32 %sub1, %d
  %sub3 = sub nsw i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_s_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_s_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -11,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 21,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 20,u
; CHECK-NEXT:    adca 19,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 25,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 24,u
; CHECK-NEXT:    adca 23,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 29,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 28,u
; CHECK-NEXT:    adca 27,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 33,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 32,u
; CHECK-NEXT:    adca 31,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #-21923
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    subb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; CHECK-NEXT:    sta 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldd #8
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 11,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_s_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #43613
; CHECK-HD6309-NEXT:    sbcd #8
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_s_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd #-21923
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 14,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd #8
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 13,u
; O0-NEXT:    sbca 12,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 18,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 17,u
; O0-NEXT:    sbca 16,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 22,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 21,u
; O0-NEXT:    sbca 20,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 26,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 25,u
; O0-NEXT:    sbca 24,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 30,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 29,u
; O0-NEXT:    sbca 28,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std 2,x
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std ,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_s_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -11,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 17,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 15,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 21,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 20,u
; O1-NEXT:    adca 19,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 25,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 24,u
; O1-NEXT:    adca 23,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 29,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 28,u
; O1-NEXT:    adca 27,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 33,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 32,u
; O1-NEXT:    adca 31,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd #-21923
; O1-NEXT:    std 4,u
; O1-NEXT:    subb 9,u
; O1-NEXT:    sbca 8,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O1-NEXT:    sta 10,u ; 1-byte Folded Spill
; O1-NEXT:    ldd #8
; O1-NEXT:    std 8,u
; O1-NEXT:    lda 10,u ; 1-byte Folded Reload
; O1-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O1-NEXT:    ldd 8,u
; O1-NEXT:    sbcb 7,u
; O1-NEXT:    sbca 6,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 11,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_s_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -11,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 17,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 15,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 21,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 20,u
; O2-NEXT:    adca 19,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 25,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 24,u
; O2-NEXT:    adca 23,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 29,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 28,u
; O2-NEXT:    adca 27,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 33,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 32,u
; O2-NEXT:    adca 31,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd #-21923
; O2-NEXT:    std 4,u
; O2-NEXT:    subb 9,u
; O2-NEXT:    sbca 8,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O2-NEXT:    sta 10,u ; 1-byte Folded Spill
; O2-NEXT:    ldd #8
; O2-NEXT:    std 8,u
; O2-NEXT:    lda 10,u ; 1-byte Folded Reload
; O2-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O2-NEXT:    ldd 8,u
; O2-NEXT:    sbcb 7,u
; O2-NEXT:    sbca 6,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 11,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_s_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -11,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 17,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 15,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 21,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 20,u
; O3-NEXT:    adca 19,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 25,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 24,u
; O3-NEXT:    adca 23,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 29,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 28,u
; O3-NEXT:    adca 27,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 33,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 32,u
; O3-NEXT:    adca 31,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd #-21923
; O3-NEXT:    std 4,u
; O3-NEXT:    subb 9,u
; O3-NEXT:    sbca 8,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O3-NEXT:    sta 10,u ; 1-byte Folded Spill
; O3-NEXT:    ldd #8
; O3-NEXT:    std 8,u
; O3-NEXT:    lda 10,u ; 1-byte Folded Reload
; O3-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O3-NEXT:    ldd 8,u
; O3-NEXT:    sbcb 7,u
; O3-NEXT:    sbca 6,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 11,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i32 567901, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -10,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 16,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 14,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 20,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 18,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 24,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 23,u
; CHECK-NEXT:    adca 22,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 28,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 27,u
; CHECK-NEXT:    adca 26,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    addd 32,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    adcb 31,u
; CHECK-NEXT:    adca 30,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    subb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 2,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 5,u
; CHECK-NEXT:    sbca 4,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 2,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 10,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i32:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 18,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 17,u
; O0-NEXT:    sbca 16,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 22,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 21,u
; O0-NEXT:    sbca 20,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 26,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 25,u
; O0-NEXT:    sbca 24,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 30,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 29,u
; O0-NEXT:    sbca 28,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std 2,x
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std ,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i32:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -10,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 16,u
; O1-NEXT:    std 2,u
; O1-NEXT:    ldd 14,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 20,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 18,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 24,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 23,u
; O1-NEXT:    adca 22,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 28,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 27,u
; O1-NEXT:    adca 26,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    addd 32,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    adcb 31,u
; O1-NEXT:    adca 30,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ldd 2,u
; O1-NEXT:    subb 7,u
; O1-NEXT:    sbca 6,u
; O1-NEXT:    std 2,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    sbcb 5,u
; O1-NEXT:    sbca 4,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 2,u
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 10,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i32:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std 2,u
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 24,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 23,u
; O2-NEXT:    adca 22,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 28,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 27,u
; O2-NEXT:    adca 26,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    addd 32,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    adcb 31,u
; O2-NEXT:    adca 30,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ldd 2,u
; O2-NEXT:    subb 7,u
; O2-NEXT:    sbca 6,u
; O2-NEXT:    std 2,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    sbcb 5,u
; O2-NEXT:    sbca 4,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 2,u
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i32:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -10,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 16,u
; O3-NEXT:    std 2,u
; O3-NEXT:    ldd 14,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 20,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 18,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 24,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 23,u
; O3-NEXT:    adca 22,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 28,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 27,u
; O3-NEXT:    adca 26,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    addd 32,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    adcb 31,u
; O3-NEXT:    adca 30,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ldd 2,u
; O3-NEXT:    subb 7,u
; O3-NEXT:    sbca 6,u
; O3-NEXT:    std 2,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    sbcb 5,u
; O3-NEXT:    sbca 4,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 2,u
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 10,s
; O3-NEXT:    rts
entry:
  %sub = sub i32 %a, %b
  %sub1 = sub i32 %sub, %c
  %sub2 = sub i32 %sub1, %d
  %sub3 = sub i32 %sub2, %e
  ret i32 %sub3
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local i32 @sub_u_i32_consts(i32 noundef %a, i32 noundef %b, i32 noundef %c, i32 noundef %d, i32 noundef %e) local_unnamed_addr #0 {
; CHECK-LABEL: sub_u_i32_consts:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -11,s
; CHECK-NEXT:    pshs u
; CHECK-NEXT:    tfr s,u
; CHECK-NEXT:    ldd 17,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 15,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 21,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 20,u
; CHECK-NEXT:    adca 19,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 25,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 24,u
; CHECK-NEXT:    adca 23,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 29,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 28,u
; CHECK-NEXT:    adca 27,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    addd 33,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 6,u
; CHECK-NEXT:    adcb 32,u
; CHECK-NEXT:    adca 31,u
; CHECK-NEXT:    std 6,u
; CHECK-NEXT:    ldd #-2081
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    subb 9,u
; CHECK-NEXT:    sbca 8,u
; CHECK-NEXT:    std 4,u
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; CHECK-NEXT:    sta 10,u ; 1-byte Folded Spill
; CHECK-NEXT:    ldd #126
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    lda 10,u ; 1-byte Folded Reload
; CHECK-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    sbcb 7,u
; CHECK-NEXT:    sbca 6,u
; CHECK-NEXT:    std 8,u
; CHECK-NEXT:    ldd 4,u
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd 8,u
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    tfr u,s
; CHECK-NEXT:    puls u
; CHECK-NEXT:    leas 11,s
; CHECK-NEXT:    rts
; CHECK-HD6309-LABEL: sub_u_i32_consts:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    subw #63455
; CHECK-HD6309-NEXT:    sbcd #126
; CHECK-HD6309-NEXT:    comd
; CHECK-HD6309-NEXT:    comw
; CHECK-HD6309-NEXT:    adcr 0,w
; CHECK-HD6309-NEXT:    adcr 0,d
; CHECK-HD6309-NEXT:    subw 4,s
; CHECK-HD6309-NEXT:    sbcd 2,s
; CHECK-HD6309-NEXT:    subw 8,s
; CHECK-HD6309-NEXT:    sbcd 6,s
; CHECK-HD6309-NEXT:    subw 12,s
; CHECK-HD6309-NEXT:    sbcd 10,s
; CHECK-HD6309-NEXT:    subw 16,s
; CHECK-HD6309-NEXT:    sbcd 14,s
; CHECK-HD6309-NEXT:    stq ,s
; CHECK-HD6309-NEXT:    rts
; O0-LABEL: sub_u_i32_consts:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs u
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd #-2081
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 14,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd #126
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 13,u
; O0-NEXT:    sbca 12,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 18,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 17,u
; O0-NEXT:    sbca 16,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 22,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 21,u
; O0-NEXT:    sbca 20,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 26,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 25,u
; O0-NEXT:    sbca 24,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    subd 30,u
; O0-NEXT:    std 4,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    ldd 6,u
; O0-NEXT:    sbcb 29,u
; O0-NEXT:    sbca 28,u
; O0-NEXT:    std 6,u
; O0-NEXT:    ldd 4,u
; O0-NEXT:    std 2,x
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std ,x
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_u_i32_consts:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    leas -11,s
; O1-NEXT:    pshs u
; O1-NEXT:    tfr s,u
; O1-NEXT:    ldd 17,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 15,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 21,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 20,u
; O1-NEXT:    adca 19,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 25,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 24,u
; O1-NEXT:    adca 23,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 29,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 28,u
; O1-NEXT:    adca 27,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd 8,u
; O1-NEXT:    addd 33,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 6,u
; O1-NEXT:    adcb 32,u
; O1-NEXT:    adca 31,u
; O1-NEXT:    std 6,u
; O1-NEXT:    ldd #-2081
; O1-NEXT:    std 4,u
; O1-NEXT:    subb 9,u
; O1-NEXT:    sbca 8,u
; O1-NEXT:    std 4,u
; O1-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O1-NEXT:    sta 10,u ; 1-byte Folded Spill
; O1-NEXT:    ldd #126
; O1-NEXT:    std 8,u
; O1-NEXT:    lda 10,u ; 1-byte Folded Reload
; O1-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O1-NEXT:    ldd 8,u
; O1-NEXT:    sbcb 7,u
; O1-NEXT:    sbca 6,u
; O1-NEXT:    std 8,u
; O1-NEXT:    ldd 4,u
; O1-NEXT:    std 2,x
; O1-NEXT:    ldd 8,u
; O1-NEXT:    std ,x
; O1-NEXT:    tfr u,s
; O1-NEXT:    puls u
; O1-NEXT:    leas 11,s
; O1-NEXT:    rts
;
; O2-LABEL: sub_u_i32_consts:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    leas -11,s
; O2-NEXT:    pshs u
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 17,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 15,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 21,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 20,u
; O2-NEXT:    adca 19,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 25,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 24,u
; O2-NEXT:    adca 23,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 29,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 28,u
; O2-NEXT:    adca 27,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd 8,u
; O2-NEXT:    addd 33,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 6,u
; O2-NEXT:    adcb 32,u
; O2-NEXT:    adca 31,u
; O2-NEXT:    std 6,u
; O2-NEXT:    ldd #-2081
; O2-NEXT:    std 4,u
; O2-NEXT:    subb 9,u
; O2-NEXT:    sbca 8,u
; O2-NEXT:    std 4,u
; O2-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O2-NEXT:    sta 10,u ; 1-byte Folded Spill
; O2-NEXT:    ldd #126
; O2-NEXT:    std 8,u
; O2-NEXT:    lda 10,u ; 1-byte Folded Reload
; O2-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O2-NEXT:    ldd 8,u
; O2-NEXT:    sbcb 7,u
; O2-NEXT:    sbca 6,u
; O2-NEXT:    std 8,u
; O2-NEXT:    ldd 4,u
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd 8,u
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u
; O2-NEXT:    leas 11,s
; O2-NEXT:    rts
;
; O3-LABEL: sub_u_i32_consts:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    leas -11,s
; O3-NEXT:    pshs u
; O3-NEXT:    tfr s,u
; O3-NEXT:    ldd 17,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 15,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 21,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 20,u
; O3-NEXT:    adca 19,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 25,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 24,u
; O3-NEXT:    adca 23,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 29,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 28,u
; O3-NEXT:    adca 27,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd 8,u
; O3-NEXT:    addd 33,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 6,u
; O3-NEXT:    adcb 32,u
; O3-NEXT:    adca 31,u
; O3-NEXT:    std 6,u
; O3-NEXT:    ldd #-2081
; O3-NEXT:    std 4,u
; O3-NEXT:    subb 9,u
; O3-NEXT:    sbca 8,u
; O3-NEXT:    std 4,u
; O3-NEXT:    ; kill: def $aalsb killed $aalsb def $aa
; O3-NEXT:    sta 10,u ; 1-byte Folded Spill
; O3-NEXT:    ldd #126
; O3-NEXT:    std 8,u
; O3-NEXT:    lda 10,u ; 1-byte Folded Reload
; O3-NEXT:    ; kill: def $aalsb killed $aalsb killed $aa
; O3-NEXT:    ldd 8,u
; O3-NEXT:    sbcb 7,u
; O3-NEXT:    sbca 6,u
; O3-NEXT:    std 8,u
; O3-NEXT:    ldd 4,u
; O3-NEXT:    std 2,x
; O3-NEXT:    ldd 8,u
; O3-NEXT:    std ,x
; O3-NEXT:    tfr u,s
; O3-NEXT:    puls u
; O3-NEXT:    leas 11,s
; O3-NEXT:    rts
entry:
  %sub2 = sub i32 8320991, %a
  %sub3 = sub i32 %sub2, %b
  %sub4 = sub i32 %sub3, %c
  %sub5 = sub i32 %sub4, %d
  %sub6 = sub i32 %sub5, %e
  ret i32 %sub6
}
