; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 < %s | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 < %s | FileCheck %s --check-prefixes=O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 < %s | FileCheck %s --check-prefixes=O2
; RUN: llc -global-isel -global-isel-abort=1 -O3 -mtriple=mc6809 < %s | FileCheck %s --check-prefixes=O3
;
; Bug #92 regression test.
;
; The 8-bit `SubSetCarryUse_i8_Imm` (and symmetric AddSetCarryUse_i8_Imm)
; expansion used to skip emitting the sbca/adca instruction when the
; immediate was the identity value (0), on the assumption that `A - 0`
; is a no-op. But for the USE-variant the borrow-in (CC.C) is part of
; the computation: `A - 0 - borrow` is NOT the same as `A`. Dropping
; the instruction silently lost the borrow propagation from the low
; byte's subtract.
;
; Exposed by picolibc's `test_memcmp("Hello", "Help!", 5)` at -O1+:
; returned 0x00FC instead of the correct 0xFFFC. The IR is
; `sub i16 (zext i8), (zext i8)`, which byte-decomposes into a low-
; byte SUBB (sets borrow) and a high-byte SBCA of 0 from 0 (with
; borrow-in). Skipping the SBCA dropped the sign-extension and
; produced the positive value.
;
; Fix: use INT32_MIN as IdentityValue for the SubSetCarryUse /
; AddSetCarryUse expand paths so the skip never triggers. Same
; pattern as the pre-existing fix for SubSetCarry / AddSetCarry
; (bug #53).
;
; The asm must contain an `sbca` instruction for the high byte.

target triple = "mc6809-unknown-unknown"

; At -O0 the high-byte 0 operand lives in a stack slot.
; At -O1+ it's a constant immediate (`sbca #0`). Either must appear.
; Bug #186 v5 (2026-04-27): stack-relative reference may use $u or $s
; depending on whether a frame pointer is allocated for the function;
; the relative-base register is not material to the borrow chain.
; CHECK-LABEL: sub_zext_i8:
; CHECK:      subb {{[0-9]+,[us]}}
; CHECK:      sbca {{#0|[0-9]+,[us]}}
define i16 @sub_zext_i8(i8 %a, i8 %b) {
; O0-LABEL: sub_zext_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    clra
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,s
; O0-NEXT:    clra
; O0-NEXT:    std <__rs1
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    subb 4,s
; O0-NEXT:    sbca ,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: sub_zext_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    subb 2,s
; O1-NEXT:    lda #0
; O1-NEXT:    sbca #0
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: sub_zext_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    subb 2,s
; O2-NEXT:    lda #0
; O2-NEXT:    sbca #0
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: sub_zext_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    subb 2,s
; O3-NEXT:    lda #0
; O3-NEXT:    sbca #0
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %conv_a = zext i8 %a to i16
  %conv_b = zext i8 %b to i16
  %sub = sub nsw i16 %conv_a, %conv_b
  ret i16 %sub
}

; Symmetric check for the add path: `add i16 (zext i8), (zext i8)`
; decomposes to ADDB + ADCA. With bug #92 the ADCA of zero was
; skipped, silently dropping the carry propagation.
; CHECK-LABEL: add_zext_i8:
; CHECK:      addb
; CHECK:      adca {{#0|[0-9]+,[us]}}
define i16 @add_zext_i8(i8 %a, i8 %b) {
; O0-LABEL: add_zext_i8:
; O0:       ; %bb.0: ; %entry
; O0-NEXT:    leas -2,s
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    clra
; O0-NEXT:    std <__rs0
; O0-NEXT:    ldb 4,s
; O0-NEXT:    clra
; O0-NEXT:    std <__rs1
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    ldb <__rs1lo
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs1hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 1,s ; 1-byte Folded Reload
; O0-NEXT:    addb 4,s
; O0-NEXT:    adca ,s
; O0-NEXT:    tfr d,x
; O0-NEXT:    leas 2,s
; O0-NEXT:    rts
;
; O1-LABEL: add_zext_i8:
; O1:       ; %bb.0: ; %entry
; O1-NEXT:    addb 2,s
; O1-NEXT:    lda #0
; O1-NEXT:    adca #0
; O1-NEXT:    tfr d,x
; O1-NEXT:    rts
;
; O2-LABEL: add_zext_i8:
; O2:       ; %bb.0: ; %entry
; O2-NEXT:    addb 2,s
; O2-NEXT:    lda #0
; O2-NEXT:    adca #0
; O2-NEXT:    tfr d,x
; O2-NEXT:    rts
;
; O3-LABEL: add_zext_i8:
; O3:       ; %bb.0: ; %entry
; O3-NEXT:    addb 2,s
; O3-NEXT:    lda #0
; O3-NEXT:    adca #0
; O3-NEXT:    tfr d,x
; O3-NEXT:    rts
entry:
  %conv_a = zext i8 %a to i16
  %conv_b = zext i8 %b to i16
  %sum = add i16 %conv_a, %conv_b
  ret i16 %sum
}
