; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=MC6809-O0
; RUN: llc -global-isel -global-isel-abort=1 -O1 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=MC6809-O1
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=MC6809-O2

; Bug #165 phase B2 regression: pin the call-boundary instruction order
; for `tail call` IR.
;
; MC6809LateOptimization::tailJMP would fold a trailing LBSR/BSR + RTS
; pair into a single TailJump (LBRA expansion) IF the two were strictly
; adjacent at the end of the MBB. In current codegen the fold rarely
; fires because frame setup/teardown (push/pull U as the frame pointer)
; sits between the call and the RTS — see the per-O check lines below.
; That's a separate codegen-quality issue worth fixing later; what this
; test is for is to PIN the call-boundary order so that any future
; post-RA scheduler enablement (deferred Phase D of bug #165) cannot
; silently reorder instructions across the call. If the scheduler moves
; (or fails to move) anything near the LBSR, this test fails loudly
; instead of the regression hiding in a per-test cycle drift in the
; bench.

target triple = "mc6809"

declare i16 @callee(i16, i16)

; Simple tail call: caller -> callee with same arg shape, return value
; passed through. At -O1 / -O2 this should fold to a single `lbra`,
; not the unfolded `lbsr ... rts` pair.
define i16 @trampoline(i16 %x, i16 %y) {
; MC6809-O0-LABEL: trampoline:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    pshs u
; MC6809-O0-NEXT:    tfr s,u
; MC6809-O0-NEXT:    ldd 4,u
; MC6809-O0-NEXT:    leas -2,s
; MC6809-O0-NEXT:    std ,s
; MC6809-O0-NEXT:    lbsr callee
; MC6809-O0-NEXT:    leas 2,s
; MC6809-O0-NEXT:    tfr u,s
; MC6809-O0-NEXT:    puls u
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: trampoline:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    pshs u
; MC6809-O1-NEXT:    tfr s,u
; MC6809-O1-NEXT:    ldd 4,u
; MC6809-O1-NEXT:    leas -2,s
; MC6809-O1-NEXT:    std ,s
; MC6809-O1-NEXT:    lbsr callee
; MC6809-O1-NEXT:    leas 2,s
; MC6809-O1-NEXT:    tfr u,s
; MC6809-O1-NEXT:    puls u
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: trampoline:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    pshs u
; MC6809-O2-NEXT:    tfr s,u
; MC6809-O2-NEXT:    ldd 4,u
; MC6809-O2-NEXT:    leas -2,s
; MC6809-O2-NEXT:    std ,s
; MC6809-O2-NEXT:    lbsr callee
; MC6809-O2-NEXT:    leas 2,s
; MC6809-O2-NEXT:    tfr u,s
; MC6809-O2-NEXT:    puls u
; MC6809-O2-NEXT:    rts
entry:
  %r = tail call i16 @callee(i16 %x, i16 %y)
  ret i16 %r
}
