; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -global-isel -global-isel-abort=1 %s -o - | FileCheck %s --check-prefixes=MC6809-O0
; RUN: llc -O1 -global-isel -global-isel-abort=1 %s -o - | FileCheck %s --check-prefixes=MC6809-O1
; RUN: llc -O2 -global-isel -global-isel-abort=1 %s -o - | FileCheck %s --check-prefixes=MC6809-O2
; RUN: llc -O3 -global-isel -global-isel-abort=1 %s -o - | FileCheck %s --check-prefixes=MC6809-O3
; RUN: llc -O0 -global-isel -global-isel-abort=1 -mcpu hd6309 %s -o - | FileCheck %s --check-prefixes=HD6309
target triple = "mc6809"

define i8 @foo0(i8* nocapture noundef readonly %a, i8 noundef zeroext %b) #0 {
;
; MC6809-O0-LABEL: foo0:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    clra
; MC6809-O0-NEXT:    ldb d,x
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: foo0:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    clra
; MC6809-O1-NEXT:    ldb d,x
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: foo0:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    clra
; MC6809-O2-NEXT:    ldb d,x
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: foo0:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    clra
; MC6809-O3-NEXT:    ldb d,x
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: foo0:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    clra
; HD6309-NEXT:    ldb d,x
; HD6309-NEXT:    rts
entry:
  %idxprom = zext i8 %b to i16
  %arrayidx = getelementptr inbounds i8, i8* %a, i16 %idxprom
  %0 = load i8, i8* %arrayidx, align 1
  ret i8 %0
}

define i8 @foo1(i8* nocapture noundef readonly %a, i8 noundef signext %b) #0 {
;
; MC6809-O0-LABEL: foo1:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    sex
; MC6809-O0-NEXT:    ldb d,x
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: foo1:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    ldb b,x
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: foo1:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    ldb b,x
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: foo1:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    ldb b,x
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: foo1:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    sex
; HD6309-NEXT:    ldb d,x
; HD6309-NEXT:    rts
entry:
  %idxprom = sext i8 %b to i16
  %arrayidx = getelementptr inbounds i8, i8* %a, i16 %idxprom
  %0 = load i8, i8* %arrayidx, align 1
  ret i8 %0
}

define i8 @foo2(i8* nocapture noundef readonly %a) #0 {
;
; MC6809-O0-LABEL: foo2:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    ldb -5,x
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: foo2:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    ldb -5,x
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: foo2:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    ldb -5,x
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: foo2:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    ldb -5,x
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: foo2:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldb -5,x
; HD6309-NEXT:    rts
entry:
  %arrayidx = getelementptr inbounds i8, i8* %a, i16 -5
  %0 = load i8, i8* %arrayidx, align 1
  ret i8 %0
}
