; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --filetype=asm < %s | FileCheck %s -check-prefixes=CHECK
; RUN: llc -O1 --filetype=asm < %s | FileCheck %s -check-prefixes=CHECK
; RUN: llc -O2 --filetype=asm < %s | FileCheck %s -check-prefixes=CHECK
; RUN: llc -O3 --filetype=asm < %s | FileCheck %s -check-prefixes=CHECK
; RUN: llc -O0 --filetype=asm -mcpu hd6309 < %s | FileCheck %s -check-prefixes=CHECK-HD6309
target triple = "mc6809"

define i32 @foo() {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    leas -2,s
; CHECK-NEXT:    ldd #24910
; CHECK-NEXT:    std 2,x
; CHECK-NEXT:    ldd #188
; CHECK-NEXT:    std ,x
; CHECK-NEXT:    leas 2,s
; CHECK-NEXT:    rts
;
; CHECK-HD6309-LABEL: foo:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    leas -2,s
; CHECK-HD6309-NEXT:    ldq #12345678
; CHECK-HD6309-NEXT:    stq ,x
; CHECK-HD6309-NEXT:    leas 2,s
; CHECK-HD6309-NEXT:    rts
entry:
  ret i32 12345678
}
