; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -O0 --filetype=asm < %s | FileCheck %s -check-prefixes=CHECK
; RUN: llc -verify-machineinstrs -O0 --filetype=asm -mcpu hd6309 < %s | FileCheck %s -check-prefixes=CHECK-HD6309
target triple = "mc6809"

define i8 @foo(i8* %a) {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldb ,x
; CHECK-NEXT:    rts
;
; CHECK-HD6309-LABEL: foo:
; CHECK-HD6309:       ; %bb.0: ; %entry
; CHECK-HD6309-NEXT:    ldf ,x
; CHECK-HD6309-NEXT:    rts
entry:
  %0 = load i8, i8* %a, align 1
  ret i8 %0
}
