; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O0
; RUN: llc -O1 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O1
; RUN: llc -O2 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O2
; RUN: llc -O3 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O3
; RUN: llc -O0 --filetype=asm -mcpu hd6309 < %s | FileCheck %s -check-prefixes=HD6309
target triple = "mc6809"

define i8 @foo(i8* %a) {
;
; MC6809-O0-LABEL: foo:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    ldb ,x
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: foo:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    ldb ,x
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: foo:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    ldb ,x
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: foo:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    ldb ,x
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: foo:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    ldb ,x
; HD6309-NEXT:    rts
entry:
  %0 = load i8, i8* %a, align 1
  ret i8 %0
}
