; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O0
; RUN: llc -O1 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O1
; RUN: llc -O2 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O2
; RUN: llc -O3 --filetype=asm < %s | FileCheck %s -check-prefixes=MC6809-O3
; RUN: llc -O0 --filetype=asm -mcpu hd6309 < %s | FileCheck %s -check-prefixes=HD6309
target triple = "mc6809"

define i32 @foo() {
;
; MC6809-O0-LABEL: foo:
; MC6809-O0:       ; %bb.0: ; %entry
; MC6809-O0-NEXT:    leas -2,s
; MC6809-O0-NEXT:    ldd #24910
; MC6809-O0-NEXT:    std 2,x
; MC6809-O0-NEXT:    ldd #188
; MC6809-O0-NEXT:    std ,x
; MC6809-O0-NEXT:    leas 2,s
; MC6809-O0-NEXT:    rts
;
; MC6809-O1-LABEL: foo:
; MC6809-O1:       ; %bb.0: ; %entry
; MC6809-O1-NEXT:    ldd #24910
; MC6809-O1-NEXT:    std 2,x
; MC6809-O1-NEXT:    ldd #188
; MC6809-O1-NEXT:    std ,x
; MC6809-O1-NEXT:    rts
;
; MC6809-O2-LABEL: foo:
; MC6809-O2:       ; %bb.0: ; %entry
; MC6809-O2-NEXT:    ldd #24910
; MC6809-O2-NEXT:    std 2,x
; MC6809-O2-NEXT:    ldd #188
; MC6809-O2-NEXT:    std ,x
; MC6809-O2-NEXT:    rts
;
; MC6809-O3-LABEL: foo:
; MC6809-O3:       ; %bb.0: ; %entry
; MC6809-O3-NEXT:    ldd #24910
; MC6809-O3-NEXT:    std 2,x
; MC6809-O3-NEXT:    ldd #188
; MC6809-O3-NEXT:    std ,x
; MC6809-O3-NEXT:    rts
;
; HD6309-LABEL: foo:
; HD6309:       ; %bb.0: ; %entry
; HD6309-NEXT:    leas -10,s
; HD6309-NEXT:    pshs u
; HD6309-NEXT:    tfr s,u
; HD6309-NEXT:    ldq #12345678
; HD6309-NEXT:    std 6,u
; HD6309-NEXT:    tfr w,d
; HD6309-NEXT:    std 8,u
; HD6309-NEXT:    ldd 6,u
; HD6309-NEXT:    std 4,u
; HD6309-NEXT:    ldd 8,u
; HD6309-NEXT:    std 2,x
; HD6309-NEXT:    ldd 4,u
; HD6309-NEXT:    std ,x
; HD6309-NEXT:    tfr u,s
; HD6309-NEXT:    puls u
; HD6309-NEXT:    leas 10,s
; HD6309-NEXT:    rts
entry:
  ret i32 12345678
}
