; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mc6809 -O2 -filetype=asm --relocation-model=pic < %s | FileCheck --check-prefix=PIC %s
; RUN: llc -mtriple=mc6809 -mcpu=hd6309 -O2 -filetype=asm --relocation-model=pic < %s | FileCheck --check-prefix=PIC6309 %s
; RUN: llc -mtriple=mc6809 -O2 -filetype=obj --relocation-model=pic %s -o %t.pic.o
; RUN: llvm-readobj -r %t.pic.o | FileCheck --check-prefix=PIC-RELOC %s

; Under -fPIC/-fPIE, fold a G_GLOBAL_VALUE address directly into the
; load/store it feeds, using PC-relative addressing (LD?i_o16PC / ST?i_o16PC)
; instead of materialising it with LEAX label,pc and dereferencing via indexed
; addressing. This is done at instruction selection, so it folds the store (the
; #197 LEAX path only ever folded into the load, via a later peephole) AND the
; non-adjacent case where the stored value is materialised after the address.
; PC-relative addressing keeps the same R_MC6809_PCREL_16 relocation the LEAX
; form used, so position-independence is preserved. i8 is intentionally left to
; the post-RA peephole (its A/B accumulator choice is not known here) — see
; global-load-store.ll.

@g16 = external global i16
@gp  = external global ptr
@g32 = external global i32

define void @store16(i16 %v) {
; PIC-LABEL: store16:
; PIC:       ; %bb.0:
; PIC-NEXT:    tfr x,d
; PIC-NEXT:    std g16,pc
; PIC-NEXT:    rts
;
; PIC6309-LABEL: store16:
; PIC6309:       ; %bb.0:
; PIC6309-NEXT:    tfr x,d
; PIC6309-NEXT:    std g16,pc
; PIC6309-NEXT:    rts
  store i16 %v, ptr @g16
  ret void
}

define i16 @load16() {
; PIC-LABEL: load16:
; PIC:       ; %bb.0:
; PIC-NEXT:    ldd g16,pc
; PIC-NEXT:    tfr d,x
; PIC-NEXT:    rts
;
; PIC6309-LABEL: load16:
; PIC6309:       ; %bb.0:
; PIC6309-NEXT:    ldd g16,pc
; PIC6309-NEXT:    tfr d,x
; PIC6309-NEXT:    rts
  %v = load i16, ptr @g16
  ret i16 %v
}

define void @store_ptr(ptr %v) {
; PIC-LABEL: store_ptr:
; PIC:       ; %bb.0:
; PIC-NEXT:    stx gp,pc
; PIC-NEXT:    rts
;
; PIC6309-LABEL: store_ptr:
; PIC6309:       ; %bb.0:
; PIC6309-NEXT:    stx gp,pc
; PIC6309-NEXT:    rts
  store ptr %v, ptr @gp
  ret void
}

; Non-adjacent: the stored value (#5) is materialised after the address would
; have been; a post-RA peephole could not fold this, selection can.
define void @store16_const() {
; PIC-LABEL: store16_const:
; PIC:       ; %bb.0:
; PIC-NEXT:    ldd #5
; PIC-NEXT:    std g16,pc
; PIC-NEXT:    rts
;
; PIC6309-LABEL: store16_const:
; PIC6309:       ; %bb.0:
; PIC6309-NEXT:    ldd #5
; PIC6309-NEXT:    std g16,pc
; PIC6309-NEXT:    rts
  store i16 5, ptr @g16
  ret void
}

; HD6309 folds the 32-bit store/load into a single Q-register PC-relative op.
define void @store32(i32 %v) {
; PIC-LABEL: store32:
; PIC:       ; %bb.0:
; PIC-NEXT:    leas -2,s
; PIC-NEXT:    ldd 6,s
; PIC-NEXT:    pshs d
; PIC-NEXT:    ldd 6,s
; PIC-NEXT:    std <__rs0
; PIC-NEXT:    puls d
; PIC-NEXT:    leax g32,pc
; PIC-NEXT:    std 2,x
; PIC-NEXT:    pshs d
; PIC-NEXT:    ldd <__rs0
; PIC-NEXT:    std g32,pc
; PIC-NEXT:    puls d
; PIC-NEXT:    leas 2,s
; PIC-NEXT:    rts
;
; PIC6309-LABEL: store32:
; PIC6309:       ; %bb.0:
; PIC6309-NEXT:    ldq 2,s
; PIC6309-NEXT:    stq g32,pc
; PIC6309-NEXT:    rts
  store i32 %v, ptr @g32
  ret void
}

; The folded stores must keep the PC-relative relocation, never an absolute one.
; PIC-RELOC: R_MC6809_PCREL_16 g16
; PIC-RELOC: R_MC6809_PCREL_16 gp
; PIC-RELOC-NOT: R_MC6809_ADDR_16
