; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 regression sentry: i64 negation, including INT64_MIN.
; INT64_MIN (0x8000_0000_0000_0000) is its own negation under two's
; complement, so `0 - INT64_MIN == INT64_MIN`. If a future change
; mishandles the carry-out of bit 63 in the i64 SUB chain, the
; "neg_eq_self" test will return wrong-for-non-INT64_MIN inputs but
; this lit test only exercises shape — runtime semantics are checked
; in test/MC/MC6809/Execution/codegen-mul64 (and the new sext64).

target triple = "mc6809-unknown-unknown"

define i64 @neg_i64(i64 %x) {
; O0-LABEL: neg_i64:
; O0:       ; %bb.0:
; O0-NEXT:    leas -8,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 7,s ; 1-byte Folded Reload
; O0-NEXT:    subb 17,s
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 16,s
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 15,s
; O0-NEXT:    sta 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 2,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 14,s
; O0-NEXT:    stb 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 13,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    lda 3,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 11,s
; O0-NEXT:    sta 3,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 6,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 8,s
; O0-NEXT:    lda 4,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 7,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb 3,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 8,s
; O0-NEXT:    rts
;
; O2-LABEL: neg_i64:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    lda #0
; O2-NEXT:    tfr a,b
; O2-NEXT:    subb 15,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 14,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 13,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 11,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 10,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 9,s
; O2-NEXT:    sbca 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    lda 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = sub i64 0, %x
  ret i64 %r
}

define i64 @mul_neg1(i64 %x) {
; O0-LABEL: mul_neg1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #-1
; O0-NEXT:    std 14,s
; O0-NEXT:    std 12,s
; O0-NEXT:    std 10,s
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __muldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: mul_neg1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -6,s
; O2-NEXT:    lda #0
; O2-NEXT:    tfr a,b
; O2-NEXT:    subb 15,s
; O2-NEXT:    stb 5,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 14,s
; O2-NEXT:    stb 4,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 13,s
; O2-NEXT:    stb 3,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 12,s
; O2-NEXT:    stb 2,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 11,s
; O2-NEXT:    stb 1,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 10,s
; O2-NEXT:    stb ,s ; 1-byte Folded Spill
; O2-NEXT:    tfr a,b
; O2-NEXT:    sbcb 9,s
; O2-NEXT:    sbca 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 7,s
; O2-NEXT:    lda 6,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 5,s
; O2-NEXT:    lda 4,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldb 3,s
; O2-NEXT:    lda 2,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,x
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,x
; O2-NEXT:    puls d
; O2-NEXT:    std ,x
; O2-NEXT:    leas 6,s
; O2-NEXT:    rts
  %r = mul i64 %x, -1
  ret i64 %r
}

define i64 @double_neg(i64 %x) {
; O0-LABEL: double_neg:
; O0:       ; %bb.0:
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    tfr b,a
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 9,s ; 1-byte Folded Reload
; O0-NEXT:    subb 25,s
; O0-NEXT:    stb 9,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 10,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 24,s
; O0-NEXT:    stb 10,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 11,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 23,s
; O0-NEXT:    stb 11,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 12,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 22,s
; O0-NEXT:    stb 12,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 13,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 21,s
; O0-NEXT:    stb 13,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 15,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 20,s
; O0-NEXT:    stb 15,s ; 1-byte Folded Spill
; O0-NEXT:    sbca 19,s
; O0-NEXT:    sta 2,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 14,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 18,s
; O0-NEXT:    stb 14,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 7,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb ,s ; 1-byte Folded Spill
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    stb 4,s ; 1-byte Folded Spill
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    stb 1,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 8,s ; 1-byte Folded Reload
; O0-NEXT:    subb 9,s
; O0-NEXT:    stb 8,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 5,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 10,s
; O0-NEXT:    stb 5,s ; 1-byte Folded Spill
; O0-NEXT:    lda 7,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 11,s
; O0-NEXT:    sta 7,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 3,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 12,s
; O0-NEXT:    stb 3,s ; 1-byte Folded Spill
; O0-NEXT:    ldb 6,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 13,s
; O0-NEXT:    stb 6,s ; 1-byte Folded Spill
; O0-NEXT:    ldb ,s ; 1-byte Folded Reload
; O0-NEXT:    sbcb 15,s
; O0-NEXT:    lda 4,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 2,s
; O0-NEXT:    sta 4,s ; 1-byte Folded Spill
; O0-NEXT:    lda 1,s ; 1-byte Folded Reload
; O0-NEXT:    sbca 14,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 10,s
; O0-NEXT:    lda 7,s
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldb 9,s
; O0-NEXT:    lda 5,s
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    tfr b,a
; O0-NEXT:    ldb 8,s
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldb 4,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    std ,x
; O0-NEXT:    leas 16,s
; O0-NEXT:    rts
;
; O2-LABEL: double_neg:
; O2:       ; %bb.0:
; O2-NEXT:    ldd 8,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 8,s
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,s
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,s
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    rts
  %n = sub i64 0, %x
  %r = sub i64 0, %n
  ret i64 %r
}
