; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 regression sentry: i64 variable-count shifts. The shift
; count gets zero/sign-extended from i8/i16/i32 to i64 before the
; G_SHL/G_LSHR/G_ASHR — the legalizer routes those to libcall
; (__ashldi3/__lshrdi3/__ashrdi3) where the count is consumed in
; the low byte. If the extension chain is wrong, the libcall sees
; garbage in the high bytes and the count-mod-64 mask in the .S
; helper does the wrong thing.

target triple = "mc6809-unknown-unknown"

define i64 @shl_i64_by_i8(i64 %x, i8 %n) {
; O0-LABEL: shl_i64_by_i8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    lda #0
; O0-NEXT:    tfr d,d
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i64_by_i8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    clra
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %nn = zext i8 %n to i64
  %r = shl i64 %x, %nn
  ret i64 %r
}

define i64 @lshr_i64_by_i16(i64 %x, i16 %n) {
; O0-LABEL: lshr_i64_by_i16:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #255
; O0-NEXT:    andb 25,u
; O0-NEXT:    anda 24,u
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i64_by_i16:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd #255
; O2-NEXT:    andb 25,u
; O2-NEXT:    anda 24,u
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %nn = zext i16 %n to i64
  %r = lshr i64 %x, %nn
  ret i64 %r
}

define i64 @ashr_i64_by_i32(i64 %x, i32 %n) {
; O0-LABEL: ashr_i64_by_i32:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #255
; O0-NEXT:    andb 27,u
; O0-NEXT:    anda 26,u
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i64_by_i32:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd #255
; O2-NEXT:    andb 27,u
; O2-NEXT:    anda 26,u
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %nn = zext i32 %n to i64
  %r = ashr i64 %x, %nn
  ret i64 %r
}

define i64 @shl_i64_by_i32_sext(i64 %x, i32 %n) {
; O0-LABEL: shl_i64_by_i32_sext:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #255
; O0-NEXT:    andb 27,u
; O0-NEXT:    anda 26,u
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i64_by_i32_sext:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd #255
; O2-NEXT:    andb 27,u
; O2-NEXT:    anda 26,u
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %nn = sext i32 %n to i64
  %r = shl i64 %x, %nn
  ret i64 %r
}
