; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 regression sentry: i64 ICMP against a sign/zero-extended
; narrower operand. The widening MUST happen before the compare —
; if the legalizer narrows the i64 instead of widening the i8/i16/i32,
; the high bytes are silently dropped and the result depends only on
; the low end. G_ICMP for i64 is `Custom` in MC6809LegalizerInfo, so
; this exercises that path.

target triple = "mc6809-unknown-unknown"

define i1 @eq_i64_sext_i32(i64 %a, i32 %b) {
; O0-LABEL: eq_i64_sext_i32:
; O0:       ; %bb.0:
; O0-NEXT:    leas -5,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 13,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 11,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 21,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 19,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    ldb <__rs0lo
; O0-NEXT:    pshs a
; O0-NEXT:    lda <__rs0hi
; O0-NEXT:    tfr a,b
; O0-NEXT:    puls a
; O0-NEXT:    cmpb #0
; O0-NEXT:    lblt .LBB0_2
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    ldb #0
; O0-NEXT:    lbra .LBB0_3
; O0-NEXT:  .LBB0_2:
; O0-NEXT:    ldb #1
; O0-NEXT:  .LBB0_3:
; O0-NEXT:    andb #1
; O0-NEXT:    negb
; O0-NEXT:    stb 4,u ; 1-byte Folded Spill
; O0-NEXT:    leas -16,s
; O0-NEXT:    ldd 17,u
; O0-NEXT:    std 6,s
; O0-NEXT:    ldd 15,u
; O0-NEXT:    std 4,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 14,s
; O0-NEXT:    puls d
; O0-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O0-NEXT:    tfr b,a
; O0-NEXT:    std 10,s
; O0-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O0-NEXT:    tfr b,a
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 5,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ucmpdi2
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 16,s
; O0-NEXT:    cmpb #1
; O0-NEXT:    lbeq .LBB0_5
; O0-NEXT:  ; %bb.4:
; O0-NEXT:    ldb #0
; O0-NEXT:    lbra .LBB0_6
; O0-NEXT:  .LBB0_5:
; O0-NEXT:    ldb #1
; O0-NEXT:  .LBB0_6:
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 5,s
; O0-NEXT:    rts
;
; O2-LABEL: eq_i64_sext_i32:
; O2:       ; %bb.0:
; O2-NEXT:    leas -5,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 11,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd 21,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 19,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    cmpb #0
; O2-NEXT:    lblt .LBB0_2
; O2-NEXT:  ; %bb.1:
; O2-NEXT:    ldb #0
; O2-NEXT:    bra .LBB0_3
; O2-NEXT:  .LBB0_2:
; O2-NEXT:    ldb #1
; O2-NEXT:  .LBB0_3:
; O2-NEXT:    andb #1
; O2-NEXT:    negb
; O2-NEXT:    stb 4,u ; 1-byte Folded Spill
; O2-NEXT:    leas -16,s
; O2-NEXT:    ldd 17,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd 15,u
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd 13,u
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 12,s
; O2-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O2-NEXT:    tfr b,a
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 5,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ucmpdi2
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 16,s
; O2-NEXT:    cmpb #1
; O2-NEXT:    lbeq .LBB0_5
; O2-NEXT:  ; %bb.4:
; O2-NEXT:    ldb #0
; O2-NEXT:    bra .LBB0_6
; O2-NEXT:  .LBB0_5:
; O2-NEXT:    ldb #1
; O2-NEXT:  .LBB0_6:
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 5,s
; O2-NEXT:    rts
  %nn = sext i32 %b to i64
  %c = icmp eq i64 %a, %nn
  ret i1 %c
}

define i1 @ult_i64_zext_i16(i64 %a, i16 %b) {
; O0-LABEL: ult_i64_zext_i16:
; O0:       ; %bb.0:
; O0-NEXT:    leas -4,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    ldd 16,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 12,s
; O0-NEXT:    std 10,s
; O0-NEXT:    std 8,s
; O0-NEXT:    tfr x,d
; O0-NEXT:    std 14,s
; O0-NEXT:    leay 4,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ucmpdi2
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 16,s
; O0-NEXT:    cmpb #0
; O0-NEXT:    lbeq .LBB1_2
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    ldb #0
; O0-NEXT:    lbra .LBB1_3
; O0-NEXT:  .LBB1_2:
; O0-NEXT:    ldb #1
; O0-NEXT:  .LBB1_3:
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 4,s
; O0-NEXT:    rts
;
; O2-LABEL: ult_i64_zext_i16:
; O2:       ; %bb.0:
; O2-NEXT:    leas -4,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    ldd 16,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    stx 14,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 12,s
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 4,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ucmpdi2
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 16,s
; O2-NEXT:    cmpb #0
; O2-NEXT:    lbeq .LBB1_2
; O2-NEXT:  ; %bb.1:
; O2-NEXT:    ldb #0
; O2-NEXT:    bra .LBB1_3
; O2-NEXT:  .LBB1_2:
; O2-NEXT:    ldb #1
; O2-NEXT:  .LBB1_3:
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 4,s
; O2-NEXT:    rts
  %nn = zext i16 %b to i64
  %c = icmp ult i64 %a, %nn
  ret i1 %c
}

define i1 @sgt_i64_sext_i8(i64 %a, i8 %b) {
; O0-LABEL: sgt_i64_sext_i8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -5,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 17,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 15,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 13,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 11,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    cmpb #0
; O0-NEXT:    lblt .LBB2_2
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    lda #0
; O0-NEXT:    lbra .LBB2_3
; O0-NEXT:  .LBB2_2:
; O0-NEXT:    lda #1
; O0-NEXT:  .LBB2_3:
; O0-NEXT:    anda #1
; O0-NEXT:    nega
; O0-NEXT:    sta 4,u ; 1-byte Folded Spill
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    lda 4,u
; O0-NEXT:    std 14,s
; O0-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O0-NEXT:    tfr b,a
; O0-NEXT:    std 12,s
; O0-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O0-NEXT:    tfr b,a
; O0-NEXT:    std 10,s
; O0-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O0-NEXT:    tfr b,a
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 5,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __cmpdi2
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 16,s
; O0-NEXT:    cmpb #2
; O0-NEXT:    lbeq .LBB2_5
; O0-NEXT:  ; %bb.4:
; O0-NEXT:    ldb #0
; O0-NEXT:    lbra .LBB2_6
; O0-NEXT:  .LBB2_5:
; O0-NEXT:    ldb #1
; O0-NEXT:  .LBB2_6:
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 5,s
; O0-NEXT:    rts
;
; O2-LABEL: sgt_i64_sext_i8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -5,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 17,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 15,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 13,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 11,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    cmpb #0
; O2-NEXT:    lblt .LBB2_2
; O2-NEXT:  ; %bb.1:
; O2-NEXT:    lda #0
; O2-NEXT:    bra .LBB2_3
; O2-NEXT:  .LBB2_2:
; O2-NEXT:    lda #1
; O2-NEXT:  .LBB2_3:
; O2-NEXT:    anda #1
; O2-NEXT:    nega
; O2-NEXT:    sta 4,u ; 1-byte Folded Spill
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    lda 4,u
; O2-NEXT:    std 14,s
; O2-NEXT:    ldb 4,u ; 1-byte Folded Reload
; O2-NEXT:    tfr b,a
; O2-NEXT:    std 12,s
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 5,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __cmpdi2
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 16,s
; O2-NEXT:    cmpb #2
; O2-NEXT:    lbeq .LBB2_5
; O2-NEXT:  ; %bb.4:
; O2-NEXT:    ldb #0
; O2-NEXT:    bra .LBB2_6
; O2-NEXT:  .LBB2_5:
; O2-NEXT:    ldb #1
; O2-NEXT:  .LBB2_6:
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 5,s
; O2-NEXT:    rts
  %nn = sext i8 %b to i64
  %c = icmp sgt i64 %a, %nn
  ret i1 %c
}

define i1 @ne_i64_zext_i8(i64 %a, i8 %b) {
; O0-LABEL: ne_i64_zext_i8:
; O0:       ; %bb.0:
; O0-NEXT:    leas -4,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 14,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 12,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 10,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    lda #0
; O0-NEXT:    tfr d,d
; O0-NEXT:    leas -16,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #0
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 14,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 14,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 12,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 10,s
; O0-NEXT:    puls d
; O0-NEXT:    leay 4,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ucmpdi2
; O0-NEXT:    ldd 2,y
; O0-NEXT:    leas 16,s
; O0-NEXT:    cmpb #1
; O0-NEXT:    lbne .LBB3_2
; O0-NEXT:  ; %bb.1:
; O0-NEXT:    ldb #0
; O0-NEXT:    lbra .LBB3_3
; O0-NEXT:  .LBB3_2:
; O0-NEXT:    ldb #1
; O0-NEXT:  .LBB3_3:
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 4,s
; O0-NEXT:    rts
;
; O2-LABEL: ne_i64_zext_i8:
; O2:       ; %bb.0:
; O2-NEXT:    leas -4,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    clra
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 12,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 10,u
; O2-NEXT:    std <__rs3
; O2-NEXT:    puls d
; O2-NEXT:    leas -16,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs3
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 14,s
; O2-NEXT:    ldd #0
; O2-NEXT:    std 12,s
; O2-NEXT:    std 10,s
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 4,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ucmpdi2
; O2-NEXT:    ldd 2,y
; O2-NEXT:    leas 16,s
; O2-NEXT:    cmpb #1
; O2-NEXT:    lbne .LBB3_2
; O2-NEXT:  ; %bb.1:
; O2-NEXT:    ldb #0
; O2-NEXT:    bra .LBB3_3
; O2-NEXT:  .LBB3_2:
; O2-NEXT:    ldb #1
; O2-NEXT:  .LBB3_3:
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 4,s
; O2-NEXT:    rts
  %nn = zext i8 %b to i64
  %c = icmp ne i64 %a, %nn
  ret i1 %c
}
