; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -global-isel-abort=1 -O0 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O0
; RUN: llc -global-isel -global-isel-abort=1 -O2 -mtriple=mc6809 -mattr=-static-stack %s -o - | FileCheck %s --check-prefixes=O2

; Bug #72 regression sentry: i64 division/shift by power-of-2.
; Today these go via the libcall (__divdi3/__udivdi3 or __ashrdi3/
; __lshrdi3 if the front-end already strength-reduced). Recording
; current behaviour as a baseline so a future strength-reduction
; pass shows up as a delta. NB: signed sdiv-by-2 is NOT the same
; as ashr-by-1 for negative operands (round-to-zero vs round-to-
; -inf), so they're checked separately.

target triple = "mc6809-unknown-unknown"

define i64 @sdiv_i64_2(i64 %x) {
; O0-LABEL: sdiv_i64_2:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #2
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    std 12,s
; O0-NEXT:    std 10,s
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __divdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: sdiv_i64_2:
; O2:       ; %bb.0:
; O2-NEXT:    leas -34,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 46,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldd 44,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 42,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    ldd 40,u
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 8,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 6,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #63
; O2-NEXT:    std 12,u ; 2-byte Folded Spill
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 14,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 14,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    leas -10,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd 12,u ; 2-byte Folded Reload
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 22,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    std <__rs3
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldd 40,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    ldb <__rs2lo
; O2-NEXT:    stb 12,u ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs2hi
; O2-NEXT:    tfr a,b
; O2-NEXT:    stb 11,u ; 1-byte Folded Spill
; O2-NEXT:    ldb <__rs3lo
; O2-NEXT:    lda <__rs3hi
; O2-NEXT:    sta 9,u ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs0lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 10,u ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs0hi
; O2-NEXT:    sta 8,u ; 1-byte Folded Spill
; O2-NEXT:    pshs b
; O2-NEXT:    ldb <__rs1lo
; O2-NEXT:    tfr b,a
; O2-NEXT:    puls b
; O2-NEXT:    sta 6,u ; 1-byte Folded Spill
; O2-NEXT:    lda <__rs1hi
; O2-NEXT:    sta 7,u ; 1-byte Folded Spill
; O2-NEXT:    addb 47,u
; O2-NEXT:    tfr b,a
; O2-NEXT:    ldb 9,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 46,u
; O2-NEXT:    stb 9,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 10,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 45,u
; O2-NEXT:    stb 10,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 8,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 44,u
; O2-NEXT:    stb 8,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 6,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 43,u
; O2-NEXT:    stb 6,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 7,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 42,u
; O2-NEXT:    stb 7,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 12,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 23,u
; O2-NEXT:    stb 12,u ; 1-byte Folded Spill
; O2-NEXT:    ldb 11,u ; 1-byte Folded Reload
; O2-NEXT:    adcb 22,u
; O2-NEXT:    stb 11,u ; 1-byte Folded Spill
; O2-NEXT:    leas -10,s
; O2-NEXT:    tfr a,b
; O2-NEXT:    lda 9,u
; O2-NEXT:    std 6,s
; O2-NEXT:    ldb 10,u
; O2-NEXT:    lda 8,u
; O2-NEXT:    std 4,s
; O2-NEXT:    ldb 6,u
; O2-NEXT:    lda 7,u
; O2-NEXT:    std 2,s
; O2-NEXT:    ldb 12,u
; O2-NEXT:    lda 11,u
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 30,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 30,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 34,s
; O2-NEXT:    rts
  %r = sdiv i64 %x, 2
  ret i64 %r
}

define i64 @udiv_i64_4(i64 %x) {
; O0-LABEL: udiv_i64_4:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    ldd 22,u
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas -16,s
; O0-NEXT:    std 6,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd #4
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    ldd #0
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 16,s
; O0-NEXT:    puls d
; O0-NEXT:    std 12,s
; O0-NEXT:    std 10,s
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __udivdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 16,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: udiv_i64_4:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -10,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd #2
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %r = udiv i64 %x, 4
  ret i64 %r
}

define i64 @ashr_i64_1(i64 %x) {
; O0-LABEL: ashr_i64_1:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #1
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashrdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: ashr_i64_1:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -10,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #1
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %r = ashr i64 %x, 1
  ret i64 %r
}

define i64 @lshr_i64_2(i64 %x) {
; O0-LABEL: lshr_i64_2:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #2
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __lshrdi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: lshr_i64_2:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -10,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd #2
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 4,s
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std 2,s
; O2-NEXT:    puls d
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __lshrdi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %r = lshr i64 %x, 2
  ret i64 %r
}

define i64 @shl_i64_3(i64 %x) {
; O0-LABEL: shl_i64_3:
; O0:       ; %bb.0:
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs u,y
; O0-NEXT:    tfr s,u
; O0-NEXT:    stx 4,u ; 2-byte Folded Spill
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 22,u
; O0-NEXT:    std <__rs3
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 20,u
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 18,u
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 16,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    ldd #3
; O0-NEXT:    andb #255
; O0-NEXT:    clra
; O0-NEXT:    leas -10,s
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs3
; O0-NEXT:    std 8,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 6,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 4,s
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std 2,s
; O0-NEXT:    puls d
; O0-NEXT:    std 8,s
; O0-NEXT:    leay 6,u
; O0-NEXT:    tfr y,x
; O0-NEXT:    lbsr __ashldi3
; O0-NEXT:    ldd 6,y
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 4,y
; O0-NEXT:    std <__rs0
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 2,y
; O0-NEXT:    std <__rs1
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd 6,u
; O0-NEXT:    std <__rs2
; O0-NEXT:    puls d
; O0-NEXT:    leas 10,s
; O0-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O0-NEXT:    std 6,x
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs0
; O0-NEXT:    std 4,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs1
; O0-NEXT:    std 2,x
; O0-NEXT:    puls d
; O0-NEXT:    pshs d
; O0-NEXT:    ldd <__rs2
; O0-NEXT:    std ,x
; O0-NEXT:    puls d
; O0-NEXT:    tfr u,s
; O0-NEXT:    puls u,y
; O0-NEXT:    leas 10,s
; O0-NEXT:    rts
;
; O2-LABEL: shl_i64_3:
; O2:       ; %bb.0:
; O2-NEXT:    leas -10,s
; O2-NEXT:    pshs u,y
; O2-NEXT:    tfr s,u
; O2-NEXT:    stx 4,u ; 2-byte Folded Spill
; O2-NEXT:    ldd 22,u
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 20,u
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 18,u
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 16,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas -10,s
; O2-NEXT:    std 6,s
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,s
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,s
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,s
; O2-NEXT:    ldd #3
; O2-NEXT:    std 8,s
; O2-NEXT:    leay 6,u
; O2-NEXT:    tfr y,x
; O2-NEXT:    lbsr __ashldi3
; O2-NEXT:    ldd 6,y
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 4,y
; O2-NEXT:    std <__rs0
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 2,y
; O2-NEXT:    std <__rs1
; O2-NEXT:    puls d
; O2-NEXT:    pshs d
; O2-NEXT:    ldd 6,u
; O2-NEXT:    std <__rs2
; O2-NEXT:    puls d
; O2-NEXT:    leas 10,s
; O2-NEXT:    ldx 4,u ; 2-byte Folded Reload
; O2-NEXT:    std 6,x
; O2-NEXT:    ldd <__rs0
; O2-NEXT:    std 4,x
; O2-NEXT:    ldd <__rs1
; O2-NEXT:    std 2,x
; O2-NEXT:    ldd <__rs2
; O2-NEXT:    std ,x
; O2-NEXT:    tfr u,s
; O2-NEXT:    puls u,y
; O2-NEXT:    leas 10,s
; O2-NEXT:    rts
  %r = shl i64 %x, 3
  ret i64 %r
}
