; 6809 assembly program generated by cmoc 0.1.97


	.section .rom,"ax",@progbits


	.globl	_puthex16


;******************************************************************************

; FUNCTION puthex16(): defined at cc_tests16.c:10
_puthex16:
; Prototype: void puthex16(unsigned int)
; Calling convention: 0 (CMOC Default)
	pshs	U
	leau	,S
; Formal parameter(s):
;      4,U:    2 bytes: val: unsigned int: line 10
; Line cc_tests16.c:11: function call: puthex()
	ldd	4,U	; variable `val', declared at cc_tests16.c:10
	tfr	A,B	; shift D 8 bits right
; optim: stripOpToDeadReg
; Cast from `unsigned int' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Line cc_tests16.c:12: function call: puthex()
	ldd	4,U	; variable val
; optim: stripOpToDeadReg
; optim: stripUselessBitwiseOp
; Cast from `unsigned int' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Useless label L00007 removed
	leas	,U
	puls	U,PC
; END FUNCTION puthex16(): defined at cc_tests16.c:10
funcend_puthex16:
	.set	funcsize_puthex16, funcend_puthex16-_puthex16
	.globl	_main


;******************************************************************************

; FUNCTION main(): defined at cc_tests16.c:15
_main:
; Prototype: int main(void)
; Calling convention: 0 (CMOC Default)
; Line cc_tests16.c:16: function call: puthex16()
; Line cc_tests16.c:16: function call: test_identity16()
	ldd	#$BEEF	; decimal 48879 unsigned
	pshs	B,A	; C function argument 1 of test_identity16(): unsigned int
	lbsr	_test_identity16
	leas	2,S
	pshs	B,A	; C function argument 1 of puthex16(): unsigned int
	lbsr	_puthex16
	leas	2,S
; Line cc_tests16.c:17: function call: putnl()
	lbsr	_putnl
; Line cc_tests16.c:18: function call: puthex16()
; Line cc_tests16.c:18: function call: test_add16()
	ldx	#$4321	; decimal 17185 signed (optim: optimizeConsecutiveFunctionArguments)
; optim: optimizeConsecutiveFunctionArguments
	ldd	#$1234	; decimal 4660 signed
	pshs	X,B,A	; C function argument 1 of test_add16(): int (optim: optimizeConsecutiveFunctionArguments)
	lbsr	_test_add16
	leas	4,S
	pshs	B,A	; C function argument 1 of puthex16(): unsigned int
	lbsr	_puthex16
	leas	2,S
; Line cc_tests16.c:19: function call: putnl()
	lbsr	_putnl
; Line cc_tests16.c:20: function call: puthex16()
; Line cc_tests16.c:20: function call: test_sub16()
	ldx	#$01	; decimal 1 signed (optim: optimizeConsecutiveFunctionArguments)
; optim: optimizeConsecutiveFunctionArguments
	ldd	#$8000	; decimal 32768 unsigned
	pshs	X,B,A	; C function argument 1 of test_sub16(): unsigned int (optim: optimizeConsecutiveFunctionArguments)
	lbsr	_test_sub16
	leas	4,S
	pshs	B,A	; C function argument 1 of puthex16(): unsigned int
	lbsr	_puthex16
	leas	2,S
; Line cc_tests16.c:21: function call: putnl()
	lbsr	_putnl
; Line cc_tests16.c:22: function call: halt()
	lbsr	_halt
; Line cc_tests16.c:23: return with value
	clra
	clrb
; optim: branchToNextLocation
; Useless label L00008 removed
	rts
; END FUNCTION main(): defined at cc_tests16.c:15
funcend_main:
	.set	funcsize_main, funcend_main-_main






	.section .rom,"ax",@progbits


string_literals_start:
string_literals_end:


;******************************************************************************

; READ-ONLY GLOBAL VARIABLES






	.section .rom,"ax",@progbits


; Statically-initialized global variables
; Statically-initialized local static variables






	.section .bss


bss_start:
; Uninitialized global variables
; Uninitialized local static variables
bss_end:






