; 6809 assembly program generated by cmoc 0.1.97


	.section .rom,"ax",@progbits


	.globl	_puthex16


;******************************************************************************

; FUNCTION puthex16(): defined at test_interop_all.c:12
_puthex16:
; Prototype: void puthex16(unsigned int)
; Calling convention: 0 (CMOC Default)
	pshs	U
	leau	,S
; Formal parameter(s):
;      4,U:    2 bytes: val: unsigned int: line 12
; Line test_interop_all.c:13: function call: puthex()
	ldd	4,U	; variable `val', declared at test_interop_all.c:12
	tfr	A,B	; shift D 8 bits right
; optim: stripOpToDeadReg
; Cast from `unsigned int' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Line test_interop_all.c:14: function call: puthex()
	ldd	4,U	; variable val
; optim: stripOpToDeadReg
; optim: stripUselessBitwiseOp
; Cast from `unsigned int' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Useless label L00007 removed
	leas	,U
	puls	U,PC
; END FUNCTION puthex16(): defined at test_interop_all.c:12
funcend_puthex16:
	.set	funcsize_puthex16, funcend_puthex16-_puthex16
	.globl	_main


;******************************************************************************

; FUNCTION main(): defined at test_interop_all.c:17
_main:
; Prototype: int main(void)
; Calling convention: 0 (CMOC Default)
; Line test_interop_all.c:19: function call: puthex()
; Line test_interop_all.c:19: function call: llvm_add8()
;
; HAND-EDITED (no longer a faithful CMOC capture): the original CMOC
; output for the second i8 arg used `clra; pshs B,A` (a 2-byte slot
; with the byte at offset+1, because CMOC promotes char→int when
; passing byte args via __gcccall). LLVM-MC6809 now uses gcc6809's
; convention (1-byte slot, byte at offset 0) — see CC_MC6809 in
; MC6809CallingConv.td. CMOC's actual output won't link cleanly
; against the new LLVM convention; this hand-edit demonstrates what
; CMOC *should* emit if it were updated to match gcc6809.
	ldb	#$12	; second i8 arg → 1-byte stack slot
	pshs	B
; function receives argument in B
	ldb	#48	; __gcccall: first byte-sized argument
	lbsr	_llvm_add8
	leas	1,S
; Cast from `char' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Line test_interop_all.c:20: function call: putnl()
	lbsr	_putnl
; Line test_interop_all.c:22: function call: puthex()
; Line test_interop_all.c:22: function call: llvm_negate8()
; optim: stripConsecutiveLoadsToSameReg
; function receives argument in B
	ldb	#190	; __gcccall: first byte-sized argument
	lbsr	_llvm_negate8
; Cast from `char' to byte: result already in B
	clra	; promoting byte argument to word
	pshs	B,A	; C function argument 1 of puthex(): unsigned char
	lbsr	_puthex
	leas	2,S
; Line test_interop_all.c:23: function call: putnl()
	lbsr	_putnl
; Line test_interop_all.c:25: function call: puthex16()
; Line test_interop_all.c:25: function call: llvm_identity16()
; optim: optimizeXParameterLoad (case 1)
; optim: optimizeXParameterLoad (case 1)
	ldx	#48879	; __gcccall: first word-sized argument
	lbsr	_llvm_identity16
	tfr	X,D	; 16-bit result received in X as per GCC6809 convention
	pshs	B,A	; C function argument 1 of puthex16(): unsigned int
	lbsr	_puthex16
	leas	2,S
; Line test_interop_all.c:26: function call: putnl()
	lbsr	_putnl
; Line test_interop_all.c:27: function call: puthex16()
; Line test_interop_all.c:27: function call: llvm_identity16()
; optim: optimizeXParameterLoad (case 1)
; optim: optimizeXParameterLoad (case 1)
	ldx	#4660	; __gcccall: first word-sized argument
	lbsr	_llvm_identity16
	tfr	X,D	; 16-bit result received in X as per GCC6809 convention
	pshs	B,A	; C function argument 1 of puthex16(): unsigned int
	lbsr	_puthex16
	leas	2,S
; Line test_interop_all.c:28: function call: putnl()
	lbsr	_putnl
; Line test_interop_all.c:29: function call: halt()
	lbsr	_halt
; Line test_interop_all.c:30: return with value
	clra
	clrb
; optim: branchToNextLocation
; Useless label L00008 removed
	rts
; END FUNCTION main(): defined at test_interop_all.c:17
funcend_main:
	.set	funcsize_main, funcend_main-_main






	.section .rom,"ax",@progbits


string_literals_start:
string_literals_end:


;******************************************************************************

; READ-ONLY GLOBAL VARIABLES






	.section .rom,"ax",@progbits


; Statically-initialized global variables
; Statically-initialized local static variables






	.section .bss


bss_start:
; Uninitialized global variables
; Uninitialized local static variables
bss_end:






